### ISSUE TITLE
If TERM is not set as xterm or something similar, DB.Repo doesn't work

### ISSUE THREAD

**Issue by johnhamelink** [bitwalker/distillery#106]
I was also experiencing this error in exrm, for what it's worth :smile: 

### Steps to reproduce

- Install [termite](https://github.com/thestinger/termite/)
- Deploy a distillery release that includes Ecto onto a server
- SSH in
- `/opt/<app>/bin/<app> remote_console`
- Press `tab`, `up`, `down` to see how the REPL behaves differently
- Attempt to get something from the repo

Now to show the fix:

- Install [termite](https://github.com/thestinger/termite/)
- Deploy a distillery release that includes Ecto onto a server
- Run `export TERM=xterm`
- SSH in
- `/opt/<app>/bin/<app> remote_console`
- Press `tab`, `up`, `down` to see how the REPL behaves as expected
- Attempt to get something from the repo

### Verbose Logs

Error from Ecto:

```
deploy@ip-10-0-1-54:/home/ubuntu$ /opt/api/bin/api remote_console
Interactive Elixir (1.3.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(remshc1bc3153-api@127.0.0.1)1> import Ecto.Query, only: [from: 2]
iex(remshc1bc3153-api@127.0.0.1)2> DB.Repo.one(from g in DB.Group, limit: 1)
iex(remshc1bc3153-api@127.0.0.1)3> 
** (ArgumentError) repo DB.Repo is not started, please ensure it is part of your supervision tree
    lib/ecto/query/planner.ex:65: Ecto.Query.Planner.query_lookup/5
    lib/ecto/query/planner.ex:48: Ecto.Query.Planner.query_with_cache/6
    lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
    lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    lib/ecto/repo/queryable.ex:64: Ecto.Repo.Queryable.one/4
iex(remshc1bc3153-api@127.0.0.1)3> 
```

### Description of issue

- What are the expected results?

Either the Ecto query works correctly or `remote_console` checks the TERM variable to make sure its acceptable before starting the console. The real error here is that it's not obvious what has gone wrong.

- What OS, Erlang/Elixir versions are you seeing this issue on?

Dev machine:

Arch Linux, ZSH and Termite

Server:

Ubuntu 14.04.05, ERTS 7.3, Elixir 1.3.1, distillery 0.10.0

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

https://gist.github.com/johnhamelink/80eff933eb2503f0bf01038cb5bd9230

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

N/A

**Comment by spscream** [comment]
had the same issue with in-docker setup

**Comment by bitwalker** [comment]
The problem is that I'm not entirely sure what valid values of TERM will work as expected here. I set `TERM=xterm` in my containerized environments, but I'm not sure it's a good idea to do that in the release script for everyone. However, we can probably safely set it to `xterm` if TERM is unset.

**Comment by bitwalker** [comment]
I've set the boot script to set `TERM=xterm` if `TERM` is unset, that's about the best we can do here.
