### ISSUE TITLE
Task permanently changes terminal colours

### ISSUE THREAD

**Issue by CrowdHailer** [bitwalker/distillery#109]
### Steps to reproduce

Simply running the `mix release` task. This issue occurs in a demo project I have been working on that uses vagrant. Cloning at [this commit](https://github.com/CrowdHailer/baobab.ex/commit/257c8fa9e08ecb11c3cadef64299a7fd7ae88f70), should allow exactly the same environment to be created
### Verbose Logs

```
vagrant@baobab:/vagrant$ mix release
==> Assembling release.. # This line is blue
==> Building release baobab:0.0.1 using environment prod
==> Including ERTS 8.1 from /usr/lib/erlang/erts-8.1
==> Packaging release..
==> Release successfully built! # This line is green 
    You can run it in one of the following ways:
      Interactive: rel/baobab/bin/baobab console
      Foreground: rel/baobab/bin/baobab foreground
      Daemon: rel/baobab/bin/baobab start
vagrant@baobab:/vagrant$ echo 'hello' # These lines are still green.
hello
```
### Description of issue
- When running the mix release task the terminal output changes to green. This change persists and permanently alters the bash shell.

**Comment by bitwalker** [comment]
I just had this happen to me today, something in the logger must have left off a trailing reset.

**Comment by bitwalker** [comment]
Fixed in master
