### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by CrowdHailer** [bitwalker/distillery#110]
This issue is not a bug report so it doesn't necessarily belong here. I would like to suggest a link on the README which shows people how to ask questions or see a FAQ. The exrm slack channel might do, all though its lack of history is annoying for the purposes of generating a FAQ.

The question that I wanted to ask in such a forum was. should the the `rel` directory be added to .gitignore. It seams that there is a lot of noise by including every release in version control but as they should not be recreated maybe it does make sense for them to exist in version control

**Comment by bitwalker** [comment]
That's a good idea, I'll add some pointers in the README.

To answer your question, I add `rel/<release-name>` to my `.gitignore`, that way all of my core release config files (config.exs, vm.args, etc.) are source controlled, but the release artifacts are not. Those artifacts will be moving to _build soon though, so it will be less of a concern at that point.

**Comment by bitwalker** [comment]
Just an update here about your question, but build output is now being placed under `_build` by default (in master), rather than `rel`, so you can now just source control all of `rel`.
