### ISSUE TITLE
Documentation Suggestions for .gitignore and duplicate module names

### ISSUE THREAD

**Issue by aphillipo** [bitwalker/distillery#112]
### Steps to reproduce

These are documentation suggestions:

1) It should be clear what I should .gitignore
2) Duplicate modules in applications should have a discussion in the FAQ.  
### Verbose Logs

If you want me to add either of these I can write something I'm sure.
### Description of issue

Duplicated modules should display a message suggesting that one of the package authors stop having conflicting modules names.

I'm not sure what can safely be added to .gitignore 

Distillery is excellent btw!  Thanks!

**Comment by bitwalker** [comment]
@aphillipo Great suggestions! I'll add this to my todo list.

**Comment by aphillipo** [comment]
Please include in the docs the idea that the priv/static directory should be in your github if you are doing deployment from something like travis-ci.

By default with phoenix it's not included in git and therefore not the release!

**Comment by aphillipo** [comment]
Absolutely nailed it - great news about moving releases to _build.

Will there be upgrade instructions as to how to move things to the new directory structure?

Amazing work on this project; thank you so so much!
