### ISSUE TITLE
Consider adding runtime_tools to the generated config.exs applications

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/distillery#12]
Runtime tools are important if anyone wants to use most of the awesome tooling erlang gives us for debugging running systems. With the `applications` configuration in releases I feel like we have a perfect place to define this - it doesn't really make sense for the application itself to depend on the `runtime_tools`. I think it would be reasonable to include the application by default.

It's relatively large with 296K, but I don't think it matters that much.

**Comment by archSeer** [comment]
@michalmuskala this issue was closed, but #13 seems to address a different bug altogether?
