### ISSUE TITLE
Equivalent to $RELEASE_CONFIG_FILE from exrm

### ISSUE THREAD

**Issue by GalaxyGorilla** [bitwalker/distillery#120]
Hey,

I used exrm for some time and was used to the env variable $RELEASE_CONFIG_FILE to point to my production config. Is it still there or maybe some equivalent variable?

At https://hexdocs.pm/distillery/shell-script-api.html#environment-variables I cannot see something like that apart from $RELEASE_CONFIG_DIR.

EDIT: After some time playing around I have to say that distillery left a really positive impression on me :).

**Comment by bitwalker** [comment]
@GalaxyGorilla Thanks! So you have two options, the most direct equivalent is `$SYS_CONFIG_PATH`, but you can also store *all* release files in an external directory using `$RELEASE_CONFIG_DIR`, which will expect `sys.config`, `vm.args`, etc., but will fallback to the release directory for those as needed.
