### ISSUE TITLE
Add easy way of configuring plugins

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/distillery#128]
Today, most of the plugins, I've seen are configured by adding stuff to `mix.exs`, but I don't think this is a good option, since distillery has it's configuration infrastructure in `rel/config.exs`.

Unfortunately there's no way of passing options to the plugins. The ideal way would be passing a keyword to the `plugin` - this seems the most natural option.

``` elixir
environment :prod do
  plugin FooPlugin, foo: 1, bar: 2
end
```

The harder part is figuring out how to provide those options to plugins in a backwards-compatible way. Probably the most obvious one would be an additional argument to all the callback functions, but that's not backwards compatible. I propose adding a new field in the `%Release{}` struct called `plugins` that would hold a map of plugin to options configuration - the default would be an empty list. This would mean the options could be accessed with something like:

``` elixir
  def after_package(release) do
    opts = release.plugins[__MODULE__]
    # ...
  end
```

**Comment by bitwalker** [comment]
What about something more like what exists in `config/*.exs`, such as the following example:

```elixir
config FooPlugin,
  foo: 1,
  bar: 2
```

Then I'll use `PLUGIN.__info__(:functions)` to check to see if that plugin exports `callback/oldN+1`, if so, I'll pass the configuration proplist as the second argument, if not, then the plugin won't receive the second argument. For backwards-compatibility, plugins can expose both callbacks, and use the old arity to provide default values, or use an alternative means for getting the configuration.

Thoughts?

**Comment by michalmuskala** [comment]
We don't need to use `Mod.__info__/1` - we can use the `function_exported?/3` BIF. 

I was thinking about using `config`, but ultimately proposed something else because of one thing - when somebody sees: "put that in the config", they will put it in `config/config.exs` and not in `rel/config.exs` and it will cause a lot of confusion. The `plugin` thing is unambiguous - it works only in the release configuration. Also having it separate creates another place for potential typos.

On the other hand `config` would allow to separate definition options from actually enabling the plugin, so you could have the plugin configured in `environment` and enabled in `release` (or the reverse).

I'm not 100% sure which one is better. I would lean towards passing options to `plugin` since it's similar, for example, to how `plug` works.

**Comment by bitwalker** [comment]
The parallel to `plug` is a good point, it's familiar, and won't get confusing in documentation as you've pointed out.

Good call on `function_exported?/3` by the way, I knew something like that existed, but could not recall the name, thanks for the reminder :)

I'll add this to the TODO list!
