### ISSUE TITLE
Document moving from rel/ to _build/

### ISSUE THREAD

**Issue by aphillipo** [bitwalker/distillery#131]
Is there clear documentation on moving/upgrading from the current rel directory to _build?  Be good because I have a feeling everything may break :-)  Ta!

**Comment by bitwalker** [comment]
The documentation has been updated to reflect the change, and the new `output_dir` config setting has also been documented. Other than the new root path, everything about the filesystem layout is the same, and you can effectively change back to `rel` with `set output_dir: "./rel/myapp"` in your `config.exs`. Is there anything else you'd like to see in the docs?

**Comment by aphillipo** [comment]
No that sounds perfect.  I will try this now.
