### ISSUE TITLE
Undefined applications: [stdlib,kernel]

### ISSUE THREAD

**Issue by andrewtimberlake** [bitwalker/distillery#134]
Config generated from `mix release.init`

```bash
$ MIX_ENV=prod mix do release --env=prod --verbose
==> Loading configuration..
==> Assembling release..
==> Building release vulcan_greet_cycle:0.0.1 using environment prod
==> Discovered applications:
  bamboo_sparkpost-0.5.1
    from: _build/prod/lib/bamboo_sparkpost
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :bamboo
    includes: none

  httpoison-0.9.2
    from: _build/prod/lib/httpoison
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
    includes: none

  bamboo-0.5.0
    from: _build/prod/lib/bamboo
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :httpoison
      :poison
    includes: none

  timex_ecto-3.0.5
    from: _build/prod/lib/timex_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :timex
    includes: none

  combine-0.9.2
    from: _build/prod/lib/combine
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  metrics-1.0.1
    from: _build/prod/lib/metrics
    applications:
      :kernel
      :stdlib
    includes: none

  ssl_verify_fun-1.1.1
    from: _build/prod/lib/ssl_verify_fun
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  certifi-0.7.0
    from: _build/prod/lib/certifi
    applications:
      :kernel
      :stdlib
    includes: none

  mimerl-1.0.2
    from: _build/prod/lib/mimerl
    applications:
      :kernel
      :stdlib
    includes: none

  idna-1.2.0
    from: _build/prod/lib/idna
    applications:
      :kernel
      :stdlib
    includes: none

  ssl-8.0.3
    from: /usr/lib/erlang/lib/ssl-8.0.3
    applications:
      :crypto
      :public_key
      :kernel
      :stdlib
    includes: none

  hackney-1.6.3
    from: _build/prod/lib/hackney
    applications:
      :kernel
      :stdlib
      :kernel
      :stdlib
      :crypto
      :asn1
      :public_key
      :ssl
      :idna
      :mimerl
      :certifi
      :ssl_verify_fun
      :metrics
    includes: none

  tzdata-0.5.9
    from: _build/prod/lib/tzdata
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
      :logger
    includes: none

  timex-3.1.3
    from: _build/prod/lib/timex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
      :gettext
      :combine
    includes: none

  uuid-1.1.5
    from: _build/prod/lib/uuid
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  base64url-0.0.1
    from: _build/prod/lib/base64url
    applications:
      :kernel
      :stdlib
    includes: none

  public_key-1.2
    from: /usr/lib/erlang/lib/public_key-1.2
    applications:
      :asn1
      :crypto
      :kernel
      :stdlib
    includes: none

  asn1-4.0.4
    from: /usr/lib/erlang/lib/asn1-4.0.4
    applications:
      :kernel
      :stdlib
    includes: none

  jose-1.8.0
    from: _build/prod/lib/jose
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :asn1
      :public_key
      :base64url
    includes: none

  guardian-0.13.0
    from: _build/prod/lib/guardian
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :poison
      :jose
      :uuid
    includes: none

  canada-1.0.1
    from: _build/prod/lib/canada
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  comeonin-2.6.0
    from: _build/prod/lib/comeonin
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
    includes: none

  phoenix_helpers-0.1.0
    from: _build/prod/lib/phoenix_helpers
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :comeonin
      :canada
      :guardian
      :timex
      :timex_ecto
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  db_connection-1.0.0
    from: _build/prod/lib/db_connection
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :connection
    includes: none

  postgrex-0.12.1
    from: _build/prod/lib/postgrex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :db_connection
      :decimal
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      :kernel
      :stdlib
    includes: none

  decimal-1.2.0
    from: _build/prod/lib/decimal
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  ecto-2.0.5
    from: _build/prod/lib/ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :decimal
      :poolboy
    includes: none

  phoenix_ecto-3.0.1
    from: _build/prod/lib/phoenix_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :plug
    includes: none

  gettext-0.12.1
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  ranch-1.2.1
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
    includes: none

  cowboy-1.0.4
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  phoenix_html-2.7.0
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  phoenix_pubsub-1.0.1
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  eex-1.3.3
    from: /usr/local/lib/elixir/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-3.0.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  mime-1.0.1
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  logger-1.3.3
    from: /usr/local/lib/elixir/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  crypto-3.7.1
    from: /usr/lib/erlang/lib/crypto-3.7.1
    applications:
      :kernel
      :stdlib
    includes: none

  plug-1.2.2
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  phoenix-1.2.1
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  compiler-7.0.2
    from: /usr/lib/erlang/lib/compiler-7.0.2
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.3.3
    from: /usr/local/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.1
    from: /usr/lib/erlang/lib/stdlib-3.1
    applications:
      :kernel
    includes: none

  kernel-5.1
    from: /usr/lib/erlang/lib/kernel-5.1
    applications: none
    includes: none

  vulcan_greet_cycle-0.0.1
    from: _build/prod/lib/vulcan_greet_cycle
    applications:
      :kernel
      :stdlib
      :elixir
      :phoenix
      :phoenix_pubsub
      :phoenix_html
      :cowboy
      :logger
      :gettext
      :phoenix_ecto
      :postgrex
      :phoenix_helpers
      :bamboo
      :bamboo_sparkpost
    includes: none

  iex-1.3.3
    from: /usr/local/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.1
    from: /usr/lib/erlang/lib/sasl-3.0.1
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:vulcan_greet_cycle
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.1"
    output_dir="rel/vulcan_greet_cycle"
==> Copying applications to rel/vulcan_greet_cycle
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.1 from /usr/lib/erlang/erts-8.1
==> Generating boot script
==> Failed to build release:

    Undefined applications: [stdlib,kernel]
```

**Comment by andrewtimberlake** [comment]
If I add `:stdlib, :kernel` to `:applications` then the release builds but that doesn’t seem right.

**Comment by bitwalker** [comment]
Yeah that's strange indeed. Would you mind giving master a shot? There have been a number of fixes since 0.10.1, and I suspect this may already be resolved.

**Comment by danturn** [comment]
Heya, I had this issue and have tried with master with the same results :*(

==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :earmark

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Failed to build release:
    Undefined applications: [stdlib,kernel]

**Comment by danturn** [comment]
not sure if it helps but i had bamboo and json in my included applications bit of mix.exs, if i remove them then the release builds (albeit with a warning about bamboo and json not being included in the release)

**Comment by tmepple** [comment]
Thanks @danturn, I was struggling for hours with this issue.  It wouldn't build even when adding :stdlib and :kernel to applications (as worked for @andrewtimberlake) or building with distillery master.

By following your suggestion and simply removing bamboo from applications my umbrella release finally builds under both master and 0.10.1 without complaining about :stdlib and :kernel.  Also the release installs/runs properly in staging sans the bamboo email functionality.

I was scanning the bamboo source briefly to see if I could figure out what's special about it but really have no idea given my limited experience.

**Comment by mdowell12** [comment]
FYI, experienced same error running on current master.  I also was releasing with some applications not included in my `mix.exs` file's `applications` section, producing the following warning:

    ==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :covertool
    :earmark
    :ex_doc
    :meck
    :parallel_stream
    :proper

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

I added each of these to my `mix.exs` file's `applications` section and was able to build the release.

**Comment by bitwalker** [comment]
Is there a reason you all are using `included_applications` instead of `applications`? Looks like there is an issue when using `included_applications`, though I haven't looked into it yet, but you shouldn't be using `included_applications` unless you have an really good reason.

If you omit applications from your applications list, then you should expect to see that warning, and you should also expect to see your application fail at runtime because your dependencies aren't in the release. The documentation covers how to silence that warning for things which are built-time only dependencies which you know you don't need at runtime.

If you need to include applications in the release, but not start them, because you wish to start them yourself, then leave them out of your applications list in `mix.exs`, and use `set applications: [some_app: :load]` in `rel/config.exs` to append them to the applications list as load-only apps. You don't need to do this for library applications (i.e. they don't export an application start/stop callback), just put them in `applications`.

**Comment by tmepple** [comment]
I'm not using `included_applications` and have included all required applications in `applications` so they are properly copied into the release.

Looking again at this tonight, it's strange but my non-umbrella app properly compiles bamboo into the release and everything works great.  After I refactored the exact same app into an umbrella app in the structure of phoenix 1.3 master (the phoenix part in `apps/my_app_web` and the ecto/service part in `apps/my_app`) it would not build a release and started complaining about `:stdlib` and `:kernel` being undefined.  The only way I can get the umbrella to compile into a working release is to remove bamboo from applications.  I also had to include distillery in the umbrella`mix.exs` to get it to work.

I wish I could help further diagnose this but not sure what info to provide to help?

**Comment by danturn** [comment]
Hi, I'm using included_applications because they don't require starting. Json, for example, doesnt need to be started as an app to be used. I suppose it doesnt hurt to start it anyway so I could try this.

It does seem that everyone here with this problem is using Bamboo though so maybe its only an issue with that?

**Comment by mdowell12** [comment]
@danturn for the record, I didn't have Bamboo and still experienced the issue.

**Comment by brucepom** [comment]
I received the same error this morning.
```
==> Failed to build release:
Undefined applications: [stdlib,kernel]
```
I was using Edeliver and for me the solution was to move `:edeliver` to the end of the applications list (this is documented on Edeliver's page so I was aware of it but I'd accidentally added an app after it):
```
def application do
    [mod: {MyApp, []},
     applications: [... everything else ..., :edeliver]] # <- Edeliver should be the last item
end
```

**Comment by tmepple** [comment]
I finally solved my issue and got a good working build using bamboo master instead of the latest release 0.7.0.  I think the root of the issue may be bamboo 0.7.0's dependency on httpoison v0.9.  Bamboo master uses hackney instead.  

When I test by adding httpoison ~> 0.9 to my deps/apps the error `Undefined applications: [stdlib,kernel]` reoccurs.

**Comment by Gazler** [comment]
I have experienced this issue. It appears to be something to do with the order in the applications list.

The line that causes the error is https://github.com/bitwalker/distillery/blob/752f0dd1b125dae6fa0cf2626350132b486edd05/lib/mix/lib/releases/assembler.ex#L693

Here is a repo containing the most minimal example I could create that replicates the issue. https://github.com/Gazler/broken_release All the dependencies in the mix.exs files are required to trigger the issue.

You will see that both `app1` and `dep1` contain the `rollbax` dependency: https://github.com/Gazler/broken_release/blob/master/apps/dep1/mix.exs#L38
https://github.com/Gazler/broken_release/blob/master/apps/app1/mix.exs#L42

I have included two versions of the applications list in `app1/mix.exs` one that works and one that fails. From this you can see that the order is significant.

https://github.com/Gazler/broken_release/blob/master/apps/app1/mix.exs#L22

Hope this helps!

**Comment by Gazler** [comment]
This issue on relx may be relevant https://github.com/erlware/relx/issues/492

**Comment by pharosproduction** [comment]
I have solved this issue by shuffling applications(6 apps in umbrella) in Mix.Releases.Config. I haven't yet found why some order works and other is not, but looks like it's about dependancies between umbrella apps.

**Comment by bitwalker** [comment]
@danturn Just FYI, but your reason for using `included_applications` is actually not what it's for, and in fact is likely to cause more issues than not. `included_applications` is intended only to be used when you are manually controlling the lifecycle for some dependency, and in that case, no other application can depend on it. You shouldn't worry about starting "library" applications, such as `:json` - as it is effectively a no-op anyway, but even if it wasn't, there is no reason *not* to start them, your application depends on them, and if they need to run a supervisor tree for some reason, then it's important that they be able to do so.

@Gazler Thanks for the hard work! I recall seeing this issue before with relx and exrm, I'm not certain what causes this to occur, but I'll try and do some more in depth digging. In the meantime, at least we have a workaround.

**Comment by ontofractal** [comment]
Sharing this to help others solve this issue easier. 

Got the same error with :websocket_client, fixed by moving it to the end of the :applications list. Got the error again after adding some applications and solved again by moving :distillery to the `-2` position in the :applications list. 

My working config looks like this.
`
   def application do
    # FIXME If you move :distillery or :websocket_client apps from their last position in the list, release build will throw
    # Undefined applications: [stdlib,kernel] error
    [applications: [...usual deps..., :distillery, :websocket_client],
    mod: {CryptoMonitor, []}]
  end

`

**Comment by bitwalker** [comment]
@ontofractal you don't need distillery in your applications list, it's build-time only :)
