### ISSUE TITLE
Distributed node name specification

### ISSUE THREAD

**Issue by meyercm** [bitwalker/distillery#140]
### Overview / Discussion

I'm a bit confused over configuring a release of a distributed node.  I like the `config.exs` approach and I expected it to be my one-stop shop for runtime configuration, but it seems that I cannot set the node name, while the sister config item, `set cookie: :"<cookie>"` is available.

Once I embraced using a custom `vm.args` to specify the name, I ran into a conflict specifying the cookie- if it is not specified in the custom `vm.args`, the release will not start; but if it is not specified in `config.exs`, then `Distillery` barfs a warning and threatens a future error. Setting the cookie in both places works, but it's not obvious which cookie is going to be the winner.

My preferred resolution would be to allow a `set name: :"<node_name>"` config item inside `config.exs`, though if that's technically infeasible, then inverting the warning/future error when using custom `vm.args` makes the most sense (i.e. raise a warning when specifying both a cookie and custom vm.args in `config.exs`)

### Relevant Output

Cookie not specified in `config.exs`:

```
==> Attention! You did not provide a cookie for the erlang distribution protocol in rel/config.exs
    For backwards compatibility, the release name will be used as a cookie, which is potentially a security risk!
    Please generate a secure cookie and use it with `set cookie: <cookie>` in rel/config.exs.
    This will be an error in a future release.
```

Cookie not specified in `vm.args`:

```
# rel/poof/bin/my_app console
a secret cookie must be provided in one of the following ways:
  - with vm.args using the -setcookie parameter,
  or
  by writing the cookie to '/root/.erlang.cookie', with permissions set to 0400
```

### Configuration

- Ubuntu 16.04
- Erlang 19.1
- Elixir 1.3.4
- Distillery 0.10.1

**Comment by tonyvanriet** [comment]
Regarding the warning, in #129, @bitwalker suggests leaving a placeholder cookie value in `rel/config.exs` when using a custom `vm.args` to avoid the need for distillery to parse the custom `vm.args` file.

As for configuring the node name, I found myself looking for that capability as well. If it's not appropriate for this to be a `config.exs` setting, then perhaps overlays can help us get this done.
Discussed in #121.

**Comment by bitwalker** [comment]
It's possible to make the base nodename configurable via `config.exs`, though I think it's a better practice to set that in the environment of the target machine in conjunction with `REPLACE_OS_VARS=true`. In any case, I think we can scan the custom `vm.args` and only produce a warning if the cookie is missing in both places, rather than always printing a warning like today.

**Comment by jesseshieh** [comment]
I notice in vm.args that the node basename is configurable, but the host is not. Is it normal to keep the host as 127.0.0.1 or is there a way to configure the host in a distributed production system?

**Comment by bitwalker** [comment]
You can provide your own `vm.args` and set `-name` to whatever value you would like. `127.0.0.1` is just a safe default value (as you may not want the node to be reachable from other hosts). The key is that the host needs to be resolvable (a "fake" hostname will work as long as you don't try to connect to the node from any other nodes, but will fail if you do).
