### ISSUE TITLE
Difficult to make release without hard coded cookie.

### ISSUE THREAD

**Issue by obmarg** [bitwalker/distillery#148]
I'm trying to use distillery to build distributable releases of some applications I've made, and ideally I want to upload a .tar.gz to github that anyone can download and and run.  

Ideally I'd like to use a cookie stored in `$HOME/.erlang.cookie`, so that users of the app aren't all sharing the same cookie that's publicly available in the repository.  I borrowed the pre-start script from #100 to actually generate this cookie on startup, but I can't see an easy way to make a distillery release use it.  The generated `vm.args` always includes a `-setcookie` line, and it doesn't look like there's any way to remove it.

I understand I can provide my own vm.args file at runtime by setting `RELEASE_CONFIG_DIR`, but it'd be a lot nicer if I didn't have to ask users to do that.

**Comment by obmarg** [comment]
Yeah, good point.  That probably would work.

**Comment by jesseshieh** [comment]
I did the following which seems to work for me: `set cookie: :"${MY_COOKIE}"`.
Then when starting the app, set `MY_COOKIE=foo REPLACE_OS_VARS=true bin/web console`.
You can verify once you get an IEx prompt by typing `Node.get_cookie`

**Comment by bitwalker** [comment]
That's the approach I use as well :)
