### ISSUE TITLE
Distinct cookies for dev and prod environments

### ISSUE THREAD

**Issue by tonyvanriet** [bitwalker/distillery#149]
When running `mix release.init`, a cookie is generated and used in both the `dev` and `prod` environments in `rel/config.exs`.

Would it make sense to instead generate a distinct cookie for `dev` and `prod` each, to help avoid accidentally connecting a `dev` node to the `prod` cluster? Obviously the node names would be the primary way to avoid this, but I still can't think of a reason *not* to use distinct cookies in each environment.

I'd be happy to work on a PR if there's agreement.

**Comment by bitwalker** [comment]
Sure, that's an easy change to make and I think it makes good sense to generate distinct cookies. Great suggestion!
