### ISSUE TITLE
A release name other than the app_name doesn't start all the applications

### ISSUE THREAD

**Issue by minhajuddin** [bitwalker/distillery#159]
### Steps to reproduce

Change the `rel/config.exs` to

```elixir
use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :"foo_server_#{Mix.env}",
    # This sets the default environment used by `mix release`
    default_environment: Mix.env
# ...
environment :staging do
  set include_erts: true
  set include_src: false
  set cookie: :"<snip>"
end

# ...

release :"foo_server_#{Mix.env}" do
  set version: current_version(:foo_server)
end
```
Build the project using `MIX_ENV=staging mix release --verbose`

Now, when I run `_build/staging/rel/foo_server_staging/bin/foo_server_staging foreground` it doesn't start the phoenix app or the other apps.

### Verbose Logs
```text
==> Loading configuration..
==> Assembling release..
==> Building release foo_server_staging:0.1.1481192764 using environment staging
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :calendar
    :cowboy
    :gettext
    :foo_shared
    :httpoison
    :logger_file_backend
    :mailer
    :phoenix
    :phoenix_ecto
    :phoenix_html
    :postgrex
    :redix
    :rollbax

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Discovered applications:
  compiler-7.0.2
    from: /usr/lib/erlang/lib/compiler-7.0.2
    applications:
      :kernel
      :stdlib
    includes: none

  stdlib-3.1
    from: /usr/lib/erlang/lib/stdlib-3.1
    applications:
      :kernel
    includes: none

  kernel-5.1
    from: /usr/lib/erlang/lib/kernel-5.1
    applications: none
    includes: none

  elixir-1.3.4
    from: /usr/local/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  iex-1.3.4
    from: /usr/local/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.1
    from: /usr/lib/erlang/lib/sasl-3.0.1
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:foo_server_staging
    release_version="0.1.1481192764"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.1"
    output_dir="_build/staging/rel/foo_server_staging"
==> Copying applications to _build/staging/rel/foo_server_staging
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.1 from /usr/lib/erlang/erts-8.1
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.1481192764/commands
==> Packaging release..
==> Archiving foo_server_staging-0.1.1481192764
==> Writing tarball to _build/staging/rel/foo_server_staging/releases/0.1.1481192764/foo_server_staging.tar.gz
==> Updating tarball
==> Tarball updated!
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/staging/rel/foo_server_staging/bin/foo_server_staging console
      Foreground: _build/staging/rel/foo_server_staging/bin/foo_server_staging foreground
      Daemon: _build/staging/rel/foo_server_staging/bin/foo_server_staging start
```

### Description of issue

I expected it to start all the appslications, However, it doesn't start any. Changing the release name to match the app_name makes it work

I am using Elixir 1.3.4 on Erlang 19 and distillery 1.0. The app_name is `foo_server` whereas the release name is `foo_server_staging`. I need this as I'll be running a *staging* and *sandbox* environment on the same box.

**Comment by minhajuddin** [comment]
I was using releases to get multiple instances of the same app running on the same server. One for staging and one for sandbox. `epmd` complains if you try to start a second app with the same name on the same server. I thought a release was a good way to create different named nodes. Hence the problem.

However, I've found a workaround using the `erl_opts` setting in the environments (which should have been obvious). My environment block is configured as:

```elixir
#...
environment :staging do
  set include_erts: true
  set include_src: false
  # set a node name so that epmd doesn't complain if two foo_servers are running on the same server
  set erl_opts: "-sname foo_server_staging"
  set cookie: :"<snip>"
end

environment :sandbox do
  set include_erts: true
  set include_src: false
  # set a node name so that epmd doesn't complain if two foo_servers are running on the same server
  set erl_opts: "-sname foo_server_sandbox"
  set cookie: :"<snip>"
end
#...
```

**Comment by minhajuddin** [comment]
I may have jumped the gun with the above workaround. I am not able to stop the currently running app using the above strategy. Not sure what the problem is. Would love to hear your input @bitwalker

**Comment by GalaxyGorilla** [comment]
I ran into the same issue today. I wanted to generate two releases with different config files. When you chose a release configuration name other than the application name then the application plus dependencies are not started.

**Comment by bitwalker** [comment]
@minhajuddin @GalaxyGorilla The solution here is to provide this configuration via `vm.args`. You can provide your own by setting the path to load your own vm.args with `set vm_args: "path/to/vm.args"` under an environment or release definition. In short it would look something like this:

## rel/vm.args.staging
```
-sname foo_server_staging
-cookie <snip>
```

## rel/vm.args.sandbox
```
-sname foo_server_sandbox
-cookie <snip>
```

## rel/config.exs

```elixir
...

environment :staging do
  set vm_args: "vm.args.staging"
  ...
end
environment :sandbox do
  set vm_args: "vm.args.sandbox"
  ...
end

...
```

**Comment by GalaxyGorilla** [comment]
@bitwalker many thanks for this detailed description :) I think we could solve our problems with this.

However, I think the real problem stays the same: It is not possible to use `release` configurations (besides the one with the app name). I did some tracing today and found myself back in the configuration parser (the assembler looks ok) but I ran out of time. Tomorrow I will work on it further.

**Comment by bitwalker** [comment]
You use Mix environments to generate configs conditionally, i.e. `MIX_ENV=staging mix release`. If you create a release that does not have the same name as your application, then you need to provide an applications list in the release definition, e.g.:

```elixir
release :myrelease do
  set applications: [:myapp]
end
```

Distillery infers the applications to include in the release by either loading the applications list of the application which shares the name of the release (the default configuration), or by loading the applications list of each of the applications defined in the list in the release definition. So in the above case, all applications required by `:myapp` will be included in the release. Without that, it will attempt to find an application named `:myrelease`, and if it finds no such application, it will effectively be an empty release (it will only contain `:elixir`, `:kernel`, `:stdlib`, and `:compiler`).

**Comment by GalaxyGorilla** [comment]
Ah thanks for the hint! I was definitely not aware of the relation between the release definition name and the application name. I will try this tomorrow!

**Comment by minhajuddin** [comment]
Thanks for the response @bitwalker 

I tried your suggestion by creating a `vm.args.staging` file, I was able to start the app properly but once it was started, I wasn't able to ping or stop it. Changing the vm.args to use `-name foo_server_staging@127.0.0.1` did the trick. Not sure why it isn't working with just the `-sname`. One thing that I did note was calling `DEBUG_BOOT=true bin/foo_server` showed that it was using an `-sname` of `foo_server_staging@fooserver` where `fooserver` is the `hostname` of the server.

For future googlers, here is my config

### rel/config.exs
```elixir
use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env

# ...

environment :staging do
  set include_erts: true
  set include_src: false
  set vm_args: Path.join(Path.expand(__DIR__), "./rel/vm.args.staging")
  set cookie: :"..."
end

# ...

release :foo_server do
  set version: current_version(:foo_server)
end
```
### rel/vm.args.staging
```
-name foo_server_staging@127.0.0.1

## Cookie for distributed erlang
-setcookie C(%ZG@9bc!v*^9uh/bwhHR,RgP3p<P&Y)9:{--k{M,JUi6|b&PsUbEnn.l<~~C33

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart

## Enable kernel poll and a few async threads
##+K true
##+A 5

## Increase number of concurrent ports/sockets
##-env ERL_MAX_PORTS 4096

## Tweak GC to run more often
##-env ERL_FULLSWEEP_AFTER 10

# Enable SMP automatically based on availability
-smp auto
```

**Comment by phtrivier** [comment]
Has this been fixed in any version of distillery later than 1.4 ?

**Comment by bitwalker** [comment]
@phtrivier There wasn't something to be fixed - it is documented that if the release name does not match the application named, or if you are building a release for an umbrella project, that you must set the applications which are part of that release in `rel/config.exs` as described above. This same restriction exists in all versions of Distillery.

If I'm misunderstanding what you mean, it's probably due to this issue having a couple different topics mixed together, so it would help if you are specific as to which issue you intended to ask about.

**Comment by x-ji** [comment]
I just ended up directly modifying `vm.args` but I wanted to figure out in the line

`-name <%= release_name %>@127.0.0.1` 

Where does `release_name` come from in the first place. Wouldn't changing that be a more fundamental solution than changing only `vm.args`?
