### ISSUE TITLE
Shutting down Distillery-based program under systemd/docker terminates abruptly instead of waiting for cleanup to complete.

### ISSUE THREAD

**Issue by petrikero** [bitwalker/distillery#165]
I created a docker image with Distillery and edib, which is run as a systemd service. When shutting down the systemd service, the Elixir program is terminated abruptly instead of waiting for it to clean up properly.

Root cause for this seems to be in the signal handler in boot_loader.eex, _cleanup() copy-pasted below. The RPC to :init.stop() returns immediately, which in combination with the usage of 'exec' causes systemd to think that the service has actually terminated immediately after :init.stop() returns, and then kills the actual Elixir process without letting it clean up.

Would it make sense to make _cleanup() wait until the program has terminated? Or if the current behavior is desired, is there a way to cleanly work around this issue, maybe by allowing the overriding of the boot_loader.eex with a custom one.

_cleanup() {
    echo "Shutting down node cleanly.."
    exec "$RELEASES_DIR/$REL_VSN/$REL_NAME.sh" rpc init stop
}

Below is a log of how the shutdown progresses. Only two Elixir applications get terminated before the whole program is killed.

12:17:16.029123 systemd[1]: Stopping MyService...
12:17:16.057868 docker[29055]: Shutting down node cleanly..
12:17:16.587159 docker[29055]: [info] MyApplication1 terminated (reason=:shutdown)
12:17:16.594425 docker[29055]: ok
12:17:16.602780 docker[29055]: [info] MyApplication2 terminated
12:17:16.634731 systemd[1]: Stopped MyService.

**Comment by bitwalker** [comment]
I would prefer to ensure that the cleanup task blocks until the node has shut down completely, if you are interested in tackling that in the form of a PR, I'd be happy to merge it!

**Comment by petrikero** [comment]
I'd be happy to take a shot! I'll be traveling for the next ten days, so it won't happen immediately, though.

**Comment by bitwalker** [comment]
It's all good, I've gone ahead and fixed it :)
