### ISSUE TITLE
vm.args not passed into build vm.args

### ISSUE THREAD

**Issue by michelson** [bitwalker/distillery#169]
it seems that rel/vm.args are not generating vm.args on release

given an umbrella app I just set some options in rel/vm.args file.

```
-name notify_web@127.0.0.1
-setcookie notify_web
+P 13421772
```

but none of these options are passed into /_build/prod/rel/my_umbrella/releases/0.1.0/vm.args
is there a way to pass some advanced options like system limits +P from vm.args or from rel/config.exs?

best regards

**Comment by bitwalker** [comment]
You need to put `set vm_args: "rel/vm.args"` in `rel/config.exs` under the release or environment configuration in order for it to be used. If you are coming from exrm, I strongly recommend reviewing the docs, as there are several differences in how distillery works.

**Comment by michelson** [comment]
thanks! it works

**Comment by nelsonic** [comment]
getting the error:
```
cat: /releases/1.0.3+b0d5adc/vm.args: No such file or directory
```
when attempting to deploy using distillery & edeliver ...

@bitwalker do you have an _example_ `rel/config.exs` file including the `set vm_args: "rel/vm.args"` ?
trying to figure out _where_ to put it. (_please/thanks_!)

**Comment by bitwalker** [comment]
@nelsonic Sure, the following would be a simple case:

```elixir
# rel/config.exs
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :foo
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :foo
  set vm_args: "rel/vm.args.prod"
end

release :myapp do
  set version: current_version(:myapp)
  set applications: [
    :runtime_tools
  ]
end
```
