### ISSUE TITLE
About the use of the `prod` environment

### ISSUE THREAD

**Issue by GalaxyGorilla** [bitwalker/distillery#170]
This is really more a general question about distillery ... The documentation states that

```
IMPORTANT: When running mix release for deployment to production, you should set MIX_ENV=prod, to avoid pulling in dev dependencies, and to make sure the compiled BEAMs are optimized.
```

and so I asked myself what this special part with optimized BEAMs is about. What's the big difference to e.g. the dev environment here?

**Comment by bitwalker** [comment]
I probably could've phrased that better - but what I was referring to was protocol consolidation, although it's possible that now happens regardless of build environment (I think that's only true if `build_embedded: true`), at one point protocol consolidation was only done for `prod`. Running your app without consolidated protocols will be far slower than with consolidation.
