### ISSUE TITLE
Upgrade permissions problem was hard to diagnose

### ISSUE THREAD

**Issue by bryanstearns** [bitwalker/distillery#173]
There might not be anything distillery can do about this, but it stymied me for longer than I'd like to admit, and @bitwalker suggested I write it up...

### Steps to reproduce

With an existing deploy of version 0.0.0 running in `/app` as the `daemon` user, follow the instructions for deploying an upgrade, but run it as `root`: create a new version directory (eg `/app/releases/0.0.1`) and copy the distillery-built upgrade tarball to it, then execute `/app/bin/my_app upgrade 0.0.1`

(This was on Ubuntu 16.10, with Erlang/OTP 19 [erts-8.2] & Elixir 1.3.4)

### Description of issue

The upgrade will fail with this confusing output:

```
Release 0.0.1 not found, attempting to unpack releases/0.0.1/my_app.tar.gz
Installed versions:
* 0.0.0    permanent
Unpack failed: {enoent,"/app/run/releases/0.0.1/my_app.rel"}
```

It turns out that it can't find `my_app.rel` because it couldn't actually expand the tarball: though I invoked the `upgrade` operation as `root`, it does its work by connecting to the running node, which is running as the less-priviledged `daemon` user: `daemon` can't write the unpacked tarball to the directory that `root` created, but doesn't report a problem until it tries to read a file that it should've unpacked.

Like I said - I'm not sure `distillery` can fix this: I think the problem is really in Erlang's standard library: sasl's [release_handler.do_unpack_release/4](https://github.com/erlang/otp/blob/OTP_R16B03/lib/sasl/src/release_handler.erl#L831) isn't reporting the failure to extract until it tries to read one of the extracted files. I didn't dig further (into `erl_tar:extract/2`) to try to figure this out - once it occurred to me that this might be a permissions issue, I fixed the problem by `chown`-ing the version directory and tarball to `daemon` before invoking the `upgrade`.

At least people who Google the error message might find this issue :-)

(Thanks for `distillery` - it really does make things easier!)

**Comment by bitwalker** [comment]
I should add documentation about this, but you're right, I don't think we can fix this unfortunately - just make people aware that the node needs to be able to write to it's release directory.

**Comment by jgmchan** [comment]
Thank @bryanstearns for writing this up, I just ran into the same issue :)
