### ISSUE TITLE
Fails to run release in foreground

### ISSUE THREAD

**Issue by brainlid** [bitwalker/distillery#18]
I can successfully build a release, start it and use a Phoenix application on my computer. However, when I try to run the "foreground" script it fails. I'm wanting to run the script in a docker container, but for now everything is on my development machine while I try to just get it working. 

```bash
$ cd /home/mark/dev/connect/rel/connect/releases/0.0.1/

$ ./connect.sh foreground
Exec: /home/mark/dev/connect/rel/connect/erts-8.0/bin/erlexec -noshell -noinput +Bd -boot /home/mark/dev/connect/rel/connect/releases/0.0.1/connect -mode embedded -config /home/mark/dev/connect/rel/connect/releases/0.0.1/sys.config -boot_var ERTS_LIB_DIR /home/mark/dev/connect/rel/connect/erts-8.0/../lib -args_file /home/mark/dev/connect/rel/connect/releases/0.0.1/vm.args -env ERL_LIBS /home/mark/dev/connect/rel/connect/lib -pa /home/mark/dev/connect/rel/connect/lib/connect-0.0.1/consolidated -extra -- foreground
Root: /home/mark/dev/connect/rel/connect
trap: SIGUSR1: bad trap
```

As I said, the release is working, I can start it, interact with the application (Phoenix) and stop it. It fails when trying to run in foreground. I can't figure out why. Most of the guides for deploying an elixir release in a docker container recommend running it that way.

**Comment by brainlid** [comment]
This issue is fixed by PR in #19 (https://github.com/bitwalker/distillery/pull/19). I tested it and verified that it fixes the issue and runs "foreground" correctly.

Please review/apply his PR.

**Comment by shanesveller** [comment]
If you are running on a Debian derivative, this is likely because of the default behavior of replacing upstream `sh` with `dash`, which implements `trap` differently. In my environment (Docker using the official `elixir:1.3.1` image), I was able to correct this by reverting to the original `sh`:
```shell
echo 'dash dash/sh boolean false' | debconf-set-selections
dpkg-reconfigure -phigh dash
```

**Comment by brainlid** [comment]
Thanks, this worked for solving my problem.
