### ISSUE TITLE
Systemd script error "vm.args needs to have either -name or -sname parameter."

### ISSUE THREAD

**Issue by walkr** [bitwalker/distillery#186]
Hello,

I'm trying to setup a systemd script for a release on Ubuntu, but it fails when trying to start the service, with the following error:
`vm.args needs to have either -name or -sname parameter.`

This is my script file:

```shell
[Unit]
Description=Elixir Application

[Service]
User=webuser
Group=webuser
WorkingDirectory=/home/webuser/myapp
ExecStart=/home/webuser/myapp/bin/myapp start
ExecStop=/home/webuser/myapp/bin/myapp stop
Restart=on-failure
RestartSec=2
Environment=PORT=9090
Environment=LANG=en_US.UTF-8

[Install]
WantedBy=multi-user.target
```

Any thoughts?

Thank you much!

**Comment by walkr** [comment]
I found the problem. 
`RemainAfterExit=yes` must be set in the script.

Here's the final systemd script:

```ini
[Unit]
Description=Elixir Application

[Service]
Type=simple
User=webuser
Group=webuser
WorkingDirectory=/home/webuser/myapp
ExecStart=/home/webuser/myapp/bin/myapp start
ExecStop=/home/webuser/myapp/bin/myapp stop
Restart=on-failure
RemainAfterExit=yes
RestartSec=5
Environment=PORT=9090
Environment=LANG=en_US.UTF-8
SyslogIdentifier=myapp

[Install]
WantedBy=multi-user.target
```

**Comment by bitwalker** [comment]
Nice find, I'll find a place in the docs for this!

**Comment by walkr** [comment]
Thanks @bitwalker 

In that case, then you can also add a link to this article if you want or use bits from it to better explain in the documentation what's going on: http://mfeckie.github.io/Phoenix-In-Production-With-Systemd/

**Comment by bitwalker** [comment]
Definitely :)

**Comment by lessless** [comment]
That still bite me today despite having `RemainAfterExit=yes` already:

[Unit]
Description=...
Requires=docker-staging.service
After=docker-staging.service

[Service]
Type=simple
User=...
WorkingDirectory=/server/app
ExecStart=/server/app/bin/flowmail_web start
ExecStop=/server/app/bin/flowmail_web stop
Restart=on-failure
RemainAfterExit=yes
RestartSec=5
Environment=LANG=en_US.UTF-8
Environment=RUN_ERL_LOG_GENERATIONS=2
SyslogIdentifier=app

[Install]
WantedBy=multi-user.target

**Comment by lessless** [comment]
@walkr how did you come to conclusion that `RemainAfterExit=yes`  was the main reason? Did you experience deploy failure with that message again?

**Comment by walkr** [comment]
@lessless When I didn't have `RemainAfterExit=yes`, my app wouldn't start. Fore more details, see the linked article above.

Also, if you're deploying a Phoenix app, make sure you have `server: true` in your `prod.exs` defined for your `App.Endpoint`.


Here's the relevant section of my config for `prod.exs`:
```elixir

config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com", port: 80],
  server: true,
  version: Mix.Project.config[:version]
```

In addition, I don't see anywhere in your service configuration the definition for `PORT`, but that might be different based on your use case.

Hope that helps!

**Comment by lessless** [comment]
@walkr I see. Here we have different symptoms - application starts fine,.. at least once in 20 or so times.
Apparently, systemd script has a little to do with it.  I checked failed release's `vm.args`  and it has `name` option right at the first line

```
## Name of the node
-name app@127.0.0.1
```

**Comment by dantswain** [comment]
I'm having a similar problem and I'm not using systemd at all.  I have a cron job that makes an rpc call once an hour and it _sometimes_ fails with the same error.  The cron job looks like this:

```
0 * * * * /path/to/release/bin/ourapp rpc Some.Module some_function >> /data/log/ourapp/job.log 2>&1
```

and it occasionally errors out with

```
vm.args needs to have either -name or -sname parameter.
```

**Comment by lessless** [comment]
@dantswain do you have `name` set in config as well?

**Comment by dantswain** [comment]
@lessless Yep.  The job finishes successfully about 3/4 of the time?  Give or take.

**Comment by lessless** [comment]
@dantswain are you using edeliver for deployment? It very well might be the source of the bug

**Comment by dantswain** [comment]
@lessless Nope :/  Just doing `mix release` and then untarring the release in the deploy location.

My best guess is this has something to do with how long it takes to execute the job.  Ours is doing a relatively short database query synchronously and kicking off something asynchronous with the results.  So maybe it has to do with how long that database query takes to run?

**Comment by bitwalker** [comment]
@dantswain Could you add `DEBUG_BOOT=true` to the environment for that command and gist the output when it fails? That should tell us where this is happening.

**Comment by dantswain** [comment]
@bitwalker I have output now, but I need to sanitize it.  Strangely the error has changed to "node is not running" (the node is running and did not restart).

**Comment by dantswain** [comment]
@bitwalker https://gist.github.com/dantswain/4d0825e21fe19b480e93e1ebf78283d5

It includes a successful output above and below the failed output.  The encoding warnings are "normal" in that we always get those on that particular box.

**Comment by bitwalker** [comment]
The problem appears to be that `-name ourapp@127.0.0.1` is in the `vm.args` file multiple times, and the boot script isn't handling that well. I'm pushing a fix to master for that, could you give it a shot?

**Comment by dantswain** [comment]
Will do.  If you have time, can you explain why that would cause intermittent failures?

**Comment by bitwalker** [comment]
To be honest it's not clear to me at all how it's intermittent, and not just constantly broken, but there shouldn't be multiple entries in `vm.args` to begin with unless it's being externally modified, so something is writing to that file, and if so, that's the culprit.

**Comment by dantswain** [comment]
Hm.  This is the full vm.args from the release in `releases/1.1.3/vm.args`:

```
## Name of the node
-name ourapp@127.0.0.1

## Cookie for distributed erlang
-setcookie ourapp

## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart

## Enable kernel poll and a few async threads
##+K true
##+A 5

## Increase number of concurrent ports/sockets
##-env ERL_MAX_PORTS 4096

## Tweak GC to run more often
##-env ERL_FULLSWEEP_AFTER 10

# Enable SMP automatically based on availability
-smp auto

## Protect the shell from accidental closure
+Bi
```

That's all from the `rel/vm.args` file in our repo.

**Comment by bitwalker** [comment]
Yeah that's basically the same as the auto-generated one provided by Distillery, I pushed that fix to master btw if you want to give it a shot and see if it addresses the original problem - tracking down what's modifying the `vm.args` file will probably require `strace` though :(

**Comment by dantswain** [comment]
Just to confirm - this commit? f162cb1df189b7f83d9c8bb10c67a795bc5218b4

I've got a PR in for it on our side.  Should be able to have that out either this evening or tomorrow morning.

So you think something is modifying vm.args on-the-fly when the command is being run?  I might be able to run strace, but it's gonna be tricky since the command seems to always succeed if I run it manually :/

**Comment by bitwalker** [comment]
@dantswain Yep that's the one.

I'm suspicious of that, but I can't say for sure. One thing to do would be to check *which* `vm.args` is being read, i.e., Distillery's boot script generates one to `$RELEASE_MUTABLE_DIR/vm.args`, which by default is `<deploy root>/var/vm.args`. Perhaps something is causing the generated `vm.args` to be appended to periodically, which causes the failure, but then subsequent runs are able to overwrite it as expected. Again, I'm speculating because I don't have access to the system, but these are things which I would be looking at to determine what exactly is going on. Under normal conditions, this shouldn't be possible, so something is gumming up the works here.

**Comment by dantswain** [comment]
@bitwalker Could it be multiple rpc calls at the same time?  I think that _is_ possible in our current situation - i.e., we have two different cron jobs and occasionally they line up.

**Comment by dantswain** [comment]
Actually, looking at the timing of the failures, I'd say it seems likely that this is due to two cron jobs lining up.  I might be able to solve my problem by shifting one of the jobs, but I'm also glad to keep debugging if that would help you.

**Comment by bitwalker** [comment]
That definitely sounds like the culprit, which version of Distillery are you on?

**Comment by dantswain** [comment]
@bitwalker Yup that was it.  I shifted one of the cron jobs by 1 minute and haven't had a failure since.  It's using Distillery 1.2.2, Elixir 1.4.2, Erlang R19.

**Comment by lessless** [comment]
@dantswain  good job!

**Comment by bitwalker** [comment]
@dantswain I wonder if you'd hit the same issue with 1.3.5. I suspect this was happening because of how `vm.args` was being dealt with previously (it would always write it). That said, it's good to know that was the issue!

**Comment by dantswain** [comment]
@bitwalker I'll update to 1.3.5 and report back.  It may take a couple days just b/c I was able to get the immediate problem under control and there's lots going on.

**Comment by balena** [comment]
Hey guys, I've been looking to this case for some time, and looks like you've been using the wrong `Unit` service type. Instead of `Type=simple` + `RemainAfterExit=yes`, if you use the distillery script arguments `start|stop`, then seems to me that the "more appropriate" approach, according to the [docs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html), is to use `Type=forking`. Yes, there are other [implications](https://www.lucas-nussbaum.net/blog/?p=877), thought.

Anyway, here is a configuration example:

```
[Unit]
Description=Elixir Application

[Service]
Type=forking
...
ExecStart=/path/to/myapp/bin/myapp start
ExecStop=/path/to/myapp/bin/myapp stop
...

[Install]
WantedBy=multi-user.target
```

If you use the distillery script argument `foreground`, then you can use `Type=simple` and you hasn't use `RemainAfterExit=yes`. This way:

```
[Unit]
Description=Elixir Application

[Service]
Type=simple
...
ExecStart=/path/to/myapp/bin/myapp foreground
#ExecStop=/path/to/myapp/bin/myapp stop  # XXX: will not work
...

[Install]
WantedBy=multi-user.target
```

You should [read this](https://elixirforum.com/t/distillery-node-is-not-running-and-non-zero-exit-code/3834) in order to figure out how to stop the service gracefully in this case (do not use `myapp stop`).

**Comment by lessless** [comment]
Just want to let know that this error doesn't appear for us anymore since we updated to 1.3.5
