### ISSUE TITLE
Please rerun with RELEASE_VERSION=x environment variable set.

### ISSUE THREAD

**Issue by GildedHonour** [bitwalker/distillery#193]
When deploying with edeliver, this error occurs.

	Detected several releases:
	 A
	 remote
	 command
	 failed
	 on:
	 my_user@11.22.33.44
	 Output
	 of
	 the
	 command
	 is
	 shown
	 above
	 if
	 the
	basename: unrecognized option '--verbose'
	Try 'basename --help' for more information.
	 
	 option
	 was
	 used
	 and
	 the
	 commands
	 executed
	 on
	 that
	 remote
	 host
	 are
	 printed
	 below
	 for
	 debugging
	 purposes:
	 FAILED
	 with
	 exit
	 status
	 2:
	 ssh
	basename: invalid option -- 'o'
	Try 'basename --help' for more information.
	 
	 ConnectTimeout=3
	 my_user@11.22.33.44
	 ls
	basename: invalid option -- 'A'
	Try 'basename --help' for more information.
	 
	 *
	Please rerun with RELEASE_VERSION=x environment variable set.

Nothing suggested by the author of edeliver has helped me so far. See this https://github.com/boldpoker/edeliver/issues/191

**Comment by bitwalker** [comment]
As best I can tell this is an issue with edeliver - I don't see anything in the error you pasted which is Distillery related. Sorry I can't be of more help :(
