### ISSUE TITLE
Auto yes option

### ISSUE THREAD

**Issue by nhjk** [bitwalker/distillery#195]
It might be helpful if when running mix release there was an option (-y) to automatically answer yes to things such as installing hex and rebar.

The use case I have in mind is using docker to build linux releases on macOS. I use the following one liner:

```sh
docker run \
  --rm \
  -v `pwd`:/build \
  -w=/build \
  -e MIX_ENV=prod \
  --env-file ./env.secrets \
  -it elixir:1.4 mix release --verbose --env=prod
```

There are a number of easy workarounds, but this with an added -y (or --auto-yes, etc) seems like a clean way to do linux releases on other os's.

**Comment by bitwalker** [comment]
There already is for the two examples you mentioned, installing hex/rebar, by using `--force`. Distillery also provides flags to do so where necessary, did you have a specific case where that wasn't true?
