### ISSUE TITLE
Failed to build upgrade after removing dependency

### ISSUE THREAD

**Issue by arnodirlam** [bitwalker/distillery#198]
### Steps to reproduce

- Build a release (or upgrade) with dependency X (here: confex)
- Remove the dependency
- git commit
- `mix edeliver upgrade production --branch=master --verbose --skip-mix-clean`

### Verbose Logs

```
==> Upgrading vira from 0.0.1+60-ac15ce1 to 0.0.1+64-e0bb936
==> Generated overlay vars:
    release_name=:vira
    release_version="0.0.1+64-e0bb936"
    is_upgrade=true
    upgrade_from="0.0.1+60-ac15ce1"
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.1"
    output_dir="rel/vira"
==> Copying applications to rel/vira
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.1 from /usr/lib/erlang/erts-8.1
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Generating relup for vira
==> vira requires an appup, but it wasn't provided, one will be generated for you..
==> Generated .appup for vira 0.0.1+60-ac15ce1 -> 0.0.1+64-e0bb936
==> Failed to build release:
    
    confex: File not found: "confex.app"

A remote command failed on:

  root@api.askvira.com

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/edeliver/vira/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="vira" AUTO_VERSION="commit-count+git-revision+branch-unless-master" BRANCH="master" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version  --verbose,  release --verbose --env="prod" --name="vira" --upgrade --upfrom="0.0.1+60-ac15ce1"
    fi
  

ERROR: Build failed: exit code 1
```

### Description of issue
Build system is Ubuntu 16.04, Elixir v1.4.0

```
Erlang/OTP 19 [erts-8.1] [source-e7be63d] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
```

#### config

comments and cookies removed.

```
use Mix.Releases.Config,
    default_release: :default,
    default_environment: :dev

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"XXX"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"XXX"

  name = "vira"
  output_dir = Path.relative_to_cwd(Path.join(["rel", "#{name}"]))
  IO.puts "Distillery output_dir: #{output_dir}"
  set output_dir: output_dir
end

release :vira do
  set version: current_version(:vira)
end
```

**Comment by bitwalker** [comment]
I'll take a look at this tomorrow.

**Comment by bitwalker** [comment]
After looking at this briefly, I'm not sure if this is a bug per se, but I need to validate something: The code is failing when asking `systools` to make a relup, but the only way `confex` could be causing this to fail is if it's in the applications list, even though it's been removed from your dependencies. Could you verify if that's the case? If so, I'll make a task to verify those things before building the relup, so we can produce a better error (this would cause the release to fail at runtime, so it's not a warning type situation).

**Comment by arnodirlam** [comment]
Thanks for looking into this that quickly.
In fact, we're using the automatic application detection introduced in Elixir 1.4, so we have no explicit application list any more:
```
  def application do
    [mod: {Vira, []},
     extra_applications: [:logger]]
  end
```

I've searched the whole code base for `confex` and it doesn't appear anywhere.

**Comment by bitwalker** [comment]
Is it in `mix.lock` by any chance? There could be an issue with the new application inference - I haven't yet updated distillery to make sure it behaves nicely with both pre-1.4 and post-1.4

**Comment by arnodirlam** [comment]
I've removed `confex`from `mix.lock` using `mix deps.clean --unused --unlock`, and confirmed its removal before committing the change. Also, all tests run fine.
I can privately provide you the release file it tries to build the update from, or more parts of our code, if that helps.

**Comment by bitwalker** [comment]
@arnodirlam I would try the explicit application list approach - if that fixes it, then I'll focus on making sure Distillery works well with the new application inference - a lot of the code for it already exists actually, as I had originally written Distillery to do just that, but I removed it because it wasn't how Elixir itself worked and so surprised people.

**Comment by arnodirlam** [comment]
I've added the applications, but the error still is the same :(
```
  def application do
    [mod: {Vira, []},
     applications: [:cors_plug, :joken, :phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger,
                    :logger_file_backend, :gettext, :phoenix_ecto, :mariaex, :edeliver, :ja_serializer]]
  end
```

**Comment by bitwalker** [comment]
Can you try and build a release and upgrade with just distillery? I'd like to isolate the problem, but right now edeliver creates a significant obstacle to reducing this down. You should be able to just run `mix release --env=prod --verbose` with version 1 checked out, then `mix release --env=prod --upgrade --verbose` with version 2 checked out. The second command should fail if this is indeed a distillery issue.

**Comment by arnodirlam** [comment]
done. Unfortunately, the error still appears.

https://gist.github.com/arnodirlam/31a4ba74d10cb454157fdd337dac2e45

This was with the explicit application list still intact. I've upgraded some dependencies in the meantime, which seems to be handled fine.

**Comment by bitwalker** [comment]
Well it's good to have narrowed the scope a bit. Unfortunately at this point I need a way to reproduce this so I can fix it - it's not clear to me how it got to this state, but I'll see if I can try a few things. If there is a way you can reproduce this with my [example app](https://github.com/bitwalker/distillery-test), that would help a bunch. I would try to add some dependencies and then remove them in a subsequent upgrade - but I know I've tested that before with no issue, but perhaps something more recent has broken it.

**Comment by arnodirlam** [comment]
I was able to reproduce the error in the [example app](https://github.com/bitwalker/distillery-test) (with master branches of distillery and conform), by the following steps (my own steps are **bold**):

## Steps

- Clone it
- Prepare deployment directory e.g. `mkdir -p /tmp/test/releases/0.2.0`
- Fetch deps and build: `cd distillery-test && mix do deps.get, compile`
- Build release: `mix release --env=prod`
- Deploy release: `cp _build/dev/rel/test/releases/0.1.0/test.tar.gz /tmp/test/`
- Start release: `cd /tmp/test && tar -xf test.tar.gz && ./bin/test start`
- Verify with:
  - `./bin/test ping`
  - `./bin/test remote_console`
  - At prompt `GenServer.call(Test.Server, :ping)`, should return `:v1`
- **Remove `:timex` from deps and applications, bump the version to `0.2.0`**
- **`mix deps.clean --unused --unlock`**
- `mix release --env=prod --upgrade`

## Output

```
Compiling 5 files (.ex)
Generated test app
==> Assembling release..
==> Building release test:0.2.0 using environment prod
==> Including ERTS 8.2 from /usr/local/Cellar/erlang/19.2/lib/erlang/erts-8.2
==> Generated .appup for test 0.1.0 -> 0.2.0
==> Failed to build release:

    timex: File not found: "timex.app"

    tzdata: File not found: "tzdata.app"

    hackney: File not found: "hackney.app"

    idna: File not found: "idna.app"

    mimerl: File not found: "mimerl.app"

    certifi: File not found: "certifi.app"

    ssl_verify_fun: File not found: "ssl_verify_fun.app"

    metrics: File not found: "metrics.app"

    gettext: File not found: "gettext.app"

    combine: File not found: "combine.app"
```

**Comment by bitwalker** [comment]
@arnodirlam Perfect, I'll work on this today

**Comment by bitwalker** [comment]
I've pushed a fix for this and cut a new point release to get it out since this is a high priority fix. Thanks for your patience!

**Comment by arnodirlam** [comment]
Works with the demo and our project now! 🎉 You're welcome. Thank **you** for the fix and contributing so much to the community. I appreciate your work!😄
