### ISSUE TITLE
include_erts: false may not really be working?

### ISSUE THREAD

**Issue by felipesere** [bitwalker/distillery#20]
Currently I am using this config
```elixir
environment :dev do
  set dev_mode: false
  set include_erts: false
end
```

to create a release on my Mac that I then copy into a Docker container running Linux.
I was expecting `incude_erts: false` to simply not include any erts in my release and use whatever is installed on my container.

My release fails to boot because it can't find erts-8.0.2 in the container. 
This is correct, as I currently only have 8.0.1 in there.

This prompted me to look into where that comes from.
`start_erts.data` gets populated with Utils.erts_version which is defined at release time, which means it uses the version in my Mac and not the one in the container.
Adding the full path in `include_erts` made the release fail because it tried to pickup a path that obviously does not exist on my Mac.

There are probably a bunch of ways to "solve" this:
  1. defer the detection to runtime/boot time
  2. allow to specify the version in the config file
  3. allow to specify a path in the config file, without actually including it

I'd kinda prefer 1) but it could be brittle. 2 and 3 are pretty much the same but mean that I have know and understand all the environments where this will run.

**Comment by bitwalker** [comment]
@felipesere I pushed a tentative solution to this. It appears to work for me, but I'd like to hear from you before I push a release.

**Comment by felipesere** [comment]
I'll have a look at it tonight.
