### ISSUE TITLE
erl_opts not picked up from environment config

### ISSUE THREAD

**Issue by ulfurinn** [bitwalker/distillery#204]
`erl_opts` is documented (`Configuration.md`) as applicable to both environment and release profiles, but it only appears to be used when specified in the release. Putting it in the environment block seems to be ignored.

Having `erl_opts` in the release block, I get:

```
==> Generated overlay vars:
    release_name=:approval_collector
    release_version="0.0.1-dev8"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=false
    include_src=false
    include_system_libs=true
    erl_opts="+C multi_time_warp +K true"
    erts_vsn="8.2"
    output_dir="_build/dev/rel/approval_collector"
```

After moving it to the environment block, the `erl_opts` line disappears from the overlay vars and is not included in the generated shell script.

distillery 1.1.2, ex 1.4.1, erl 19.2

**Comment by bitwalker** [comment]
Thanks for the report! This is now fixed in master, should have a new release soon.
