### ISSUE TITLE
dev_mode: true not symlinking ebin or priv folders

### ISSUE THREAD

**Issue by cjimison** [bitwalker/distillery#206]
### Steps to reproduce

I just upgraded to 1.1.2 and created a plan umbrella app that just starts itself up and dumped some random junk into the apps/<my_app>/priv folder.

then I ran:

 mix release --name=pg_app --env=dev --no-tar --verbose

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag.

==> Generated overlay vars:
    release_name=:pg_app
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=false
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.1"

### Description of issue

Not sure why the dev_mode is set to false here when I am setting it to true in my config.exs

use Mix.Releases.Config,
    default_release: :pg_app,
    default_environment: :dev

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :test
end
environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"#{:crypto.hash(:sha256, System.get_env("COOKIE"))}"
end

release :pg_app do
  set applications: [ :my_app]
end

**Comment by bitwalker** [comment]
This should be fixed in master, could you give it a shot and confirm?

**Comment by cjimison** [comment]
Confirmed.  Thanks!
