### ISSUE TITLE
Question:  Is there a way to get the --name value in the mix.exs and/or config file

### ISSUE THREAD

**Issue by cjimison** [bitwalker/distillery#207]
### Question:

Right now I use distillery to build 2 different releases with a different combination of apps

Hopefully this will help describe my setup

<root folder>\mix.exs
<root folder>\apps\module_a
<root folder>\apps\module_b
<root folder>\apps\module_c
<root folder>\config\config.exs
<root folder>\config\build_1.exs
<root folder>\config\build_2.exs
<root folder>\rel\config.exs

When I build a release I am using the following:

mix release --name=build_1 --env=dev

and 

mix release --name=build_2 --env=dev

in the rel/config.exs:

build_1 includes module_a and module_b
build_2 includes module_a and module_c

My question is in how can I dig out the --name value in my <root folder>/config/config.exs so I can include <root folder>/config/build_1.exs or <root folder>/config/build_2.exs  depending on the application I am actually building?

Thanks for any insights, and I am sorry if this is more of a mix question.   I am just not really sure where to get started.

-Chris

**Comment by cjimison** [comment]
Or should I be thinking about this the other way around?

Basically in the rel/config.exs set the "config" value for the build to "\config\build_1.exs" and have it include \config\config.exs first to bring in the common stuff first then define the app specific overrides.

**Comment by cjimison** [comment]
This work however when I build my modules I use macros to check the config values for some constant values that are not getting set because build_1.exs is not loaded until the release phase (not during the compile phase).  I do this so I can get a C++ like #define <value> that I can modify for each value.  So to modify my original question:

I there a way to get the --name value during the initial compile phase?

Thanks!

**Comment by cjimison** [comment]
OK.  I solved this for myself but I am commenting this encase someone else bumps into this issue in the future.  I solved this via environment variables.  Basically like so

APP_NAME=build_1 mix release --name=build_1 --env=dev
Then in my umbrella level mix.exs I pull this value out via:

```
def project do
  app = case Sys.get_env("APP_NAME") do
                 nil -> :build_1  # my default app
                 a   -> String.to_atom(a)
             end
  [ app: app
    config_path: "config/#{app}.exs"
    .. # other settings
  ]
```

You can then get this app name via `Mix.Project.config |> Keyword.get(:app)`

and in my rel/config.exs

```
environment :dev do
  set config: "config/#{Mix.Project.config |> Keyword.get(:app)}"
  # other settings
end
```

Not the most elegant solution but it works ...

**Comment by bitwalker** [comment]
Let me explain how I would set this up, and let me know if there a reason why it wouldn't work in your case.

For umbrellas I tend to define common configuration in `config/config.exs` and have it in turn import the configs of the apps in the umbrellas. This way you can mix and match any combination of applications in the release config, and the configuration for those apps will be available. Anything environment-specific I put in env-specific configs and import those where applicable. When building a release, all I generally have to do is specify `MIX_ENV`, and the rest flows from that.

If there is something about your setup which makes this not an option for you, I'd like to explore it further, as it may mean there is room for improvement in the current tooling.
