### ISSUE TITLE
Include Consolidated BEAM Files?

### ISSUE THREAD

**Issue by vishnevskiy** [bitwalker/distillery#21]
We just did a release and noticed the consolidated files were not included in the archive despite being copied to the release. I couldn't find any code that actually handles this and patched it so we can re-release. I am just wonder if we are doing something wrong or is there an oversight?

https://github.com/hammerandchisel/distillery/commit/fc4b92ce1dc9a03eac85bf49340b97ddd043d130

**Comment by bitwalker** [comment]
I could've sworn I did this, but sure enough, it's not there. Could you open a PR with your changes?

**Comment by bitwalker** [comment]
Closing this since #33 was merged.
