### ISSUE TITLE
:profile option for release task is broken in 1.2.0

### ISSUE THREAD

**Issue by Gringill** [bitwalker/distillery#212]
### Steps to reproduce

Attempt to create a release using the `:profile` option when using Distillery 1.2.0.

### Verbose Logs

```
$ MIX_ENV=prod mix release --verbose --profile=my_name:my_env
** (Mix) Could not invoke task "release": 1 error found!
--profile : Unknown option
```

### Description of issue

I would expect the release to be created using the given profile, as was the case prior to 1.2.0. Instead, since the `:strict` option is used here: https://github.com/bitwalker/distillery/blob/1.2.0/lib/distillery/tasks/release.ex#L151 , and `:profile` is not provided as an option, the aforementioned error occurs.

**Comment by bitwalker** [comment]
I'll get a fix released for this today.
