### ISSUE TITLE
:prod and :dev share the same release path

### ISSUE THREAD

**Issue by liketemple** [bitwalker/distillery#221]
I am new to distillery.
Since I tried mix release --env=dev I got this:
```
==> Assembling release..
==> Building release Elf:0.1.0 using environment dev
==> You have set dev_mode to true, skipping archival phase
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/dev/rel/Test/bin/Test console
      Foreground: _build/dev/rel/Test/bin/Test foreground
      Daemon: _build/dev/rel/Test/bin/Test start
```

however, I try mix release --env=prod I got:
```
==> Assembling release..
==> Building release Elf:0.1.0 using environment prod
==> Including ERTS 8.2 from /usr/local/Cellar/erlang/19.2/lib/erlang/erts-8.2
==> Packaging release..
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/dev/rel/Test/bin/Test console
      Foreground: _build/dev/rel/Test/bin/Test foreground
      Daemon: _build/dev/rel/Test/bin/Test start
```

The dev and prod env do not affect the release path, always _build/dev/, no _build/prod/, and there is an empty _build/prod directory

**Comment by bitwalker** [comment]
It works the same way Mix does, you should set MIX_ENV=prod to change the build environment. If your release and build environments match, set `default_release: Mix.env` in your `rel/config.exs`, and then you can omit `--env` and just set a MIX_ENV

**Comment by liketemple** [comment]
I try MIX_ENV=prod mix release then, works fine. Thanks a lot.

**Comment by nhooyr** [comment]
@bitwalker wouldn't `default_release: Mix.env` require a released named with one of the mix environments? E.g. a release named `:dev`. Isn't that different from what the `--env` flag does?

Setting `default_release: Mix.env` gives me

```
$ env MIX_ENV=prod mix release 
==> Assembling release..
==> Release failed, unable to load selected release
    - Make sure `rel/config.exs` has at least one release configured
    - Make sure at least one is set as default OR
    - Pass --name=<rel_name> to `mix release`
```

**Comment by nhooyr** [comment]
If you meant `default_environment: Mix.env()`, then that is already set. So just `MIX_ENV=prod mix release` should be fine with the default settings right?

The docs would need a update too then, because some specify `MIX_ENV=prod mix release --env=prod` when that is unnecessary. Should I create a separate issue for this?

**Comment by bitwalker** [comment]
@nhooyr `default_environment: Mix.env` is what I meant, thanks for spotting the typo! I added it after this issue as the default when a new config is generated, so there are probably still places which explicitly refer to the `--env` flag. If you want to open a PR which updates them to drop the flag (as long as `MIX_ENV` is set), I'll be glad to merge it!
