### ISSUE TITLE
init terminating in do_boot timeout

### ISSUE THREAD

**Issue by chenxsan** [bitwalker/distillery#232]
I'm  running my server code with a remote database, when running [`bin/app migrate`](https://hexdocs.pm/distillery/running-migrations.html#content) on my server, I would get many times error as below:

```
{"init terminating in do_boot",{timeout,{gen_server,call,[<0.103.0>,{checkout,#Ref<0.0.1.238>,true,infinity},5000]}}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
[root@li1580-247 phantom]# docker-compose exec app sh bin/app migrate
Loading app..
Starting dependencies..
Starting repos..
Running migrations for app
06:30:19.713 [info] == Running App.Repo.Migrations.CreateUser.change/0 forward
06:30:19.717 [info] create table users
06:30:19.723 [info] create index users_lower_email_index
06:30:19.729 [info] == Migrated in 0.0s
Running seed script..
Success!
[root@li1580-247 phantom]# docker-compose exec app sh bin/app migrate
Loading app..
Starting dependencies..
Starting repos..
Running migrations for app
{"init terminating in do_boot",{timeout,{gen_server,call,[<0.103.0>,{checkout,#Ref<0.0.1.238>,true,infinity},5000]}}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
```
Yes, sometimes it worked, but it's annoying since I don't know when it will works.

This is what I have in `prod.secret.exs`:

```
config :app, App.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "****",
  password: "*********",
  database: "app_prod",
  pool_size: 20,
  hostname: "remote.address",
  port: 5432,
  timeout: 35000
``` 
And I confirmed that I could connect to the remote database with `psql -h xxxx -U *** app_prod` command.

Any suggest? Thanks.

**Comment by Angarsk8** [comment]
Same here, I've been trying to run the migration task but it always fails with an error like that.

```
Loading todo_app..
Starting dependencies..

=INFO REPORT==== 26-Mar-2017::11:44:49 ===
    application: logger
    exited: stopped
    type: temporary
Starting repos..
Running migrations for todo_app
{"init terminating in do_boot",{{noproc,{'Elixir.GenServer',call,['Elixir.Postgrex.TypeManager',{get,'Elixir.Ect
o.Adapters.Postgres.TypeModule',{"localhost",5432,<<"todo_app_dev">>}},5000]}},{gen_server,call,[<0.103.0>,{chec
kout,#Ref<0.0.4.145>,true,infinity},5000]}}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```

**Comment by bitwalker** [comment]
This error is occurring because the migration is exceeding the timeout, you'll need to configure things such that this doesn't occur. This isn't a release-specific issue, or an issue with Distillery, so I'm going to close this.

**Comment by johannesE** [comment]
FYI: For other people I fixed the same issue with the infinity timeout. It was really my implementation (and the super slow server).

    File.stream!(Path.join(:code.priv_dir(:marinenotes), "/repo/country_port_list.csv"))
    |> CSV.decode!
    |> Task.async_stream(fn country -> Seeds.Helper.insert_country(country) end, timeout: :infinity)
    |> Stream.run()
