### ISSUE TITLE
module Mix is missing

### ISSUE THREAD

**Issue by zhaohansprt** [bitwalker/distillery#237]
centos7
Elixir 1.4.2
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

21:30:07.311 [info]  Application mr_t exited: exited in: MrT.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Mix.env/0 is undefined (**module Mix is not available**)

**Comment by bitwalker** [comment]
Mix is not included in releases, and cannot be because it is designed around Mix project structure. You should limit your use of `Mix.env` to compile-time invocations only.

**Comment by zhaohansprt** [comment]
got it
