### ISSUE TITLE
Error building on elixir 1.3.0/1.3.1

### ISSUE THREAD

**Issue by teamon** [bitwalker/distillery#243]
Please take a look at recent mix_docker build - https://travis-ci.org/Recruitee/mix_docker/builds/218606264

This commit bumps distillery version to 1.3.2 - https://github.com/Recruitee/mix_docker/commit/0ab178f2e64555e9106b094f83dafc5ffc8995e6#diff-7234367b857fd47fe1b5d1bcfd7e05edL1

The distillery compilation has failed for the following versions
```
Elixir: 1.3.0 OTP Release: 18.2.1
Elixir: 1.3.0 OTP Release: 19.0.2
Elixir: 1.3.1 OTP Release: 18.2.1
Elixir: 1.3.1 OTP Release: 19.0.2
```

The relevant log output:

```
==> distillery
Compiling 18 files (.ex)
== Compilation error on file lib/mix/lib/releases/archiver.ex ==
** (CompileError) lib/mix/lib/releases/archiver.ex:152: cannot invoke local when/2 inside match, called as: {:error, {name, reason}} when :erlang.is_list(name)
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

I've checked distillery's mix.exs and it has `elixir: "~> 1.3"`.

Any ideas?

**Comment by bitwalker** [comment]
Ah right, this is something that was added in 1.4, but thought was a 1.3 feature (as part of `with`). I'll refactor this code and push a new minor release.

**Comment by teamon** [comment]
Unfortunately, there is at least one more place :| - https://travis-ci.org/Recruitee/mix_docker/jobs/221633133
