### ISSUE TITLE
Can you pass a 'sname' or 'name' to 'foreground' ?

### ISSUE THREAD

**Issue by phtrivier** [bitwalker/distillery#244]
I have an application that is successfully released. 
I can run it with `_build/.../foo foreground`.

However, is it possible to pass an node name, to behave the same as:

    iex -sname foo@localhost -S mix run

I tried:

    _build/.../foo foreground -sname foo@localhost
    _build/.../foo foreground -name foo@localhost

But it does not seem to work.
Is it possible ?

**Comment by bitwalker** [comment]
You set this in the `vm.args` file, which by default should be in `<deploy dir>/releases/<ver>/vm.args`. You can set `RELEASE_CONFIG_DIR=/some/path` and then place your own `vm.args` file at `/some/path/vm.args`, if you want to control where that file lives.

**Comment by phtrivier** [comment]
Ok, it seems like the default vm.args uses a name like "foo@127.0.0.1". 

This may be unrelated, by I fail to connect to such a node using `Node.connect(String.to_atom("foo@localhost"))`

Should it work ? Is it a resolution issue on my side ?

**Comment by bitwalker** [comment]
If the name is set to `foo@127.0.0.1`, then you have to connect with that exact name, `foo@localhost` would be a different node.
