### ISSUE TITLE
Custom Commands stopped working somewhere after 1.2.2

### ISSUE THREAD

**Issue by dpehrson** [bitwalker/distillery#246]
### Steps to reproduce

1. Be using 1.2.2 with working custom commands
2. Upgrade to 1.3.3
3. Attempt to run `bin/app <custom-command>`

### Verbose Logs

No logs available at the moment

### Description of issue

Sometime after 1.2.2 attempting to run a custom command results in the same output as running `bin/app` with no arguments, it just displays the list of commands/help info

Downgrading back to 1.2.2 restores the functionality of the custom commands.

**Comment by dpehrson** [comment]
I apologize for not providing logs, this bug took down a staging system an hour before a production launch today.

If I can acquire more information I will provide updated information, but I wanted to make sure something was filed as I have spoken to other people that hit this same issue.

**Comment by jakub-zawislak** [comment]
Same for me. Just started to learn Distillery and stuck on custom command. My command is properly listed when I run `bin/app command`
```
MacBook-Pro:blog kuba$ bin/blog migrate
Usage: blog <task>

Service Control
=======================
start                          # start blog as a daemon

...

Custom Commands
=======================
/Users/kuba/htdocs/phoenix/blog/_build/PROD/rel/blog/releases/0.0.4/commands/migrate.sh
```
Tested on 1.3.2 and 1.3.3

**Comment by mmainz** [comment]
I can confirm this, too. Got this problem after upgrading from 1.3.1 to 1.3.3.

**Comment by bitwalker** [comment]
Looking into it ASAP

**Comment by bitwalker** [comment]
I'll be pushing a new release shortly, I've retired 1.3.2 and 1.3.3 on hex as well.

**Comment by bitwalker** [comment]
1.3.4 has been published with the fix for this
