### ISSUE TITLE
Is it possible to not run in distributed mode?

### ISSUE THREAD

**Issue by baldmountain** [bitwalker/distillery#247]
We have s few services running in docker containers. We'd like them to run independently (not distributed mode) They currently work OK, but we noticed that they start epmd, and if two instances start on the same slave their node names clash and one of the instances exits. We tried using vm.args with -start_epmd false and no sname or name but the release won't start because it insists that if we use vm.args, we have to specify either an sname or name.

**Comment by bitwalker** [comment]
No, as it's required for the control plane currently (i.e. bin/myapp remote_console), but you should just be able to set `-sname foo` and it will be impossible for the nodes to connect to each other (if they are in different containers). Even `-name foo@127.0.0.1` should cause no problems.

**Comment by michalmuskala** [comment]
Isn't that exactly what cookie is for? To keep different clusters on the same network from connecting to one another.

**Comment by bitwalker** [comment]
@michalmuskala Yeah that's another approach, though I feel `-sname` is better since it prevents them from being able to connect regardless of whether the cookie happens to be the same.

**Comment by teamon** [comment]
@baldmountain Not sure if this applies to your situation, but I have successfully managed to setup node name during docker container boot while keeping the mentioned control plane working - http://teamon.eu/2017/setting-up-elixir-cluster-using-docker-and-rancher/ (in my case I use rancher IP address, but you could use e.g. docker hostname)

**Comment by baldmountain** [comment]
We have a work around. Its bit complicated, but I'll walk through it.  We have a vm.args file like:

```
## Cookie for distributed erlang
-setcookie somelongstring

## Name of the node
-name ${TASK_REQUEST_ID}_${PORT0}@${TASK_HOST}

## Listening ports
-kernel inet_dist_listen_min ${PORT1} inet_dist_listen_max ${PORT1}

-smp auto
```

We expose 2 ports from the docker container. PORT0 is our listener and PORT1 is allocated to the Erlang VM. TASK_HOST and TASK_REQUEST_ID come from Singularity which manages our containers.

Our Dockerfile looks like:

```
FROM docker.repository.cc/app-elixir:1.4.1

ENV EX_APP_NAME=rorschach
ENV REPLACE_OS_VARS=true

# bring in the built files
ADD ./_build/rel/rorschach/bin /app/bin
ADD ./_build/rel/rorschach/lib /app/lib
ADD ./_build/rel/rorschach/releases /app/releases
```

And we inject the following environment variable: ERL_EPMD_PORT=5369 to get epmd to start on a specific port since it was starting in the middle of the range of exposed ports that docker is managing.

When we are running in production, or even on our dev servers, we are never going to connect to it with remote_console. We'd prefer to not open that second port, not specify a name or sname and not run in distributed mode. But the above seems to work. :)


geoff

**Comment by bitwalker** [comment]
I'm not sure I understand how you're running into the issue you are describing here, my understanding is:

- Unless you have a `EXPOSE` directive in your Dockerfile for a given port, there is no way to have "unexposed" ports conflict between containers; so it should be unnecessary to specify a port for both EPMD and Erlang's distribution (via the kernel config settings).
- You shouldn't need to expose your node at all if you don't want distribution, and in fact using `-sname literally_anything` would by definition prevent two nodes in different containers from even knowing each other exist, let alone connect

Did you try the above? What were you seeing?

And though you say you're never going to connect with `remote_console`, there will come a day when your logging/metrics don't give you enough insight into some transient production issue, and you'll need the remote shell to actually troubleshoot it ;)

**Comment by baldmountain** [comment]
We tried a lot of things. We saw epmd coming up in the range of ports that docker was managing causing conflicts with other containers. (We are running our containers in HOST mode.) If we only opened one port the VM would listen there and prevent our listener starting. We have to open two ports and specify to the VM which of the two ports to listen on or the VM will listen on the port that our frontend load balancer is trying to forward connections to. 

I guess what I'd prefer is to be able to skip this check: https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L371-L375 and just not supply a sname or name to the VM.

I prefer to not start epmd or for the VM to start in distributed mode. If at some time in the future we decide we want to connect to a system running in production we can supply a -name and redeploy. Using Singularity to manage docker containers means you can trade keeping a system running forever and using code updates for starting a new instance and once it's healthy stopping the old instance.

Having said all this, I guess we are OK with opening two ports.

**Comment by bitwalker** [comment]
There is probably a way to introduce a environment variable which allows you to bypass that check, but it would mean many of Distillery's features would be unavailable or degraded for you (hooks, custom commands, reload configuration, and remote consoles). I'll look into it.
