### ISSUE TITLE
With the mnesia database project, can you use distillery hot update?

### ISSUE THREAD

**Issue by dsl2014** [bitwalker/distillery#253]
### Steps to reproduce

Just a brief list of the steps required to produce the issue.

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag.

### Description of issue

- What are the expected results?
- What OS, Erlang/Elixir versions are you seeing this issue on?
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

**Comment by bitwalker** [comment]
Yes
