### ISSUE TITLE
Nifs not loaded

### ISSUE THREAD

**Issue by walkr** [bitwalker/distillery#261]
Hello,

I have a few nifs created using [rustler](https://github.com/hansihe/rustler), however the modules don't seem to be loaded when I start the app, as I get the error :

`supervisor: {local,kernel_sup}
    errorContext: start_error
    reason: {on_load_function_failed,'Elixir.Extra.GeoMath'}`

Any thoughts on how to deal with this?

Btw, my setup is the following:

1. I create the release on a build machine similar to production
2. I deploy the tar.gz to production servers

**Comment by bitwalker** [comment]
It doesn't appear to be failing to find the NIF, there seems to be some kind of error occurring in the `on_load` function of that module. Can you share what's in it? Unfortunately this isn't enough information for me to help very much :(

**Comment by walkr** [comment]
Here it is:

```elixir

# lib/extra/geomath.ex

defmodule Extra.GeoMath do
    use Rustler, otp_app: :extra, crate: :extra_geomath

    # When loading a NIF module, dummy clauses for all NIF function are required.
    # NIF dummies usually just error out when called when the NIF is not loaded, as that should never normally happen.
    
    def centroid(_point1, _point2), do: exit(:nif_not_loaded)

    @doc """
    Compute centroid of two geo points and return them as geopoint
    """
    def centroid(point, point, format: Geo.Point), do: {:ok, point}
    def centroid(%Geo.Point{coordinates: point1},
                 %Geo.Point{coordinates: point2}, format: Geo.Point) do
        case centroid(point1, point2) do
            {:ok, {long, lat}} -> {:ok, %Geo.Point{coordinates: {long, lat}}}
            error -> error
        end
    end
end
```

I apologize if the error is not related to distillery, but the app works fine when running locally (w/o release), it's after I create and run the release I encounter this problem. 

Also this extra app is a dependency of another app like so:

```shell
MyApp ├── Extra ├── Extra.GeoMath
      └── Other Apps
```

**Comment by bitwalker** [comment]
Looks to me like you're going to have to add an `IO.inspect` [here](https://github.com/hansihe/rustler/blob/master/rustler_mix/lib/rustler.ex#L77) in your local copy of rustler, build the release, then see what the output is when you try to run. I don't see anything that sticks out as a problem, but without knowing what the specific values are, it's just a guess.

Did you confirm that your release has stuff in `lib/extra-<ver>/priv/native/*`? I wonder if this is a case of some build tooling generating that stuff *after* the release is already packaged. I would confirm whether it's in `_build/<env>/lib/extra/priv/native/*` as well.

**Comment by walkr** [comment]
Yes, I can confirm the `*.so` file exists in both locations.

Based on various threads I've read online about similar situations, I've ended up creating the release directly on the production machine and now it works. 

So I think there's a mismatch between the build and production machines. I just couldn't figure out what.

Thank you for your assistance!
