### ISSUE TITLE
Extending sys.config

### ISSUE THREAD

**Issue by walkr** [bitwalker/distillery#267]
### Preamble 
I know the release artifact `sys.config`is being generated from `config/config.exs`.
In Erlang, the `sys.config` can contain references to other config files for the purpose of extending the former when the release is started.

For instance, we could have something like this:

```erlang
[{sasl,[{errlog_type,error}]}, "/etc/extra.config", "/etc/extra2.config"].
```

### Reference
----------------------
#### sys.config

[...]

> When traversing the contents of sys.config and a filename is encountered, its contents are read and merged with the result so far. When an application configuration tuple {Application, Env} is found, it is merged with the result so far. Merging means that new parameters are added and existing parameter values overwritten. 
----------------------
[source](http://erlang.org/doc/man/config.html)

### Question

With distillery, is there a way to specify these additional files?

I think this would come extremely handy when deploying to multiple machines, and each could store a local file with some specific configurations.

#### For example

`/etc/extra.config` @ host one

```erlang
[{kernel,
  [
    {sync_nodes_optional, ['two@host', 'three@host']},
    {sync_nodes_timeout, 30000}
  ]}
].
```

`/etc/extra.config` @ host two

```erlang
[{kernel,
  [
    {sync_nodes_optional, ['one@host', 'three@host']},
    {sync_nodes_timeout, 30000}
  ]}
].
```

Cheers!

**Comment by bitwalker** [comment]
It is not directly supported today, but we should be able to add release configuration options to support it, something like `included_configs: ["/etc/extra.config"]`.

**Comment by bitwalker** [comment]
This is already implemented in master
