### ISSUE TITLE
Revisit {:system, env} advice in the documentation

### ISSUE THREAD

**Issue by josevalim** [bitwalker/distillery#269]
Both Phoenix and Ecto are moving away from `{:system, env}` due to the inconsistencies it brings in terms of configuration. It only works for certain keys under certain applications and, even if we standardize the solution across the Elixir ecosystem, it would still be unsuitable  for configuring Erlang applications.

The misunderstanding came from an effort to make the application environment the ONLY place to hold configuration while it was designed mostly for in-memory application configuration. Both Phoenix v1.3 and Ecto v2.1 are pushing configuration to happen inside the `init` callback, which plays well with code upgrading and allows dynamic configuration to happen explicitly in the code. On `init`, developers can explicitly read from System.get_env, the filesystem, zookeeper, etc.

**Comment by bitwalker** [comment]
I'm generally +1 on this, I'll add it to my TODO
