### ISSUE TITLE
Console task hangs

### ISSUE THREAD

**Issue by areski** [bitwalker/distillery#271]
### Steps to reproduce

1) mix new hello_world --sup
2) add distillery deps in mix.exs `{:distillery, "~> 1.4"},`
3) MIX_ENV=dev mix deps.get
4) MIX_ENV=dev mix compile
5) MIX_ENV=dev mix release.init
6) MIX_ENV=dev mix release --verbose
7)  _build/dev/rel/hello_world/bin/hello_world console

Using `console` return the following and freeze:

    _build/dev/rel/hello_world/bin/hello_world console
    Erlang/OTP 19 [erts-8.0.2] [source-753b9b9] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

I can exit with Ctrl-C.

I can also ping it:

    _build/dev/rel/hello_world/bin/hello_world ping
    pong

### Verbose Logs

```
MIX_ENV=dev mix release --verbose                 
==> Loading configuration..
==> Assembling release..
==> Building release hello_world:0.1.0 using environment dev
==> Discovered applications:
  distillery-1.4.0
    from: _build/dev/lib/distillery
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  logger-1.4.4
    from: /home/areski/.kiex/elixirs/elixir-1.4.4/lib/elixir/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  compiler-7.0.1
    from: /usr/lib/erlang/lib/compiler-7.0.1
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.4.4
    from: /home/areski/.kiex/elixirs/elixir-1.4.4/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.0.1
    from: /usr/lib/erlang/lib/stdlib-3.0.1
    applications:
      :kernel
    includes: none

  kernel-5.0.1
    from: /usr/lib/erlang/lib/kernel-5.0.1
    applications: none
    includes: none

  hello_world-0.1.0
    from: _build/dev/lib/hello_world
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :distillery
    includes: none

  iex-1.4.4
    from: /home/areski/.kiex/elixirs/elixir-1.4.4/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0
    from: /usr/lib/erlang/lib/sasl-3.0
    applications:
      :kernel
      :stdlib
    includes: none

  runtime_tools-1.10
    from: /usr/lib/erlang/lib/runtime_tools-1.10
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:hello_world
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=true
    include_erts=false
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="8.0.2"
    output_dir="_build/dev/rel/hello_world"
==> Copying applications to _build/dev/rel/hello_world
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.0/commands
==> You have set dev_mode to true, skipping archival phase
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/dev/rel/hello_world/bin/hello_world console
      Foreground: _build/dev/rel/hello_world/bin/hello_world foreground
      Daemon: _build/dev/rel/hello_world/bin/hello_world start
```

### Description of issue

- What are the expected results?
Get access to REPL.

- What OS, Erlang/Elixir versions are you seeing this issue on?
I have tried with 1.4.4 & 1.4.2

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

I haven't touched rel/config.exs but here a copy::

    # Import all plugins from `rel/plugins`
    # They can then be used by adding `plugin MyPlugin` to
    # either an environment, or release definition, where
    # `MyPlugin` is the name of the plugin module.
    Path.join(["rel", "plugins", "*.exs"])
    |> Path.wildcard()
    |> Enum.map(&Code.eval_file(&1))
    use Mix.Releases.Config,
        # This sets the default release built by `mix release`
        default_release: :default,
        # This sets the default environment used by `mix release`
        default_environment: Mix.env()

    # For a full list of config options for both releases
    # and environments, visit https://hexdocs.pm/distillery/configuration.html
    # You may define one or more environments in this file,
    # an environment's settings will override those of a release
    # when building in that environment, this combination of release
    # and environment configuration is called a profile
    environment :dev do
      set dev_mode: true
      set include_erts: false
      set cookie: :"GH&[N7xIc@LZ@>92]yP.R?j3HhRu|`83vK/IO_.lv38|R;~{Wo:AD!DKJ;jeEFjG"
    end
    environment :prod do
      set include_erts: true
      set include_src: false
      set cookie: :"*2ebbLTV>>1W)MD(/d|U|PZ@yU1kudb?%wy]7|Nq~1=M^E~G|!UGkaZwNp,IOW`Y"
    end
    # You may define one or more releases in this file.
    # If you have not set a default release, or selected one
    # when running `mix release`, the first release in the file
    # will be used by default
    release :hello_world do
      set version: current_version(:hello_world)
      set applications: [
        :runtime_tools
      ]
    end

**Comment by bitwalker** [comment]
I'm not able to reproduce, what version of Erlang are you running?

**Comment by areski** [comment]
I'm using version 19.0.3

**Comment by bitwalker** [comment]
@areski since you are already on 19, are you able to upgrade to 19.3? I'll see if I can reproduce with 19.0.3 locally. Can you also let me know what OS this is on? Debian/Ubuntu? Some other distro?

**Comment by areski** [comment]
@bitwalker I'm on Ubuntu 15.10, I will try to test with 19.3 and report back

**Comment by bitwalker** [comment]
Can't repro with 19.0 on OSX, going to try Ubuntu 15.10 next if I can find a Docker image for it.

**Comment by jeremyowensboggs** [comment]
I can repo on my OSX box.  Followed the steps above and I have the same result
```
jowens ~/d/hello_world> _build/dev/rel/hello_world/bin/hello_world console
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

```
No console output beyond that, and no commands (except for Ctl-C) acknowledged.

**Comment by areski** [comment]
Sorry for the delay to reply, it's working now that I upgraded Erlang 19.3
@jeremyowensboggs can you check your erlang version?

**Comment by jeremyowensboggs** [comment]
$ which erl
/usr/local/bin/erl
$ ls -l /usr/local/bin/erl
lrwxr-xr-x  1 jowens  admin  29 Apr 10 15:26 /usr/local/bin/erl -> ../Cellar/erlang/19.3/bin/erl

**Comment by bitwalker** [comment]
@jeremyowensboggs can you run `rm -rf _build && mix do compile, release` then try to the `console` task again? I still can't reproduce, so there is some other factor here.

**Comment by jeremyowensboggs** [comment]
I just got it working.  The change is that I installed asdf, and then the plugins for erlang 19.3 and elixir 1.4.4.
Previously, I had just had elixir and erlang installed via homebrew.

**Comment by areski** [comment]
Thanks a lot for the help @bitwalker 
Closing, reopen if needed

**Comment by tchoutri** [comment]
Hi @bitwalker, I'd like to re-open this issue. I have this exact same issue where the IEx prompt *never* shows up, even though a plain `iex` works well.

if I try to `remsh` into the node from another node on the same machine, same problem, no IEx inside the release.
