### ISSUE TITLE
Hangs on start and foreground

### ISSUE THREAD

**Issue by eltiare** [bitwalker/distillery#276]
Everything works in my applications as expected when I'm running mix tasks and even the console with the deployed application, but every time I try to package it up and run the web server it just hangs with no output whatsoever. I've tried this in the following environments:

* Alpine Linux: Elixir 1.3.4, Erlang/OTP 19 [erts-8.1]
* Alpine Linux: Elixir 1.4.4, Erlang/OTP 19 [erts-8.3]
* OS X 10.11.6: Elixir 1.4.4, Erlang/OTP 18 [erts-7.3]
* OS X 10.11.6: Elixir 1.4.4, Erlang/OTP 19 [erts-8.3]
* OS X 10.11.6: Elixir 1.3.4, Erlang/OTP 18 [erts-7.3]
* OS X 10.11.6: Elixir 1.3.4, Erlang/OTP 19 [erts-8.3]

I've tried this in projects with and without ecto, to the same effect. To be clear `mix phx.server` and `_build/prod/rel/test/bin/test console` seem to work perfectly fine. For Alpine I'm using Docker to manage elixir/erlang version, for OS X I'm using asdf. I also used the latest brew versions of elixir and erlang.

### Steps to reproduce

1. Create new Phoenix project: `mix phx.new test --no-ecto`
2. Add distillery to mix.exs: `{:distillery, "~>1.4"}`
3. Run the gamut of setting up the app (`mix deps.get`, `yarn install`, `yarn deploy`, `mix phx.digest`)
4. Run `MIX_ENV=prod mix release` and then `_build/prod/rel/test/bin/test foreground`
5. Hang time (forever)! No output alerting to listening on a specific port as expected

### Verbose Logs

 # mix release --verbose
==> Loading configuration..
==> Assembling release..
==> Building release test:0.0.1 using environment prod
==> Discovered applications:
  phoenix_pubsub-1.0.1
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  phoenix_html-2.9.3
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  eex-1.3.4
    from: /usr/lib/elixir/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-3.1.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  mime-1.1.0
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  plug-1.3.5
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  phoenix-1.3.0-rc.2
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  logger-1.3.4
    from: /usr/lib/elixir/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  gettext-0.13.1
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  asn1-4.0.4
    from: /usr/lib/erlang/lib/asn1-4.0.4
    applications:
      :kernel
      :stdlib
    includes: none

  public_key-1.2
    from: /usr/lib/erlang/lib/public_key-1.2
    applications:
      :asn1
      :crypto
      :kernel
      :stdlib
    includes: none

  crypto-3.7.1
    from: /usr/lib/erlang/lib/crypto-3.7.1
    applications:
      :kernel
      :stdlib
    includes: none

  ssl-8.0.2
    from: /usr/lib/erlang/lib/ssl-8.0.2
    applications:
      :crypto
      :public_key
      :kernel
      :stdlib
    includes: none

  ranch-1.3.2
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  cowboy-1.1.2
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  compiler-7.0.2
    from: /usr/lib/erlang/lib/compiler-7.0.2
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.3.4
    from: /usr/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.1
    from: /usr/lib/erlang/lib/stdlib-3.1
    applications:
      :kernel
    includes: none

  kernel-5.1
    from: /usr/lib/erlang/lib/kernel-5.1
    applications: none
    includes: none

  test-0.0.1
    from: _build/prod/lib/test
    applications:
      :kernel
      :stdlib
      :elixir
    includes:
      :cowboy
     :gettext
     :phoenix
     :phoenix_html
     :phoenix_pubsub
  iex-1.3.4
    from: /usr/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.1
    from: /usr/lib/erlang/lib/sasl-3.0.1
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:test
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="8.1"
    output_dir="_build/prod/rel/test"
==> Copying applications to _build/prod/rel/test
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.1 from /usr/lib/erlang/erts-8.1
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.1/commands
==> Packaging release..
==> Archiving test-0.0.1
==> Writing tarball to _build/prod/rel/test/releases/0.0.1/test.tar.gz
==> Updating tarball
==> Tarball updated!
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/test/bin/test console
      Foreground: _build/prod/rel/test/bin/test foreground
      Daemon: _build/prod/rel/test/bin/test start

### rel/config.exs contents (without comments)

Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"Q=Db2]HP9dh.wKlXAXL7Bpk9PB9d*(tM^L=>iaPX8Q*JjCzs(<s,CEXv2^1a)*)/"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"$H.E`w<1=Ycb!t,LP^uC@C,9)r/W[ORnvEC9JwBD.![dHm{6ylra>{:K`s,rvuKX"
end

release :test do
  set version: current_version(:test)
  set applications: [
    :runtime_tools
  ]
end

**Comment by eltiare** [comment]
I just wiped out my brew install, reinstalled brew, reinstalled the required stuff for asdf, exported the openssl directives reinstalled the latest versions of erlang and elixir, and started over with a new project. I also fixed permissions on OS X for good measure. No dice, and I'm completely out of ideas. 😢

**Comment by michalmuskala** [comment]
Did you set `server: true` in your `Endpoint` config as advised in the guide?

**Comment by eltiare** [comment]
Crap, I had completely forgotten about that. I guess this library isn't just for Phoenix so it makes sense to have it as a side note. Well, hopefully some other hapless person comes across this and finds this quick answer to help them out. :)

**Comment by mxgrn** [comment]
Can we have a warning by distillery about this config missing?

**Comment by bitwalker** [comment]
I've considered that before, but I decided against it because I don't want a bunch of one-off exceptions in Distillery for detecting the various gotchas like this which can bite you. The documentation is pretty clear about this, and finding the solution even if you avoid the docs is pretty easy as Google links to any one of the previous instances of this being reported and resolved. 

I'm of the opinion that we have to expect a certain level of due diligence on the part of those consuming the tools and libraries - I don't expect that people using Distillery will read *all* of the documentation, but I do expect that if they are building a Phoenix project, that they read through the docs and at least pay attention to the warnings, or at least do so when they encounter a problem. If the documentation or tooling is making it difficult to understand what's wrong, that's one thing, we can definitely push to improve those things, but I don't think it's a good idea to define warnings for things which apply only to one specific type of project.

**Comment by mxgrn** [comment]
@bitwalker Your point is totally valid, thanks. Why I didn't read the docs was because I relied (too much) on edeliver.

**Comment by hectorip** [comment]
I need help with similar problem :'(, I have set server: true in my app, but although the app works perfectly in foreground and in console modes, when I start it as a daemon it works for a few seconds and then it turns very slow until it blocks (not responding to pings, commands as stop or any endpoint), I have to kill it by PID and restart it. I'm also using edeliver to deploy it on the server. 🙏 thanks in advance.

**Comment by bitwalker** [comment]
@hectorip That sounds like it may be an issue with the app itself - when run as a daemon, a release behaves the exact same as in console mode, and the only difference between foreground and daemon modes is that logging is to stdout in foreground rather than output to files, however the behavior you are describing doesn't sound like a side effect of excessive logging (and you'd see evidence of that in the files if it were). Are you getting a crash dump?
