### ISSUE TITLE
Run Release with option foreground on Windows does not work.

### ISSUE THREAD

**Issue by DrunkenDino** [bitwalker/distillery#280]
### Description of issue
I made a Phoenix application and made a release with distillery version 1.4.
My OS is Windows 7 64Bit. I am using Elixir 1.4 and Erlang/OTP release 19.

When I run my release with the option foreground, I get an errormessage that -noshell was not found.
I looked at the batch file in "\releases\{version}\{app}.bat" and managed to fix the problem.

### Solution
In the batch file "\releases\{version}\{app}.bat":
On line number 358 (the 5th line after :foreground) there has to be an empty string before the /B parameter:

```
:foreground
@call :pre_configure_hooks
@call :pre_start_hooks
@set EMU=beam
@set PROGNAME=%~n0
@start "" /B "%erl%" -noshell -noinput +Bd ^         :: <== this line
       -boot "%boot_script%" ^
       -boot_var ERTS_LIB_DIR "%erts_dir%\..\lib" ^
       -env ERL_LIBS "%release_root_dir%\lib%" ^
       -pa "%consolidated_dir%" ^
       -args_file "%vm_args%" ^
       -config "%sys_config%" ^
       %erl_opts% ^
       -extra %extra_opts%
@call :set_pid
@call :post_start_hooks
```

This is because the "start" command is somehow interpreting the first string as a title.
So it does work by providing an empty title before the actual program.

Also an underscore is missing right after the label ":console":

```
:console
@call :pre_configure_hooks
@call :pre_start_hooks         :: <== this line
@start "%rel_name% console" %werl% -boot "%boot_script%" ^
       -config "%sys_config%"  ^
       -args_file "%vm_args%" ^
       -user Elixir.IEx.CLI ^
       -extra --no-halt +iex
@goto :eof
```

**Comment by bitwalker** [comment]
Would you be willing to open a PR that I can merge? If you don't have time, just let me know and I'll fix it manually, but want to give you the opportunity to have credit for the change if possible :)

**Comment by DrunkenDino** [comment]
Ok I made a PR with the changes from above. :)

**Comment by bitwalker** [comment]
Great! I've merged the PR and it will go out in the next release.
