### ISSUE TITLE
Add support for new signal handler in OTP 20

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/distillery#284]
OTP 20 introduced a new signal handler. Distillery currently implements it's own handling of signals to gracefully shut down releases, but that is not desired when running with OTP 20+. 

Since Distillery's own signal handling is embedded fairly deeply in the boot script, we have two options on how to approach implementation of this:

1. We introduce conditional logic in the boot script to evaluate whether to use Distillery's signal handler or just pass signals through to the Erlang VM depending on the version of ERTS present
2. We copy the existing boot script and strip the signal handling from it, maintaining two versions of the boot script, choosing the one to include in the release based on the version of OTP the release is targeting.

There are some other considerations as well: I've been planning a clean up of the boot script which would break up the big monolithic script into smaller files for easier maintenance. This would likely mean that we could isolate the signal handling bits to one of those files and conditionally source it depending on the version of ERTS being used. However the current signal handling also requires decorating some of the tasks (namely `start` and `foreground`) with extra code to help implement it, and unless that can be factored out, we'd need to source the signal-handling enhanced version of that tasks script, or the one which just passes signals through - basically combining some parts of both 1 and 2 above. I'm not yet sure what the best approach is, but backwards compatibility is a requirement, so there isn't any "perfect" solution to it.

I'm open to suggestions or opinions on this. I plan to tackle it some time in the next few weeks now that OTP 20 is released.

**Comment by 12s12m** [comment]
Conditionally sourcing the code related to the new signal handlers based on the OTP version seems like the most friction less approach.

I have been looking at posts to do graceful restarts for cowboy's requests and making sure that the GenServers I have finish their current tasks before terminating. Do you have any links to where I can find the documentation for these. distillery is an indispensable tool for most Elixir devs, Thanks for creating it :)

**Comment by bitwalker** [comment]
@12s12m The documentation you'll want is around the `terminate/2` callback in `GenServer`. You can find those docs [here](https://hexdocs.pm/elixir/GenServer.html#c:terminate/2). The current Distillery signal handler will call `:init.stop/0`, which will gracefully shut down the server by terminating all applications - shut downs performed in this way *should* result in your `terminate/2` callbacks being executed, but there are some caveats there as mentioned in the documentation.

My refactor of the boot script is just about done - I've taken a slightly different approach than discussed above, by detecting the version of OTP early on, and wrapping the bits which do signal handling in conditional blocks - turns out that was cleaner than any other approach. Hoping to have that in place soon!

**Comment by bitwalker** [comment]
Support for the new signal handler in OTP 20 has been merged into master - I still need to test how it works in practice, but the primary obstacle - the custom trap handler in the boot script - is now conditionally used based on the version of ERTS being used to boot the release. Without the trap all signals should go directly to the beam process.
