### ISSUE TITLE
custom commands not working/hard to debug

### ISSUE THREAD

**Issue by spunkedy** [bitwalker/distillery#290]
### Steps to reproduce

I have an umbrella app that I am using distillery with. I am trying to follow the docs. https://hexdocs.pm/distillery/running-migrations.html#custom-command

I created the tasks file inside one of my sub applications. 

`tasks.ex`
```
defmodule MyApp.Release.Tasks do

  def migrate do
    IO.puts "Starting up migration"
    IO.puts "this should work"
  end
end
```

### Description of issue

When I run the command via `./bin/my_app comand MyApp.Release.Tasks migrate` it gives me:
```
root@ff6bdc30453e:/app# ./bin/MyApp command MyApp.Release.Tasks migrate
{"init terminating in do_boot",{undef,[{'MyApp.Release.Tasks',migrate,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
```

When I run it via `remote_console`
```
root@ff6bdc30453e:/app# ./bin/my_app remote_console
Erlang/OTP 19 [erts-8.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(my_app@127.0.0.1)1> MyApp.Release.Tasks.migrate
Starting up migration
this should work
:ok
iex(my_app@127.0.0.1)2>
```

I am building the release into a docker image and running it via another shell into the running job. 

Any ideas on how to debug this?

**Comment by bitwalker** [comment]
You need to name with module with the `Elixir.` prefix, so `Elixir.MyApp.Release.Tasks`. I plan to add some logic to check to see if the module name is capitalized but missing the `Elixir.` prefix, and if so adding it for you, but currently that is not the case.

**Comment by spunkedy** [comment]
Worked, thanks!
