### ISSUE TITLE
How to use `Plug.Conn.send_file` with distillery?

### ISSUE THREAD

**Issue by the-shank** [bitwalker/distillery#292]
### Steps to reproduce

- Create a new project with the following dependencies
  - cowboy
  - plug
  - distillery
- Create a folder `priv/static` to hold the static files and put an `index.html` file in there. 
- create a `Router` file using `Plug.Router`. For example the following are the contents of my `lib/test_send_file/router.ex`  
```elixir
defmodule TestSendFile.Router do
  use Plug.Router
  
  plug :match
  plug :dispatch
  
  get "/" do
    conn
    |> put_resp_content_type("text/html")
    |> send_file(200, "priv/static/index.html")
  end

  match _ do
    conn |> send_resp(404, "Not found !")
  end
end
```
- run the project using `iex -S mix` and navigate to `localhost:4000` in your browser. The `priv/static/index.html` html is loaded in the browser.
- create a release using distillery. `mix release`. Run the application using `_build/dev/rel/test_send_file/bin/test_send_file foreground` and navigate to `localhost:4000` in your browser. An internal server error occurs. **`** (File.Error) could not read file stats "priv/static/index.html": no such file or directory`** is outputted in the console.

### Description of issue

One of the following is happening:
- Distillery is packaging the contents of `priv/static/` folder and putting it somewhere else in the release.
- There is some configuration option that is required in order to tell distillery to treat a particular folder as the static assets folder and package it in the release, but I am unable to locate it.

**Comment by michalmuskala** [comment]
You should use `Application.app_dir(app_name, "priv/path/to/file")` to get a path at runtime. Other methods are not guaranteed to work after compilation.

**Comment by the-shank** [comment]
@michalmuskala thanks. I will close this one.
PS: I have been following your solutions on exercism 👍
