### ISSUE TITLE
sweet_xml dependency not included in release

### ISSUE THREAD

**Issue by jespr** [bitwalker/distillery#295]
### Steps to reproduce

I don't really have steps to reproduce, as it's part of a bigger app. But I have described my problem down in the `Description of issue` section

### Verbose Logs

When I run the release command, I run it with: 
`MIX_ENV=prod mix release --env=prod --verbose`

and the log is:

```
==> Loading configuration..
==> Assembling release..
==> Building release tabsandspaces:0.0.1500946658 using environment prod
==> Discovered applications:
  xmerl-1.3.12
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/xmerl-1.3.12
    applications:
      :kernel
      :stdlib
    includes: none

  sweet_xml-0.6.5
    from: _build/prod/lib/sweet_xml
    applications:
      :kernel
      :stdlib
      :elixir
      :xmerl
    includes: none

  httpoison-0.12.0
    from: _build/prod/lib/httpoison
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
    includes: none

  arc-0.8.0
    from: _build/prod/lib/arc
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :httpoison
    includes: none

  arc_ecto-0.7.0
    from: _build/prod/lib/arc_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :arc
    includes: none

  elixir_make-0.4.0
    from: _build/prod/lib/elixir_make
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  ex_aws-1.1.3
    from: _build/prod/lib/ex_aws
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  comeonin-3.2.0
    from: _build/prod/lib/comeonin
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
    includes: none

  noegle-0.1.0
    from: _build/prod/lib/noegle
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :comeonin
      :ecto
      :postgrex
      :plug
    includes: none

  earmark-1.2.2
    from: _build/prod/lib/earmark
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  timex_ecto-3.1.1
    from: _build/prod/lib/timex_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :timex
    includes: none

  combine-0.9.6
    from: _build/prod/lib/combine
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  metrics-1.0.1
    from: _build/prod/lib/metrics
    applications:
      :kernel
      :stdlib
    includes: none

  ssl_verify_fun-1.1.1
    from: _build/prod/lib/ssl_verify_fun
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  certifi-1.2.1
    from: _build/prod/lib/certifi
    applications:
      :kernel
      :stdlib
    includes: none

  mimerl-1.0.2
    from: _build/prod/lib/mimerl
    applications:
      :kernel
      :stdlib
    includes: none

  unicode_util_compat-0.2.0
    from: _build/prod/lib/unicode_util_compat
    applications:
      :kernel
      :stdlib
    includes: none

  idna-5.0.2
    from: _build/prod/lib/idna
    applications:
      :kernel
      :stdlib
      :unicode_util_compat
    includes: none

  hackney-1.8.6
    from: _build/prod/lib/hackney
    applications:
      :kernel
      :stdlib
      :crypto
      :asn1
      :public_key
      :ssl
      :idna
      :mimerl
      :certifi
      :ssl_verify_fun
      :metrics
    includes: none

  tzdata-0.5.12
    from: _build/prod/lib/tzdata
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
      :logger
    includes: none

  timex-3.1.24
    from: _build/prod/lib/timex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
      :gettext
      :combine
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  db_connection-1.1.2
    from: _build/prod/lib/db_connection
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :connection
    includes: none

  postgrex-0.13.3
    from: _build/prod/lib/postgrex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :db_connection
      :decimal
      :crypto
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      :kernel
      :stdlib
    includes: none

  decimal-1.4.0
    from: _build/prod/lib/decimal
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  ecto-2.1.4
    from: _build/prod/lib/ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :decimal
      :poolboy
    includes: none

  phoenix_ecto-3.2.3
    from: _build/prod/lib/phoenix_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :plug
    includes: none

  gettext-0.13.1
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  asn1-4.0.4
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/asn1-4.0.4
    applications:
      :kernel
      :stdlib
    includes: none

  public_key-1.3
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/public_key-1.3
    applications:
      :asn1
      :crypto
      :kernel
      :stdlib
    includes: none

  ssl-8.1
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/ssl-8.1
    applications:
      :crypto
      :public_key
      :kernel
      :stdlib
    includes: none

  ranch-1.3.2
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  cowboy-1.1.2
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  phoenix_html-2.10.2
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  phoenix_pubsub-1.0.2
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  eex-1.4.2
    from: /usr/local/Cellar/elixir/1.4.2/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-3.1.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  mime-1.1.0
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  logger-1.4.2
    from: /usr/local/Cellar/elixir/1.4.2/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  crypto-3.7.2
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/crypto-3.7.2
    applications:
      :kernel
      :stdlib
    includes: none

  plug-1.4.0
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  phoenix-1.2.4
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  compiler-7.0.3
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/compiler-7.0.3
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.4.2
    from: /usr/local/Cellar/elixir/1.4.2/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.2
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/stdlib-3.2
    applications:
      :kernel
    includes: none

  kernel-5.1.1
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/kernel-5.1.1
    applications: none
    includes: none

  tabsandspaces-0.0.1500946658
    from: _build/prod/lib/tabsandspaces
    applications:
      :kernel
      :stdlib
      :elixir
      :phoenix
      :phoenix_pubsub
      :phoenix_html
      :cowboy
      :logger
      :gettext
      :phoenix_ecto
      :postgrex
      :timex
      :timex_ecto
      :earmark
      :noegle
      :ex_aws
      :elixir_make
      :arc_ecto
      :hackney
      :poison
      :sweet_xml
    includes: none

  iex-1.4.2
    from: /usr/local/Cellar/elixir/1.4.2/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.2
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/sasl-3.0.2
    applications:
      :kernel
      :stdlib
    includes: none

  runtime_tools-1.11
    from: /usr/local/Cellar/erlang/19.2/lib/erlang/lib/runtime_tools-1.11
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:tabsandspaces
    release_version="0.0.1500946658"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="8.2"
    output_dir="_build/prod/rel/tabsandspaces"
==> Copying applications to _build/prod/rel/tabsandspaces
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.2 from /usr/local/Cellar/erlang/19.2/lib/erlang/erts-8.2
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.1500946658/commands
==> Packaging release..
==> Archiving tabsandspaces-0.0.1500946658
==> Writing tarball to _build/prod/rel/tabsandspaces/releases/0.0.1500946658/tabsandspaces.tar.gz
==> Updating tarball
==> Tarball updated!
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/tabsandspaces/bin/tabsandspaces console
      Foreground: _build/prod/rel/tabsandspaces/bin/tabsandspaces foreground
      Daemon: _build/prod/rel/tabsandspaces/bin/tabsandspaces start
```

### Description of issue

I'm using `ex_aws` with `arc` and `arc_ecto` which requires dependencies to be like so:
```
def deps do
...
      {:arc, "~> 0.8.0"},
      {:arc_ecto, "~> 0.7.0"},
      {:ex_aws, "~> 1.1"},
      {:hackney, "~> 1.6"},
      {:poison, "~> 3.1", override: true},
      {:sweet_xml, "~> 0.6"},
end
```

However when I build a release of my app, and I attempt to upload a file - I get an error:

```
18:40:31.554 [error] %ExAws.Error{message: "Missing XML parser. Please see docs"}
18:40:31.554 [error] Missing XML parser. Please see docs
```

It appears that `SweetXML` isn't loaded and thus `Code.ensure_loaded?(SweetXML)` returns false (https://github.com/CargoSense/ex_aws/blob/c9901326c0bab278e97ca340e137ae94521e397e/lib/ex_aws/sns/parsers.ex#L1).

I have added `:sweet_xml` to `applications` in `mix.exs` and in `rel/config.exs`

rel/config.exs:
```
release :tabsandspaces do
  set version: current_version(:tabsandspaces)
  set applications: [
    :runtime_tools,
    :sweet_xml,
  ]
end
```

Complete `rel/config.exs`:
```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"BBZ|4}Gi,?(/R}jxrXP%Pgqz)H|I]s`P[[mYk)p<4YyqRr._I}<IJv^H}ne}|<De"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"G{=YRG:{}t%[Ov[(DlEzC{3VWPah;(U[?B?v0x.~QqU:~ZWG?cpr(SPlg3YKs^o?"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :tabsandspaces do
  set version: current_version(:tabsandspaces)
  set applications: [
    :runtime_tools,
    sweet_xml: :load,
  ]
end
```

Elixir version gives:

```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

IEx 1.4.2
```

**Comment by bitwalker** [comment]
If you just add `:sweet_xml` to your applications list in `mix.exs` and remove it from `rel/config.exs` do you still see this error? If so, when you untar the release, do you see a `sweet_xml-<version>` folder under `<deploy_dir>/lib`? If so, could you gist the `yourapp.script` file from `<deploy_dir>/releases/<rel_version>/`?

**Comment by jespr** [comment]
Let me try that :)

**Comment by jespr** [comment]
Ok. `sweet_xml-version` is under `<deploy_dir>/lib` the gist for `tabsandspaces.gist` is here: https://gist.github.com/jespr/7b7f7f5ad38954242d38954a581d2589

If I locally run `_build/prod/rel/tabsandspaces/bin/tabsandspaces console` and then `Code.ensure_loaded?(SweetXML)` which is how ex_aws checks if SweetXML is there, it returns `false`

**Comment by bitwalker** [comment]
The module name is `SweetXml`, rather than `SweetXML` ;)

**Comment by jespr** [comment]
Haha.. :man_facepalming: what an incredible waste of your time. 

I still get the error `[error] %ExAws.Error{message: "Missing XML parser. Please see docs"}` in my deployed code. But when I run the console and `Code.ensure_loaded?(SweetXml)` it does indeed return true :) The error must be somewhere else.

Sorry about that, and thanks for your help :)

**Comment by jespr** [comment]
Gave me some good insight in to how to debug issues with releases, so that's at least something I guess :/ so sorry.

**Comment by bitwalker** [comment]
No worries! I don't mind being a bouncing board/second set of eyes, so don't sweat it :) I wonder if that same typo is coming from configuration and causing the error in ExAws - at least that's where I'd look first, other than that, I don't know enough about the libs to really say what might be causing the problem there - failing any other options, you may have to review the source code for the version you are using to see how that error is getting produced.

**Comment by jespr** [comment]
I double checked that, after you pointed out my mistake - it is in fact spelled correctly in there (SweetXml - https://github.com/CargoSense/ex_aws/blob/c9901326c0bab278e97ca340e137ae94521e397e/lib/ex_aws/sns/parsers.ex#L1). A good exercise for me to get to learn Elixir a bit more by trying to debug this, so that's great :)

**Comment by bitwalker** [comment]
I see the problem - that code is being executed at compile-time, not runtime (i.e. in the release). The error is only produced when the code compiles without that module being loaded, [as seen here](https://github.com/CargoSense/ex_aws/blob/3aab20d4c1561dcb6e177fabdfa4a39dbdefce3f/lib/ex_aws/s3/parsers.ex#L102). So my take is that perhaps you've got `:sweet_xml` in your deps with `only: [:dev]` or something like that, and when you compile the release with `MIX_ENV=prod`, it's not actually available, and gets compiled with the errors hardcoded.

**Comment by jespr** [comment]
Hrm.. My deps look like this:

```
  defp deps do
    [
      {:phoenix, "~> 1.2.1"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.6"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:noegle, github: "jespr/noegle"},
      {:earmark, "~> 1.2"},
      {:timex, "~> 3.0"},
      {:timex_ecto, "~> 3.0"},
      {:distillery, "~> 1.4"},
      {:cowboy, "~> 1.0"},
      {:arc, "~> 0.8.0"},
      {:ex_aws, "~> 1.1"},
      {:poison, "~> 2.0"},
      {:arc_ecto, "~> 0.7.0"},
      {:sweet_xml, "~> 0.6"},
     ]
  end
```

**Comment by bitwalker** [comment]
Hmmm - try running `MIX_ENV=prod mix do deps.clean sweet_xml ex_aws, deps.get, deps.compile sweet_xml ex_aws, mix release` and see if you still get that error. If a compile happened at some point when sweet_xml wasn't loaded and those beams were cached, it may have never rebuild them once sweet_xml *was* available and causing you issues. The above command will make sure it gets recompiled properly. If it's still not working, we can dig deeper.

**Comment by jespr** [comment]
That seemed to fix my release locally :) Now I just have to figure out how to replicate that on the server, but that shouldn't be hard - thank you so so much!

**Comment by bitwalker** [comment]
No problem! Glad I could help :)

**Comment by jespr** [comment]
@bitwalker I'm using Gatling to deploy my application by pushing to a git-repo on my server. I should be able to just ssh to my server and run the above command (deps.clean), and then execute the commands that are run when I push to my git-repo, right?

For some reason that doesn't seem to work :/

**Comment by bitwalker** [comment]
I would try running both deps.clean and deps.compile, using the order `sweet_xml ex_aws` for the arguments - I have a feeling that the deps are being compiled out of order, so compiling them in that specific order should work. As to why that's happening, do you know if ex_aws declares sweet_xml in its deps as optional? If not, it should.

**Comment by jespr** [comment]
Let me try that. It appears it does declare sweet_xml as optional (https://github.com/CargoSense/ex_aws/blob/master/mix.exs#L37)

**Comment by bitwalker** [comment]
Crazy long shot: change the order of your deps so that sweet_xml comes first - I don't think it will matter, and if it does it's probably a bug in Mix, but worth a shot!

**Comment by bitwalker** [comment]
Oh, one other thing, are you source controlling mix.lock and if so, is sweet_xml there?

**Comment by jespr** [comment]
Still no luck :( I've changed the order of deps so sweet_xml comes first - I've made sure the order in deps.clean and deps.compile is right. 

mix.lock is not source controlled right now. sweet_xml is present in both the repo one, and the one on the server as far as I can see though (https://gist.github.com/jespr/204ecd3df00a9420cba68e4dd21ae26a) - not sure if it makes a difference if it's source controlled or not?

Can I delete something in `_build` on the server? Or blow the whole dir away, does that make a difference?

**Comment by bitwalker** [comment]
For projects I would recommend always checking in `mix.lock` because it will ensure that deploys use the exact same version of a dep as in dev - that said, it's not strictly necessary, I just wondered if it was possible that something was going wrong there, but it doesn't seem to be the case.

I would try blowing away `_build` completely and retrying - if that doesn't solve it though, I'd be at a bit of a loss. My next step would likely be to make sure that the version of Elixir/Erlang you are running on the build server is the exact same as in dev (where the release works), and if they aren't, trying to synchronize those and retrying the `deps.clean sweet_xml ex_aws, deps.get, deps.compile sweet_xml ex_aws` procedure. If it's *still* not working, I would try to manually build the release on the server and see if you can get it to work, and if so, that tells you something Gatling is doing isn't working quite right, but if it doesn't, then something on the build server may need to be reset/tweaked (such as running `mix hex.local --force && mix rebar.local --force` to ensure that hex and rebar are using their latest versions for example).

Unfortunately beyond that I'm not sure what I'd do - probably hop on IRC and ping ericmj or josevalim to see if they have any suggestions (or perhaps posting on https://elixirforum.com in the Deployment section). Having another set of eyes other than the two of ours may bring some fresh ideas.

**Comment by jespr** [comment]
Just a quick update. Blowing away `_build` solved the issue :) However I'm not running in to `(UndefinedFunctionError) function :unicode_util.lowercase/1 is undefined (module :unicode_util is not available)` - but I've seen similar issues and are trying to resolve that. It doesn't seem like the hackney at 1.8.0 fix works for me - but I'll keep trying. Once again, thank you so much for your help here :)

**Comment by bitwalker** [comment]
Glad to hear that worked! The error I was seeing with that was that there were duplicated modules (`:unicode_util` is defined in OTP 20, so building a release with `unicode_util_compat` which also defines that module fails due to that) - yours seems to be slightly different, I think you need to add `unicode_util_compat` to your deps if you aren't on OTP 20 yet.

**Comment by jespr** [comment]
Maybe I should go back to Ruby.. :/ I ran in to another issue now - I must've been messing around with something in the releases directory or something.. Now when I deploy I get the following error: 

`$ service tabsandspaces upgrade 0.0.1501109182` results in:

```
remote: Release 0.0.1501109182 not found, attempting to unpack releases/0.0.1501109182/tabsandspaces.tar.gz
remote: Unpacked successfully: "0.0.1501109182"
remote: Release 0.0.1501109182 is already unpacked, now installing.
remote: ERROR: release_handler:check_install_release failed: {no_matching_relup,
remote:                                                       "0.0.1501109182",
remote:                                                       "0.0.1501036767"}
```

What's the easiest way to fix this? :/ How can I see what release is currently running?

**Comment by bitwalker** [comment]
Hang in there, we'll get you through this :)

Did you build the upgrade release with the `--upgrade` flag? That's usually the problem when this error comes up.

I'm not super familiar with gatling so I don't know if they expose that to you or not, it may be worth working directly with Distillery first, validate things work, then add in the tooling to automate the deployment, I'm more useful at the lower level :P

**Comment by jespr** [comment]
I decided to skip Gatling and just do it manually on the server.. So are you saying I should run it with or without the `--upgrade` flag? :)

I think I ran something like:
`mix release --upgrade --upfrom=0.0.1501111783 --warnings-as-errors --env=pro`

..and then I'm confused on what to do next? I ran: `service tabsandspaces upgrade 0.0.1501113000` - and that resulted in that error.

**Comment by jespr** [comment]
this was obviously with a new release, which resulted in this error:

```
remote: Release 0.0.1501113000 not found, attempting to unpack releases/0.0.1501113000/tabsandspaces.tar.gz
remote: Unpacked successfully: "0.0.1501113000"
remote: Release 0.0.1501113000 is already unpacked, now installing.
remote: ERROR: release_handler:check_install_release failed: {no_matching_relup,
remote:                                                       "0.0.1501113000",
remote:                                                       "0.0.1501036767"}
```

**Comment by bitwalker** [comment]
Once you've built your first release, i.e `MIX_ENV=prod mix release`, you can build an upgrade release with just `MIX_ENV=prod mix release --upgrade `. Other flags are optional, but those are the basics. There is actually a couple of detailed walkthroughs in the docs, at https://hexdocs.pm/distillery, I would check those out for additional context and deployment instructions. I'm on my phone, so unfortunately it's hard to be verbose haha

**Comment by jespr** [comment]
Still an impressive amount of text from a phone :) That solved it. I can now deploy. Let's see if I can solve that `unicode_util` problem - adding `unicode_util_compat` to deps (and applications) didn't seem to make a diff. Might be worth upgrading to OTP 20 and see if that helps :) Thank you

**Comment by bitwalker** [comment]
Awesome! Let me know if I can be of any help :)
