### ISSUE TITLE
should include_erts: true include jinterface jar files

### ISSUE THREAD

**Issue by djgoku** [bitwalker/distillery#296]
We are building an application that uses jinterface to communicate from a java application to our elixir application. I just noticed that we have to build Erlang to have the needed jar files.

Am I missing a configuration or should this be included?

**Comment by bitwalker** [comment]
If your Erlang install was built with jinterface, then I think it should, yes. I'll take a look and see if we need to include a directory that we're not including which contains the jars.

**Comment by bitwalker** [comment]
So from what I can see the only non-standard folder in `:jinterface` is a `java_src` folder - but it's Java source files, not jars. The only jar is `OtpErlang.jar` which is in the `priv` folder of `:jinterface` - so as long as your application puts `:jinterface` in it's applications list, it should be included when you have `include_erts: true`.

**Comment by djgoku** [comment]
Thanks for the quick reply. Yeah I didn't find much info while googling. But you are correct adding `:jinterface` to our applications list does include the `OtpErlang.jar` in the release!

If I was going to add this to the official documentation where would you want me to add this or is this something not worth adding?

**Comment by bitwalker** [comment]
I'm open to adding anything that helps people out :). I would add this to the Common Issues/Questions doc, since it's a better place for various tips.
