### ISSUE TITLE
Setting RELEASE_CONFIG_DIR in umbrella does not appear to work with Conform

### ISSUE THREAD

**Issue by iacobson** [bitwalker/distillery#297]
Trying to deploy an Umbrella app with Distillery (1.4.1) and Conform (2.4.0), Elixir 1.4.5, Erlang 20. 
We have the ".conf" file generated by with Puppet.
We deployed many Phoenix projects with this setup in the past and worked fine using `RELEASE_CONFIG_DIR` to point to the conf file.

Now trying to deploy an Umbrella that has 2 apps inside:
- my_umbrella
  - app_1
  - app_2

We build the release for the Umbrella.
put the `my_umbrella.config` in the `config/dir`
And try to start the console with: 
`RELEASE_CONFIG_DIR=config/dir _build/prod/rel/my_umbrella/bin/my_umbrella console`

But the app is not getting the config from the `config/dir`
It is just looking for `_build/prod/rel/my_umbrella/releases/0.1.0/my_umbrella.conf`
If that file is empty, it will just use the default empty values from the conform schema.

### rel.config

```
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :""
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :""
end

release :my_umbrella do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    app_1: :permanent,
    app_2: :permanent
  ]
  set post_start_hook: "rel/hooks/post_start"
  plugin Conform.ReleasePlugin
end
```

Is there anything we are missing to have the configuration available through `RELEASE_CONFIG_DIR` for the umbrella ?

**Comment by bitwalker** [comment]
What is `config/dir` in this case? Is it an absolute path? If it's relative that may be the problem. Can you run the same command but with `DEBUG_BOOT=true` and gist the output? I'm assuming both your `schema.exs` and `.conf` are under `config/dir` (or whatever path that represents) correct?

**Comment by bitwalker** [comment]
Alternatively if you are generating the `sys.config` with Conform, and putting that under `config/dir`, you need to make sure it's named `sys.config` and not something else.

**Comment by iacobson** [comment]
First of all, sorry for the confusion with `config/dir` , this is not the same as the elixir/phoenix apps `config`.
It was just a directory where I pasted in the `.conf` file. Let's call it now `my_config` directory to avoid confusion. For my test, I put `my_config` directory in the umbrella root.

In the first phase, to avoid the above issue we created a **master** app as in your example: https://github.com/bitwalker/distillery-umbrella-test

Building the **master** app release, putting in `my_config/master.conf` and running
`RELEASE_CONFIG_DIR=myconfig _build/prod/rel/master/bin/master console`
run perfectly with `myconfig` as relative or absolute path.

**Back to the issue:** 
I just tried to reproduce it again and run the DEBUG_BOOT as you asked. However, during this time, I upgraded Elixir to 1.5, and had also to update Conform to 2.5.
But this time, running
`RELEASE_CONFIG_DIR=my_config _build/prod/rel/my_umbrella/bin/my_umbrella console`
worked fine.
I could access for example `Application.get_all_env(:app_1)` and would get all related config from my `my_config/my_umbrella.conf`
Not sure at all if the elixir/conform update solved the issue, but now it works as expected.
