### ISSUE TITLE
Embedded read-only filesystem support

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/distillery#3]
Review documentation on read-only filesystems [here](http://erlang.org/doc/design_principles/release_structure.html)

- Make sure applications can be built to target a RO filesystem
- Make sure applications can be upgraded/downgraded on RO filesystems (if possible)

**Comment by bitwalker** [comment]
Waiting to hear back from the Nerves team on what we can do to help

**Comment by mobileoverlord** [comment]
@bitwalker Thanks for the link and consideration. I'll start digesting it and assembling questions / topics we can work through and get back to you soon. 😄

**Comment by bitwalker** [comment]
No problem :). From my explorations of Nerves itself, it seems like there may not be much we need to do, but I don't know how much of that was due to how exrm has worked up until now. If there are better ways to use releases on embedded hardware, I'd like to make sure those facilities are baked in to distillery.

**Comment by bitwalker** [comment]
I've done some research on this, and from what I gather, support for releases (primarily upgrades) on RO filesystems is done by having a "release master" system, from which the RO nodes get release information. I don't know that this model is particularly useful for what Nerves is targeting, and I don't know of any good use outside of the embedded realm for that. I'm going to close this for now, but please reopen it if distillery can do more to support Nerves in the future. If what I've described above does sound useful, I'll reopen this and try to determine what support looks like.

**Comment by fhunleth** [comment]
@bitwalker, if I could speak for @mobileoverlord as well, I think that our feedback is that exrm and presumably distillery work well enough for us that we don't have any substantive comments. I'm looking forward to migrating Nerves to distillery in the near future, and I'll let you know if there are any issues or any nice-to-haves. Thanks for keeping us in mind.
