### ISSUE TITLE
Foreground mode doesn't work on Ubuntu

### ISSUE THREAD

**Issue by petrikero** [bitwalker/distillery#30]
When trying to run the generated release on my Ubuntu machine, the release won't start and gives the error "trap: SIGUSR1: bad trap".

I believe this is due to the trap command being give the signals in the form SIGUSR1 / SIGUSR2, which dash (the Ubuntu default shell) doesn't accept. It wants them to be without the SIG prefix: USR1 and USR2.

Apparently, the correct form is to provide the signals without the prefix, at least according to the Open Group's specs (http://pubs.opengroup.org/onlinepubs/007904975/utilities/trap.html): "The condition can be [...] a signal specified using a symbolic name, without the SIG prefix, [...]".

The offending line is in priv/templates/boot.eex, in the case for handling foreground launches:
        trap '{}' QUIT TERM KILL HUP SIGUSR1 SIGUSR2

The script starts working when changed into this:
        trap '{}' QUIT TERM KILL HUP USR1 USR2

**Comment by shanesveller** [comment]
@petrikero there is related information in #18 and #19.

**Comment by bitwalker** [comment]
I'm going to do some testing on #19, and if it is more portable than what's there now, I'll merge the changes for the signal names manually.
