### ISSUE TITLE
GenServer's code_change receives incorrect vsn when hot code upgrading

### ISSUE THREAD

**Issue by pdawczak** [bitwalker/distillery#300]
### Steps to reproduce

I was struggling to run some code in [`GenServer.code_change/3`](https://hexdocs.pm/elixir/GenServer.html#c:code_change/3), so I was trying to modify the code to nail down the problem.

I've managed to prepare the minimal piece of code to make `code_change` execute and I've discovered that this function is call with wrong (or at least - _unexpected_) `vsn`.

Please consider following code I used for reproducing:

```elixir
   def code_change(vsn, state, extra) do
     Logger.info("UPGRADING [code_change] -> vsn: #{inspect vsn}, state: #{inspect state}, extra: #{inspect extra}")

     {:ok, state * 100}
   end
```

When generating the release everything worked:

```
MIX_ENV=prod mix do compile, phx.digest, release --env=prod --upgrade
```

```
Generated deploy app
Check your digested files at "priv/static"
==> Assembling release..
==> Building release deploy:0.0.15 using environment prod
==> Including ERTS 9.0 from /Users/username/.asdf/installs/erlang/20.0/lib/erlang/erts-9.0
==> Generated .appup for deploy 0.0.14 -> 0.0.15
==> Relup successfully created
==> Packaging release..
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/deploy/bin/deploy console
      Foreground: _build/prod/rel/deploy/bin/deploy foreground
      Daemon: _build/prod/rel/deploy/bin/deploy start
```

After copying the release to separate directory and running:

```
▶ ./bin/deploy upgrade 0.0.15
```

it worked properly:

```
Release 0.0.15 not found, attempting to unpack releases/0.0.15/deploy.tar.gz
Unpacked successfully: "0.0.15"
Release 0.0.15 is already unpacked, now installing.
Installed Release: 0.0.15
Made release permanent: "0.0.15"
```

But in the logs, I've found what arguments are passed to my `code_change`:

```
07:27:10.514 [info] UPGRADING [code_change] -> vsn: 215830729874762829975669963350986035955, state: 115766068, extra: []
```

Similarly, when I was trying to perform another upgrade to check arguments, I was upgrading to next version `"0.0.16"` and the `vsn` was `46904760726157759309061750772808061065`.

### Description of issue

- What are the expected results?
    **Proper `vsn` should be passed to my function, so I can pattern match on it**
- What OS, Erlang/Elixir versions are you seeing this issue on?
    * macOS Sierra 10.12.6
    * Erlang 20
    * Elixir 1.5
    * Phoenix 1.3
    * Distillery 1.4:

```
* distillery 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (distillery) 546d851b
```

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
  **Default one generated by `mix release.init`**
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
**Don't have link for documentation, but I believe my understanding of `code_change` is to use application's configured version so it can be performed reliably**

Thanks for your help!

**Comment by michalmuskala** [comment]
The version passed to `code_change` is the version of the module. Each module can be annotated with a `@vsn` attribute. By default, it's the md5 checksum of the source.

**Comment by pdawczak** [comment]
Ok, I see. Thanks for suggestion. I'll try this and I'll get back with
results!

**Comment by bitwalker** [comment]
@michalmuskala pretty much nailed it, but I think this could be clarified in the docs, so I'll add a note to my todo list to do so. Thanks for the report!

**Comment by pdawczak** [comment]
Thanks @michalmuskala that indeed helped. Thank for clarification!

On separate note thou, the original issue I had was to hot upgrade my Phoenix Channel (and from there I was debugging going down from abstractions to _bare bones GenServer_).

In case of Phoenix Channel it doesn't even execute my `code_change` function, which is designed to accept any arguments (like GenServer presented above).

Surprisingly, it looks like the release is aware of my `code_change` as per:

```
▶ cd release/<latest_release>
▶ ack code_change
```

with result:

```
relup
21:    {code_change,up,[{'Elixir.Deploy.SampleServer',[]}]},
27:    {code_change,up,[{'Elixir.DeployWeb.FunChannel',[]}]},
55:    {code_change,down,[{'Elixir.Deploy.SampleServer',[]}]},
61:    {code_change,down,[{'Elixir.DeployWeb.FunChannel',[]}]},
```

Please note, `SampleServer` is the GenServer I described earlier, and `FunChannel` is the mentioned Phoenix's Channel I'm trying to hot code upgrade.

Is it worth discussing it here, or is it better to open separate issue?

Thanks for your help!

**Comment by bitwalker** [comment]
Could you open that as a new issue? In there, can you also provide the code for the channel module? You can strip out the other callbacks, but I can work from there to figure out what may be going on.

What I suspect is the case is that the channel module is actually being delegated to from another process, and so there are no processes backed by `FunChannel` to upgrade - distillery still detects the code_change callback and assumes the module needs an upgrade instruction when it actually doesn't. That said, I thought I protected against that by also ensuring the module was a special process (i.e. implements something like the GenServer behavior). I'll dig in deeper in the morning.
