### ISSUE TITLE
strange log message "$@" -- "${1+$ARGS}"

### ISSUE THREAD

**Issue by tap349** [bitwalker/distillery#319]
### Steps to reproduce

1. build release with distillery v1.5.1
2. run release in foreground

### Verbose Logs

```
Sep 01 15:08:50 localhost systemd[1]: Started Phoenix server for my_app.
Sep 01 15:08:53 localhost my_app[3472]: "$@" -- "${1+$ARGS}"
Sep 01 15:08:55 localhost my_app[3472]: 15:08:55.932 [debug] AppSignal starting.
```

### Description of issue

After updating distillery from 1.4.1 to 1.5.1 I see strange log message - I guess it's expected to be interpreted by bash but for some reason it's not.

Ubuntu 16.04.2 LTS
Erlang/OTP 20
Elixir 1.5.0

I use edeliver to build release (edeliver hasn't been updated).

**Comment by bitwalker** [comment]
It's put there when reattaching stdout to the tty after running post-start hooks, so it's normal. I'll see if I can silence it, but it's expected.
