### ISSUE TITLE
Restarting after a deploy does not restart epmd

### ISSUE THREAD

**Issue by myronmarston** [bitwalker/distillery#320]
### Steps to reproduce

We use distillery to package our releases, and deploy by putting the release tarball on our deploy targets, unpacking them, stopping the prior release, and starting the new one.  I noticed recently that the `epmd` daemon that's running on our production servers is quite old (running from a directory tagged with a date from May) and is even running a different ERTS version (8.3 instead of 9.0).  Here's some `ps` output showing this from one of our servers (with some sensitive bits changed):

``` shell
$ ps aux | grep [e]rts
some_user     896  0.0  0.0   7616   716 ?        S    May30   0:55 /path/to/app/root/releases/admin-2017-05-25T19-26-52Z-by-myron/erts-8.3/bin/epmd -daemon
some_user   14861  1.6  2.4 3798864 98952 pts/1   Sl+  16:44   0:04 /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/erts-9.0/bin/beam.smp -Bd -K true -A 20 -- -root /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron -progname path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/releases/0.0.1/admin.sh -- -home /home/some_user -- -noshell -noshell -noinput -boot /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/releases/0.0.1/admin -boot_var ERTS_LIB_DIR /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/erts-9.0/../lib -pa /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/lib/admin-0.0.1/consolidated -name admin@somehost.com -setcookie redacted -config /path/to/app/root/releases/admin-2017-09-01T16-42-58Z-by-myron/var/sys.config -mode embedded -extra -- foreground
```

While we haven't had any concrete problems from this, it seems like it could cause problems, and in general, when we upgrade the erlang/OTP version included in a deployed release, I'd expect `epmd` to get updated to that version on deploy as well.

### Verbose Logs

N/A

### Description of issue

Really, this is just a set of questions:

1. Is restarting `epmd` something that distillery's scripts should do?  Or are we responsible for restarting it ourselves?
2. If we're responsible, what's the recommended way to do that? (e.g. is it safe just to `kill -9` the `epmd` pid, and then trust that it'll get started as needed after that when we boot our app?)
3. If this is something users should handle, can the distillery docs be updated to mention it?

Thanks!

**Comment by tap349** [comment]
AFAIK `epmd` is started automatically when app is started unless there is already running `epmd` instance - then it's used (app must be a distributed Erlang node).

killing `epmd` process might result in losing information about running nodes - it's not an issue if you have a single application.

I've ended with having a separate systemd service that runs `epmd` while application services require it to be activated in their units.

in my opinion distillery shouldn't manage `epmd` because there might be other applications that use it. and if distillery restarts `epmd` they might not get registered in it again.

still I might be wrong - these are just my recent findings as I had to deal with `epmd` some time ago.

**Comment by myronmarston** [comment]
Thanks for the info, @tap349!  Do you know if it causes any problems for `epmd` to be running a different OTP/ERTS version than your beam processes?  If there's some strong guarantee from the OTP team that old `epmd` processes will always be able to work properly with newer beam processes, maybe it's not a big deal to just leave the old one running.  I'm not really sure.

**Comment by bitwalker** [comment]
I agree with @tap349 - Distillery can't make decisions about `epmd` unfortunately, at least not without some opt-in from the user. I have not tested to see how Erlang handles the case of upgrading the runtime with a running `epmd`, perhaps Erlang does something about it during hot upgrades. In any case, I think the thing to do there is to kill it manually as part of the upgrade/deploy script if it is causing you problems.

**Comment by myronmarston** [comment]
Makes sense.  @bitwalker -- does it makes sense to add anything to the distillery docs about this?

**Comment by bitwalker** [comment]
I think it's worth adding a note since it caught you unawares, and one person is one too many as far as docs are concerned. I'm pretty swamped today, so if you wanted to open a PR with the change, I'll gladly merge it, otherwise I'll try to get to it later this weekend.

**Comment by pgrunwald** [comment]
I encountered a related issue when I upgraded `distillery` from `2.4.0` to `2.5.2`:

After upgrading the `distillery` version, when I restarted my application's `systemd` service, I encountered this error output from the service:

```
systemd[1]: Started Service for my_app.
systemd[1]: Starting Service for my_app...
my_app[3077]: ==> Generated sys.config in /opt/my_app/releases/20170919083635Z_2fd45a6b/var
my_app[3077]: "$@" -- "${1+$ARGS}"
epmd[61665]: epmd: node name already occupied my_app
my_app[3077]: Protocol 'inet_tcp': the name my_app@10.1.1.4 seems to be in use by another Erlang node
systemd[1]: my_app.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit my_app.service entered failed state.
systemd[1]: my_app.service failed.
```

Looking at the service status, it seems that after updating `distillery` running `service my_app stop` no longer kills the child processes, only the main process gets killed:

```
[root@dev-myapp-server-app1 ~]# service my_app stop
Redirecting to /bin/systemctl stop  my_app.service
[root@dev-myapp-server-app1 ~]# service my_app status
Redirecting to /bin/systemctl status  my_app.service
● my_app.service - Service for my_app
   Loaded: loaded (/etc/systemd/system/my_app.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2017-09-19 10:07:34 UTC; 2s ago
  Process: 46437 ExecStart=/opt/my_app/current/bin/my_app foreground (code=killed, signal=TERM)
 Main PID: 46437 (code=killed, signal=TERM)
   CGroup: /system.slice/my_app.service
           ├─46693 /opt/my_app/releases/20170919083635Z_2fd45a6b/erts-9.0/bin/beam.smp -Bd -- -root /opt/my_app/releases/20170919083635Z_2fd45a6b -progname...
           ├─46697 /opt/my_app/releases/20170919083635Z_2fd45a6b/erts-9.0/bin/epmd -daemon
           ├─46709 erl_child_setup 1024
           ├─46725 inet_gethost 4
           └─46726 inet_gethost 4
```

My `systemd` service looks like this:

```
[Unit]
Description=Service for my_app
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/my_app/current
User=my_app
Group=my_app
EnvironmentFile=/opt/my_app/conf/my_app.env
ExecStart=/opt/my_app/current/bin/my_app foreground
KillMode=process
SuccessExitStatus=143
TimeoutStartSec=10
TimeoutStopSec=30
Restart=on-failure
RestartSec=5
SyslogIdentifier=my_app

[Install]
WantedBy=multi-user.target
```

If I downgrade `distillery` to `2.4.0` again, this issue does not occur. I can stop and restart the service without encountering this problem.

Not sure if this is related or helpful. I can a separate issue if this is unrelated.

**Comment by myronmarston** [comment]
@pgrunwald: what you're describing sounds like #321, which has been fixed in master.

**Comment by pgrunwald** [comment]
@myronmarston, yes, you're exactly right. I don't know how I missed that issue when browsing the issues, apologies.
