### ISSUE TITLE
Regression in 1.5: killing the `foreground` process no longer propagates to the beam process

### ISSUE THREAD

**Issue by myronmarston** [bitwalker/distillery#321]
### Steps to reproduce

1. `mix new distillery_test`
2. `cd distillery_test`
3. edit `mix.exs`, and add this dependency to the `deps` function: `{:distillery, "1.5.1"}`
4. `mix deps.get`
5. `mix compile`
6. `mix release.init`
7. `MIX_ENV=prod mix release`
8. `_build/prod/rel/distillery_test/bin/distillery_test foreground`
9. In another shell, find the pid of the process running a command like `/bin/sh /Users/myron/code/distillery_test/_build/prod/rel/distillery_test/releases/0.1.0/distillery_te
st.sh foreground`; then run `kill <pid>` to send it a TERM signal.
10. Notice that the specific process you killed stopped, but the child beam process continues to run.
11. Kill the beam process as well to clean up.
12. Change the dependency in `mix.exs` to `{:distillery, "1.4.1"}`
13. Repeat steps 4 through 9 (except for the `mix release.init` step).
14. Notice that both the shell script process and the beam process stopped, demonstrating that on 1.4 TERM signals properly progapate to the child beam process.

### Verbose Logs

N/A

### Description of issue

- What are the expected results?

I expect `kill <pid of process started with foreground command>` to halt the beam process.  More specifically, we use [upstart](http://upstart.ubuntu.com/) in production as part of our deploy process, and we run `sudo service <app name> restart` to restart our app on deploy.  This has stopped working since we upgraded to Distillery 1.5 because the beam process from the prior deploy never stops, and when the new one starts it gets an error like `Protocol 'inet_tcp': the name app_name@apphost seems to be in use by another Erlang node`.  I have to manually kill the old beam process to get our deploy to succeed.  On 1.4 the TERM signal propagated properly, allowing upstart restarts to work, and I expect that to continue to work in 1.5.

- What OS, Erlang/Elixir versions are you seeing this issue on?

Originally saw this on Ubuntu 14.04, but I can repro on OS X El Capitan.  We're using OTP 20/Elixir 1.5.1 in both cases.

- If possible, also provide your `rel/config.exs`, as it is often my first troubleshooting question, and you'll save us both time :)

N/A -- I can repro with the default generated `rel/config.exs`.

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

I don't think the behavior from 1.4 and before is documented in the distillery docs, but it's part of being a good unix citizen for parent processes to propagate a TERM signal to their children.

**Comment by bitwalker** [comment]
Hmm, I may have missed something in my refactor to rely on OTP 20's signal handler, I'll take a look. Thanks for reporting!

**Comment by DavidOliver** [comment]
Same for me in Ubuntu 16.04 LTS.

**Comment by bitwalker** [comment]
This should now be fixed on master. I'm working on a couple open issues, so I won't be pushing a release for a little while longer, but you may want to test with master to make sure things look good from your end.

**Comment by DavidOliver** [comment]
Looks good to me on master. Thanks.
