### ISSUE TITLE
kubernetes graceful restart

### ISSUE THREAD

**Issue by jeffrom** [bitwalker/distillery#336]
In kubernetes, i expect to set the bash script that acts as a frontend for distillery as the entry point:

```
CMD REPLACE_OS_VARS=true _build/prod/rel/$APP/bin/$APP foreground
```
However this process doesn't trap SIGTERM, and therefore you don't get a graceful restart. instead kubernetes waits for the grace period to end and then hard kills the beam process.

Happy to submit a PR if you want to address this.

Thanks!

**Comment by bitwalker** [comment]
Looks like I haven't pushed a new release containing the fix for this (amongst other things). I'm doing that now (tagged 1.5.2). Can you upgrade and confirm it fixes the issue for you once it's up on hex?

**Comment by jeffrom** [comment]
that did it. thank you!
