### ISSUE TITLE
Irrelevant warning about missing cookie even when using a custom vm.args

### ISSUE THREAD

**Issue by mconigliaro** [bitwalker/distillery#346]
```
==> Attention! You did not provide a cookie for the erlang distribution protocol in rel/config.exs
    For backwards compatibility, the release name will be used as a cookie, which is potentially a security risk!
    Please generate a secure cookie and use it with `set cookie: <cookie>` in rel/config.exs.
    This will be an error in a future release.
```

This is an odd error considering that:

1. We're using our own `vm.args` via the `vm_args` option so we can set the cookie via an environment variable at runtime . Maybe I'm missing something, but I don't know how setting the cookie in `rel/config.exs` is even relevant in that scenario.
1. Is it not a potential security risk to have a secret cookie checked in to your repo in plaintext?

I hope this doesn't actually become an error someday.

**Comment by bitwalker** [comment]
Just set the cookie in the config to something other than the default. We do not currently read custom vm.args to determine if you have properly set a cookie or not. If you change the default to anything, even "ignore", the warning is silenced. It's somewhat naive warning detection, but it's there to ensure that if someone doesn't change the default cookie, they are made aware that the cookie is insecure under those conditions, the intent is not that you set your "real" cookie in `rel/config.exs`, but that you have considered it and set it to _some_ value other than the default to indicate that.

**Comment by mconigliaro** [comment]
Makes sense. Thanks!
