### ISSUE TITLE
[Suggestion] An option to avoid creating the tarball

### ISSUE THREAD

**Issue by alexcastano** [bitwalker/distillery#351]
I cannot find a way to avoid the last step of creating the tarball. I think can be useful to have this option if you use the Docker images to deploy (not only to build). The last step of a Dockerfile is usually something similar to this:

```Dockerfile
COPY --from=builder /app/_build/prod/rel/my_app .
```

But this generates an image with double size: the files and the tarball. Copy the tarball and untar it makes the image bigger anyway too.

Thank you for your time.

**Comment by bitwalker** [comment]
Did you try `--no-tar`? It's in the documentation, as well as the output of `mix help release`

**Comment by alexcastano** [comment]
Thanks! I could not find it :+1:
