### ISSUE TITLE
Environment variable not present after hot upgrade on Phoenix 1.3 app

### ISSUE THREAD

**Issue by jfcalvo** [bitwalker/distillery#352]
Phoenix: 1.3.0
Distillery: 1.5.2

I'm using two environment variables to config my application on production: `PORT` and `SECRET_KEY_BASE` on a Phoenix App (v.1.3).

These two environment variables are defined in a systemd service file that I created to facilitate the control of the server process [as explained on distillery docs](https://hexdocs.pm/distillery/use-with-systemd.html#content):

```
[Unit]
Description=Phoenix server for myapp
After=network.target

[Service]
Type=simple
User=deploy
Group=deploy
WorkingDirectory=/home/deploy
Restart=on-failure
RestartSec=5
Environment=PORT=80
Environment=SECRET_KEY_BASE=MY_SECRET_KEY_BASE
SyslogIdentifier=myapp
RemainAfterExit=no
ExecStart=/home/deploy/bin/myapp foreground
ExecStop=/home/deploy/bin/myapp stop

[Install]
WantedBy=multi-user.target
```

I'm loading these environment variables in my `MyApp.Endpoint` module like this:

```elixir
defmodule MyApp.Endpoint do
  def init(_key, config) do
    if config[:load_from_system_env] do
      port = System.get_env("PORT") || raise "expected the PORT environment variable to be set"
      secret_key_base = System.get_env("SECRET_KEY_BASE") || raise "expected the SECRET_KEY_BASE environment variable to be set"

      config =
        config
        |> Keyword.put(:http, [:inet6, port: port])
        |> Keyword.put(:secret_key_base, secret_key_base)

      {:ok, config}
    else
      {:ok, config}
    end
  end
end
```

And with the following `config/prod.exs`:

```elixir
config :myapp, MyApp.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}],
  url: [host: "localhost", port: {:system, "PORT"}],
  secret_key_base: {:system, "SECRET_KEY_BASE"},
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:myapp, :vsn)
```

For some unknown reason after a hot upgrade from v0.0.1 to v0.0.2 of my app the `SECRET_KEY_BASE` is not found and an internal server error is returned if tried to access the web app. The error is the following:

```
Oct 18 16:52:49 MyApp-14 MyApp[8339]: 16:52:49.555 [error] Ranch listener MyAppWeb.Endpoint.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.1613.0> exit with reason: {{%ArgumentError{message: "argument error"}, [{:crypto, :hmac_nif, [:sha256, {:system, "SECRET_KEY_BASE"}, <<106, 109, 79, 75, 69, 108, 118, 70, 0, 0, 0, 1>>], []}, {:crypto, :hmac, 6, [file: 'crypto.erl', line: 660]}, {Plug.Crypto.KeyGenerator, :generate, 7, [file: 'lib/plug/crypto/key_generator.ex', line: 64]}, {Plug.Crypto.KeyGenerator, :with_cache, 3, [file: 'lib/plug/crypto/key_generator.ex', line: 50]}, {Plug.Session.COOKIE, :get, 3, [file: 'lib/plug/session/cookie.ex', line: 88]}, {Plug.Session, :"-fetch_session/1-fun-0-", 5, [file: 'lib/plug/session.ex', line: 75]}, {MyAppWeb.Router, :browser, 2, [file: 'lib/MyApp_web/router.ex', line: 4]}, {MyAppWeb.Router, :"-__match_route__/4-fun-1-", 1, [file: 'lib/MyApp_web/router.ex', line: 1]}]}, {MyAppWeb.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "MyApp-14.MyAppapp.com", method: "GET", owner: #PID<0.1613.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["sessions", "new"], path_params: %{}, peer: {{0, 0, 0, 0, 0, 65535, 21818, 36970}, 17402}, port: 80, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {0, 0, 0, 0, 0, 65535, 21818, 36970}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "MyApp-14.MyAppapp.com"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"}, {"upgrade-insecure-requests", "1"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate"}, {"accept-language", "es-ES,es;q=0.8,en;q=0.6"},
Oct 18 16:52:49 MyApp-14 MyApp[8339]: {"cookie", "_MyApp_key=I-HAVE-REMOVED-THIS"}], request_path: "/sessions/new", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}
```

This is only fixed if I stop and start the service again.

Is this a bug or I'm doing something wrong? Why are not environment variables reutilized from the previous version after the hot upgrade?

Why is not happening the same with the `PORT` var?

**Comment by bitwalker** [comment]
Is `init` even being called during the upgrade? The deal with the PORT is that the socket is already bound, and the code holding it must not be getting upgraded (or deals with upgrading by handing the socket off to the new version) - this SECRET_KEY_BASE value is clearly in code that was upgraded, but as far as I can tell, `init` is never being called during the upgrade. Can you confirm that?

**Comment by jfcalvo** [comment]
> Is init even being called during the upgrade? 

I'm not doing anything special to execute the `init` after the upgrade so I suppose that it is not being executed.

> this SECRET_KEY_BASE value is clearly in code that was upgraded

If I execute the following in v.0.0.1 on a remote console:

```elixir
iex(myapp@127.0.0.1)1> System.get_env("SECRET_KEY_BASE")
"Z4SfnHJwTfdY........."
iex(myapp@127.0.0.1)2> :ets.lookup(MyAppWeb.Endpoint, :secret_key_base)
[secret_key_base: "Z4SfnHJwTfdY........."]
```

The environment variable is correctly there and Phoenix has saved it. Everything working fine.

Executing the same after the hot upgrade to v.0.0.2:

```elixir
iex(myapp@127.0.0.1)1> System.get_env("SECRET_KEY_BASE")
"Z4SfnHJwTfdY........."
iex(myapp@127.0.0.1)2> :ets.lookup(MyAppWeb.Endpoint, :secret_key_base)
[secret_key_base: {:system, "SECRET_KEY_BASE"}]
```

The SECRET_KEY_BASE is clearly there in the environment but once you ask for it looks like it has not been correctly loaded causing the original problem.

---

What other alternatives do I have to maintain the value of SECRET_KEY_BASE after the upgrade? I don't care to change it to a different strategy, I was only following the [Configuration Conventions section](https://hexdocs.pm/distillery/runtime-configuration.html#configuration-conventions) of the documentation.

If a possible solution is to execute again the `init` function. How can I do that? Will I break the upgrade some way executing the init again?.

If there is a more simpler solution I am all ears.

Thank you very much for the help.

**Comment by bitwalker** [comment]
I suspect the reason `init` isn't being invoked is because Phoenix isn't being upgraded, but I haven't looked in depth enough to know for sure if that's the issue. Regardless, the easiest workaround is to use `"$SECRET_KEY_BASE"` in your config rather than `{:system, "SECRET_KEY_BASE"}`, and make sure `REPLACE_OS_VARS=true` is exported in the environment on the host the release is deployed to - this will ensure that the config has the proper value when it is loaded during the upgrade process.

**Comment by jfcalvo** [comment]
@bitwalker as you has explained in the previous comment I have modified my systemd file including `REPLACE_OS_VARS=true` and modified my app production config file to use `"${SECRET_KEY_BASE}"`:

```elixir
config :futon, MyApp.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}],
  url: [host: "localhost", port: {:system, "PORT"}],
  secret_key_base: "${SECRET_KEY_BASE}",
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:myapp, :vsn)
```

The systemd file is the following:

```
[Unit]
Description=Phoenix server for myapp
After=network.target

[Service]
Type=simple
User=deploy
Group=deploy
WorkingDirectory=/home/deploy
Restart=on-failure
RestartSec=5
Environment=REPLACE_OS_VARS=true
Environment=PORT=80
Environment=SECRET_KEY_BASE=MY_SECRET_KEY_BASE
SyslogIdentifier=myapp
RemainAfterExit=no
ExecStart=/home/deploy/bin/myapp foreground
ExecStop=/home/deploy/bin/myapp stop

[Install]
WantedBy=multi-user.target
```

I have added `REPLACE_OS_VARS=true` to the `~/.profile` file of the user I use to execute the upgrade command.

Everything looks working as expected when the initial release is deployed (env vars loaded using $ like `"${SECRET_KEY_BASE}"` looks like working) but when I try to do an upgrade (hot upgrade) to a new version I still have the same problem, the secret key base is not correctly loaded after the hot upgrade (from version 0.0.1 to 0.0.2) and I have the same error when trying to access the server via web.

I still have the following code on Endpoint init:

```elixir
def init(_key, config) do
  if config[:load_from_system_env] do
    port = System.get_env("PORT") || raise "expected the PORT environment variable to be set"
    secret_key_base = System.get_env("SECRET_KEY_BASE") || raise "expected the SECRET_KEY_BASE environment variable to be set"

    config =
      config
      |> Keyword.put(:http, [:inet6, port: port])
      |> Keyword.put(:secret_key_base, secret_key_base)

    {:ok, config}
  else
    {:ok, config}
  end
end
```

I'm really lost here. Any idea on how to fix this and allow me to do hot upgrades with working environment vars? Any suggestion is welcome.

Thanks.

**Comment by jfcalvo** [comment]
I have finally have some success executing the upgrade command and passing all the necessary environment vars:

```sh
$ REPLACE_OS_VARS=true HOST=www.myapp.com PORT=80 SECRET_KEY_BASE=MY_SECRET_KEY_BASE  bin/myapp upgrade 0.0.2
```

I don't know why but because I defined the systemd file including all the environment vars I (wrongly) though that if I execute a `upgrade` command this would be executed on the environment of the systemd daemon, and that is not correct, you need to have those environment vars available when you want to execute the `upgrade` command.

Maybe we should add some information about this in the systemd part of the documentation?.

**Comment by lessless** [comment]
@jfcalvo this is a system issue and quite logical if you think about it - those variables are injected upon service startup only, when `systemd` has control over the app environment.

**Comment by jfcalvo** [comment]
@lessless It's not totally clear that the upgrade is not made inside the systemd environment, for that reason I though that maybe documentation need some clarification about this.

**Comment by bitwalker** [comment]
Definitely need to fix the documentation, thanks!
