### ISSUE TITLE
Failed to release with Quantum

### ISSUE THREAD

**Issue by QwertyJack** [bitwalker/distillery#359]
### Steps to reproduce

Add cron job using [Quantum](https://hexdocs.pm/quantum/readme.html), and my `config/prod.exs` is like:
```
...
config :my, My.Scheduler,  
  jobs: [             
    say_hi: [                                      
      schedule: "* * * * *",        
      task: fn -> IO.puts "Hi !" end
    ]
  ]
...   
```

Then `MIX_ENV=prod mix release` failed.
### Verbose Logs

```
...
==> Packaging release..
==> Archiving my-0.0.1
==> Writing tarball to _build/prod/rel/my/releases/0.0.1/my.tar.gz
==> Release packaging failed due to errors:
    Cannot add file sys.config to tar file - [{error,{20,erl_parse,["syntax error before: ",["Fun"]]}}]
```

### Description of issue

- What are the expected results?
  * It seems that the anony function is not recognized after compile.
- What OS, Erlang/Elixir versions are you seeing this issue on?
  * Ubuntu 16.04 lts, Erlang/OTP 20, Elixir 1.5.1
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
  * The default.
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
  * Nope.

**Comment by cjen07** [comment]
:+1:

**Comment by QwertyJack** [comment]
According to [this](https://hexdocs.pm/quantum/configuration.html#release-managers), anonymous function is not supported by release managers.
