### ISSUE TITLE
Dev release tarball not possible?

### ISSUE THREAD

**Issue by sashaafm** [bitwalker/distillery#363]
I'm playing around and using `Distillery` for releases and my current idea for a release workflow relies on a release tarball, similar to the tarball generated when using the `prod` environment. 

At least by default, `Distillery` doesn't seem to generate tarball when the env is `dev`. Is there a way to do it, and if not I'd like to propose it. 

Other tools, mainly `rebar3`, allow to generate a release tarball for any environment AFAIK and I think this would be a nice feature to keep `distillery` on par with its Erlang counterpart.

I'm using `distillery` 1.5

**Comment by bitwalker** [comment]
I think you are confusing Mix environments with `dev_mode`. What is disabling the archival of the release is the fact that `dev_mode` is set to true, which symlinks everything into the appropriate places, and creating a tarball of this doesn't make sense. To build a "dev" release, either set `dev_mode: false` in the `:dev` environment in your `rel/config.exs`, or create a new environment with `dev_mode: false` and build your release with `mix release --env=<env_name>`.
