### ISSUE TITLE
Warn when release is started on a different OS

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/distillery#370]
Today, when a release is compiled on one OS  but launched on another, the error is usually very confusing and cryptic, for example:
```
erts-9.1.4/bin/erlexec: Syntax error: "(" unexpected
```

I propose that the boot script records some information about the system where release was built that is later used on start-up - if a mismatch is found, a warning should be issued. I propose to make it a warning and not an error, since there might be cases where everything will work just fine, though we shouldn't just "silently go down" in case it doesn't. The warning could also include a link to the relevant section of distillery docs.

**Comment by bitwalker** [comment]
Some of the work I'm doing right now will likely result in me recording target triples, so I think we can definitely make warning about this fall out from that effort. The easiest is to warn about BSD vs Linux vs Windows - but ideally we should warn about running on the wrong architecture, etc., as well.
