### ISSUE TITLE
Startup hook that runs before `vm.args` is injected

### ISSUE THREAD

**Issue by ijcd** [bitwalker/distillery#371]
I just noticed that you had asked me to open an issue in the tracker here for this.

There is sometimes a need to do work early in the boot process (before `vm.args` is injected with env vars).

My particular use case is dynamic node naming in docker on AWS.

Discussion was here: https://elixirforum.com/t/dynamic-node-naming-with-distillery/7228/3

**Comment by bitwalker** [comment]
This is the `pre_configure_hooks` option. This hook runs before sys.config or vm.args are generated, so you can create a new one, set up environment variables, whatever you need.
