### ISSUE TITLE
Dockerized releases run in Kubernetes cluster terminate abruptly

### ISSUE THREAD

**Issue by petrikero** [bitwalker/distillery#379]
### Steps to reproduce

Create a dockerized distillery deployment, run it inside a Kubernetes cluster, then stop the given deployment. This will cause an abrupt termination of the running Elixir application, not a clean shutdown.

### Description of issue

The expectation is that the Elixir application would run its shutdown sequence and only then actually exit the system process.

I'm using Distillery 1.5.1, OTP 20.1.4, and Elixir 1.5.2. The OS is Google's cos (default in their Kubernetes clusters). The release is running in 'foreground' mode. The base docker image used is alpine:3.6, on top of which I've installed bash and a few other libraries.

When I tried running the distillery build locally in an Ubuntu (no containers, just running the release in foreground mode from shell, I get different symptoms. When sending a SIGTERM to the bash process (the one that invokes the beam process), I get a "Terminated" into the shell running the distillery release, but the beam process keeps running in the background. When sending the SIGTERM to the beam process, the Elixir application shutdowns gracefully.

Perhaps this is what happens in the Kubernetes case as well, the Kubernetes SIGTERM gets sent to the bash process, not the beam process, and thus the Elixir shutdown sequence does not get triggered.

If there's something more I can do to help debug this issue, please let me know. It's awesome work that you're doing with Distillery!

**Comment by bitwalker** [comment]
Can you try with the latest version of Distillery? You are on an older version and this is something that was fixed in 1.5.2

**Comment by petrikero** [comment]
It does indeed work with 1.5.2. I'm not sure how I missed that it was already out. Sorry about the trouble.
