### ISSUE TITLE
mix release only generates a single artifact for umbrella application

### ISSUE THREAD

**Issue by madshargreave** [bitwalker/distillery#388]
Hi 

I want to deploy to deploy an umbrella app where each release is a separate docker container

Below you'll find my release config

```
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"adsaddsd"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"dadasdsadad"
end

release :api do
  set version: current_version(:api)
  set applications: [
    :runtime_tools
  ]
end

release :indexer do
  set version: current_version(:indexer)
  set applications: [
    :runtime_tools
  ]
end
```

Running `mix release` for this project will only generate a release bundle for the `api` app, not the `indexer` app.

If I specify the release name directly `mix relase --name-indexer` I can build them separately, but I'm not sure this is the intended use.

Am I missing something?

Thanks

**Comment by bitwalker** [comment]
Yeah, `mix release` will use the value of `--name`, or `:default_release` (where the default value of `:default` means the first release defined in the config). You need to specify the release you want to build with `--name` in this instance. I haven't added support for building multiple releases at once, but you could add an alias to `mix.exs` which does just that very easily.
