### ISSUE TITLE
"BEAM port" changes every time I restart the app release.

### ISSUE THREAD

**Issue by ryanwinchester** [bitwalker/distillery#400]
I have this shell script for connecting to remote node

```sh
#!/bin/sh

set -e

# https://jerel.co/blog/2016/12/connect-to-a-remote-elixir-node-deployed-with-distillery

BEAM_PORT=42903 # This changes every time I restart the APP
EPMD_PORT=4369
COOKIE='my_cookie_string'

ssh -f -o ExitOnForwardFailure=yes \
    -L "$EPMD_PORT:localhost:$EPMD_PORT" \
    -L "$BEAM_PORT:localhost:$BEAM_PORT" \
    my_app@my_app.com \
    sleep 10

iex --name debug@127.0.0.1 --cookie $COOKIE \
    -S mix run -e 'Node.connect(:"my_app@127.0.0.1")'
```

This works great. However, whenever I restart my app and the `BEAM_PORT` changes.

Is there a way to force the port to always be the same?

(I don't even know what `BEAM_PORT` is supposed to be called so googling is tough)

**Comment by bitwalker** [comment]
What you want is defined by the kernel config options `inet_dist_listen_min` and `inet_dist_listen_max`. They take a port number as a value, and define the start and end of the range respectively. Just be aware that each connection to the running node requires its own port, so restricting it to one port means only one thing can be connected at a time, which won't work for clusters. 

A more appropriate solution is to probably use Erlangs ssh daemon, and connect to that directly.

**Comment by ryanwinchester** [comment]
@bitwalker thanks. I'm okay with restricting it to one port for now.

my main reason for this is to be able to use `:observer` locally, and I'm not sure if erlang sshd would let me do that?

**Comment by bitwalker** [comment]
Yeah that's a good point, and in your case is just fine. For a cluster, you'd probably have to forward the whole range to make sure both you and the cluster have enough connections available. I should do some more research and see if I can find a generally applicable solution for the docs

**Comment by shymega** [comment]
@bitwalker Just wondering here, you mentioned the SSH daemon and Erlang, in what way were you thinking of using that? As a direct SSH connection to the cluster..? I have the same issue, and I'm trying to find an appropriate solution.

Thanks :)

**Comment by bitwalker** [comment]
@shymega I mentioned Erlang's sshd because it provides a way to do remote shell via ssh rather than using Erlang distribution (i.e. starting a local node and connecting it to the remote node/cluster for a remote shell).
