### ISSUE TITLE
Overriding of overlay vars in release

### ISSUE THREAD

**Issue by midas** [bitwalker/distillery#406]
Is it possible to override some overlay vars from an environment in the release definition?

**Comment by midas** [comment]
Another and better solution to the problem driving my last would be to accept a `:ip_address` var in the release.

The issue we have is we use [nodefinder](https://github.com/erlanger/nodefinder) to automatically discover all the nodes in our cluster.  Unfortunately nodefinder cannot discover nodes named `node-1@127.0.0.1`.  It must be the external IP of the machine, for instance `node-1@10.0.1.36`.

Would you accept a commit that add `:ip_address` as a var with a default of `127.0.0.1` that was templated into the `vm.args` file?

**Comment by bitwalker** [comment]
Environments take precedence over settings in the release definition, so you'd want the more general settings to be in the release definition, and provide overrides in the environment definition. If you have a situation where you need more fine-grained control, the easiest way to deal with that would be to write a small `before_package` plugin which modifies the overlays during assembly as needed.

**Comment by bitwalker** [comment]
I would recommend instead providing your own `vm.args` file via the `vm_args` setting, and provide the `ip_address` overlay var as a custom var yourself, you can then template out the `vm.args` as desired. The current `vm.args` file provided by Distillery is very basic, and really only intended to fill the necessary requirements for booting the release in distributed mode (e.g. it sets the node name and cookie)

**Comment by bitwalker** [comment]
I forgot to answer your question directly, sorry about that, I would prefer not to add more settings to the config when there is already an easy path to achieving the desired goal, as in the case you described.

**Comment by midas** [comment]
Well, there is a major issue still.  When using the `overlay_vars` or `vm_args`, you are forced to create either multiple environments or releases.  We need a level of indirection in either the environment or release to make it clean.  This is because the IP address is different for each defined build and each defined env, creating an multiplicative growth of environments or releases. 

For instance:

```
environment :dev do
  ...
end

environment :prod do
  ...
end

release :one do
   ...
  set overlay_vars: [
    node_name: "one"
  ]
end

release :two do
   ...
  set overlay_vars: [
    node_name: "two"
  ]
end
```

For `dev`the IP should be `127.0.0.1` for both `:one` and `:two`, resulting in node names of `one@127.0.0.1` and `two@127.0.0.1`.

However, for `prod` the IP for `:one` should be `10.0.1.1` and for `:two` should be `10.0.1.2`, resulting in `one@10.0.1.1` and `two@10.0.1.2`.

As you can see you would have to duplicate the releases like: `:one_prod` and `:one_dev` in order to pull this off.  This is because the `overlay_vars` and I assume the `vm_args` are overwritten by the environment version as opposed to being merged favoring the environment non nil values.

Is there a solution to this readily available tha tI am missing?  Hopefully so.

Thanks Paul!

**Comment by bitwalker** [comment]
I think the issue here is conflating release configuration with runtime configuration, which this falls under in my opinion. The way I would tackle this in my own project is by using `REPLACE_OS_VARS` on the target system, an overlay with the following shell script, and a `vm.args` as shown below:

```elixir
# rel/config.exs

release :one do
  set vm_args: "rel/vm.args"
  set overlay_vars: [node_name: "one"]
  set overlays: [
    {:copy, "rel/run.sh", "bin/start_<%= node_name %>"},
  ]
end

.. repeat for :two ...
```

```bash
#!/usr/bin/env bash

# Get bin directory
__bin_dir="$(cd "$(dirname "$0")" && pwd -P)"

# Get name of this app/node
__prog="$(basename "$0")"
export APP
APP="$(echo "$__prog" | sed -e 's/start_//')"

export REPLACE_OS_VARS=true
case "`uname`" in
    Darwin)
        export HOSTNAME="`ifconfig en0 | awk '{ print $2 }' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`"
        ;;
    *)
        export HOSTNAME="`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`"
        ;;
esac

"$__bin_dir/$APP" $@
```

```
# rel/vm.args
-name ${APP}@${HOSTNAME}
-setcookie foo
# or set it dynamically like so by exporting NODE_COOKIE in the environment
#-setcookie ${NODE_COOKIE}
```

This setup has you start the release with `bin/start_one ...` and which will dynamically set the hostname during startup, and this configuration allows you to reuse the script used to start the release between all of the releases (so you don't have to hardcode node names in the script). This also affords a lot of extra flexibility by letting you dynamically set the node cookie as well, and you have access to whatever tools you need to dynamically determine the node IP address (the example I provided above was how I did it for one app I was running under Kubernetes, but you may want to do it differently).

In general the `rel/config.exs` file shouldn't be used for runtime configuration, some things, like `set cookie` are there for convenience/legacy reasons, but I would be inclined to deprecate them as well and have people rely on mechanisms like I described above to deal with such things.

Thoughts?

**Comment by midas** [comment]
That makes sense.  Thanks for clarifying it for me.  Having the cookie there does lead ones thinking in this direction.  Take care Paul!

**Comment by midas** [comment]
One additional question regarding `vm.args` and releases.  Why is there a caution note about using the heartbeat feature?

**Comment by bitwalker** [comment]
@midas The caution is there because you shouldn't just turn it on blindly, you have to know how to setup `heart` properly, but there isn't necessarily a reason you _shouldn't_ use it if that's what you are wondering.

**Comment by bitwalker** [comment]
Unfortunately I don't think I'm going to be of much help with `heart` - the last time I played with it, all I needed to do was set up the various VM flags as defined in the Erlang manual for `heart` as desired, and Distillery made sure the environment variables it needed are exported (`HEART_COMMAND`, `HEART_OPTION`, and `HEART_BEAT_TIMEOUT`. It only works with the `start` task though, so you can't use it with `foreground` - or rather, you can, but Distillery doesn't help you with anything there.
