### ISSUE TITLE
RPC timeout

### ISSUE THREAD

**Issue by samphilipd** [bitwalker/distillery#413]
### Steps to reproduce

I'm trying to execute a command on a node with:

`/bin/my_app rpc MyMod myfun`

The function is expected to take a few minutes to execute, however it fails with this error:

`RPC to 'my_app@my.host' failed: timeout`

Is there some way to increase or disable this timeout in RPC calls?

**Comment by bitwalker** [comment]
In master, the timeout has been removed, but in 1.5.x, you'd need to modify the `release_utils.escript` to invoke the `rpc` function with no timeout. This may be worth backporting a fix for, but I probably won't have a chance to do that until I get 2.0 released.
