### ISSUE TITLE
`mix release.init` creates .gitignore file but the file is not under version control

### ISSUE THREAD

**Issue by zoltanmaric** [bitwalker/distillery#416]
Hi gang!

### Steps to reproduce

Run `mix release.init`

### Verbose Logs
`release.init` doesn't support the `--verbose` flag, so here's the log output without it:
```
mix release.init
==> utils
Compiling 1 file (.ex)

An example config file has been placed in rel/config.exs, review it,
make edits as needed/desired, and then run `mix release` to build the release
```

### Description of issue

When I run `mix release.init`, it creates a `.gitignore` file in the `rel/plugins` directory with the following contents:
```
*.*
!*.exs
```
This makes git ignore all files _except_ those with a `.exs` extension. Unfortunately, that also means that the `.gitignore` file itself is not under version control. Subsequently, the `.gitignore` file and the `plugins` directory will only exist on the machine where `mix release.init` was run, and non-`.exs` files will only be ignored on that machine.

This can be fixed by explicitly excluding `.gitignore` from the list of ignored files, e.g. like this:
```
*.*
!*.exs
!.gitignore

```
If you agree that the latter should be the expected behaviour, please let me know, and I'll be happy to submit a pull request (or you guys can fix it yourself if you think that's easier).

Cheers!

**Comment by zoltanmaric** [comment]
I see now that this is actually already fixed in `master`: https://github.com/zoltanmaric/distillery/commit/21c630b162aac3312ef3216905c806b861c4336e

but there haven't been any new releases since the fix. Are there currently any new releases planned?

**Comment by bitwalker** [comment]
Yes, I'm planning an upcoming release very soon, sometime in the next week I hope
