### ISSUE TITLE
Executables don't respect RELEASE_MUTABLE_DIR

### ISSUE THREAD

**Issue by rzane** [bitwalker/distillery#427]
### Steps to reproduce

1. Create an executable with `mix release --executable`
2. Run `RELEASE_MUTABLE_DIR=/tmp/foobar ./app.run foreground`
3. Note that `./tmp` will exist.
4. Note that `/tmp/foobar` will also exist.

### Error message

In my case, the CWD is a read-only filesystem. I need to be able to control where the archive gets extracted to or I get the following error.

```
mkdir:
  cannot create directory ‘./tmp’
  Read-only file system
```

### Description of issue

- What are the expected results?
I expected `RELEASE_MUTABLE_DIR` to control where the archive got extracted to,

- What OS, Erlang/Elixir versions are you seeing this issue on?
Linux, Erlang 20, Elixir 1.6

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
I simply ran `mix release.init` and didn't change anything.

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
The documentation is pretty clear that the archive will be extracted to `./tmp`. But, I think maybe this should be configurable.

**Comment by rzane** [comment]
A possible solution would be to modify https://github.com/bitwalker/distillery/blob/master/priv/templates/executable.eex like so:

```bash
if [ -z "$RELEASE_MUTABLE_DIR" ]; then
  __EXEC_TARGET_DIR="./tmp"
else
  __EXEC_TARGET_DIR="$RELEASE_MUTABLE_DIR/tmp"
fi
```

**Comment by bitwalker** [comment]
I think that's a decent solution, I'll make that part of the 2.0 release
