### ISSUE TITLE
[Suggestion] Exclude deps of `runtime: false` when check missing deps.

### ISSUE THREAD

**Issue by jung-hunsoo** [bitwalker/distillery#437]
(Since this is a feature suggestion, it's inadequate to fill the issue form.)

Whenever `MIX_ENV=prod mix release`, it shows some missing deps which are used on compilation.

They are included in `mix.exs` with `runtime: false` option; ex. `{:elixir_make, "~> 0.4", runtime: false}`.

But the Distillery seems to check whether the deps are included in the `:applications` of `rel/config.exs` regardless of `runtime: false`.

So I suggest to improve the `mix release` to check deps without `runtime: false`.

**Comment by bitwalker** [comment]
This is already the case today. What this generally means is that a transitive dependency shares the dependency you are being warned about, but does not declare it as `runtime: false`. The warning is effectively saying "if this dependency isn't present, things may not work as expected", and this would hold true even if you set `runtime: false`, but another dependency you do require at runtime does not, as that other dependency may in fact need it at runtime (more than likely in your example, they simply haven't added the `runtime: false` flag in their deps list). If you have such cases, you can use the `config :distillery, no_warn_missing: true` or `config :distillery, no_warn_missing: [:some, :apps]` to silence this warning.

**Comment by lasseebert** [comment]
I have had this same issue in a situation where it does not make sense to include the app that is warned about.

I have (among others) two deps:

* Credo (`only: [:dev, :test]`) that depends on `:jason`
* Tesla that depends on `:jason` with `optional: true`

When I build a release for prod environment I get the warning:

```

==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :jason

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.
```

Adding `:jason` to `extra_applications` obviously gives an error, since it does not exist in prod environment.
