### ISSUE TITLE
systemd setup?

### ISSUE THREAD

**Issue by omin** [bitwalker/distillery#45]
ubuntu is recommending systemd instead of upstart now so I was wondering how you would set it up. Does this seem right? https://gist.github.com/KozakIvan/fbc992fb1f864de1b907

**Comment by omin** [comment]
I'll close this since it's not exactly related but I you have any tips, let me know!

**Comment by bitwalker** [comment]
@omin That looks like it should work as a service definition to me, but without testing I couldn't tell you for sure. If you test it out or get a working configuration, could you follow up here so I can add it to the docs?

**Comment by omin** [comment]
@bitwalker will do!
