### ISSUE TITLE
Unable to start when config provider is used

### ISSUE THREAD

**Issue by imranismail** [bitwalker/distillery#456]
### Steps to reproduce

When the elixir provider is used, I'm unable to start console.

```
  set config_providers: [
    {Mix.Releases.Config.Providers.Elixir, ["${RELEASE_ROOT_DIR}/var/config.exs"]}
  ]
```

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

{"init terminating in do_boot",{noproc,{'Elixir.GenServer',call,['Elixir.Mix.State',{get,{'Elixir.Map',get,[env,dev]}},5000]}}}
init terminating in do_boot ({noproc,{Elixir.GenServer,call,[Elixir.Mix.State,{get,{_}},5000]}})

Crash dump is being written to: erl_crash.dump...done
```

  </details>
</summary>

### Description of issue

- What are the expected results?
IEX session should start as usual and `Mix.Releases.Config.Providers.Elixir` should be able to retrieve value from key
- What version of Distillery?
2.0.0-rc.6
- What OS, Erlang/Elixir versions are you seeing this issue on?
Elixir 1.7.1, MacOS 10.13.3

If you do not provide the above information and I need it to help troubleshoot, it may delay things significantly,
as I will have to ask you for all of these things anyway. Help me help you!

**Comment by bitwalker** [comment]
Hmmm, I think I know what's going on, probably happened because of another patch yesterday

**Comment by imranismail** [comment]
@bitwalker It seems the docs are wrong for the path to config.exs

https://hexdocs.pm/distillery/2.0.0-rc.6/handling_config.html#mix-config-provider

When I use this path:

```elixir
{Mix.Releases.Config.Providers.Elixir, ["${RELEASE_ROOT_DIR}/config.exs"]}
```

I get this error instead:

```shell
$ _build/dev/rel/platform/bin/platform console --verbose
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Code.LoadError',file=><<"/Users/imranismail/Projects/fave/platform/_build/dev/rel/platform/config.exs">>,message=><<"could not load /Users/imranismail/Projects/fave/platform/_build/dev/rel/platform/config.exs">>},[{'Elixir.Code',find_file,2,[{file,"lib/code.ex"},{line,1147}]},{'Elixir.Code',eval_file,2,[{file,"lib/code.ex"},{line,706}]},{'Elixir.Mix.Config','eval!',2,[{file,"lib/mix/config.ex"},{line,220}]},{'Elixir.Mix.Releases.Config.Providers.Elixir','eval!',2,[{file,"lib/mix/lib/releases/config/providers/elixir.ex"},{line,43}]},{'Elixir.Mix.Releases.Config.Providers.Elixir',init,1,[{file,"lib/mix/lib/releases/config/providers/elixir.ex"},{line,14}]},{'Elixir.Mix.Releases.Config.Provider','-init/1-fun-0-',2,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,96}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1925}]},{'Elixir.Mix.Releases.Config.Provider',init,1,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,88}]}]}}
init terminating in do_boot ({,[{Elixir.Code,find_file,2,[{_},{_}]},{Elixir.Code,eval_file,2,[{_},{_}]},{Elixir.Mix.Config,eval!,2,[{_},{_}]},{Elixir.Mix.Releases.Config.Providers.Elixir,eval!,2,[{_},

Crash dump is being written to: erl_crash.dump...done
```

**Comment by imranismail** [comment]
No mix env so it should be dev.. building locally on my machine.

**Comment by bitwalker** [comment]
No the path is right (Distillery places it in `var/config.exs`), the error you see there is because the provider raises an exception because the path doesn't exist

**Comment by imranismail** [comment]
You're right, the issue seems to be with my config. I'll have to debug line by line.

**Comment by bitwalker** [comment]
Are you calling any `Mix` functions in your config? It seems to be blowing up because of that, possibly `Mix.env`? I'm not sure why that would fail, but I could see that potentially being an issue outside of a Mix project

**Comment by imranismail** [comment]
Good catch!

That was the culprit

**Comment by bitwalker** [comment]
Yeah, that's unfortunately one of the caveats - we have Mix config files, and technically Mix is in the release, but it should be treated as functionally unavailable - Mix.Config works, but that's really about it.

**Comment by bitwalker** [comment]
One thing we could maybe do is replace the `Mix` module with a mock of sorts that stubs out some of the common calls with sane values

**Comment by bitwalker** [comment]
Not a huge fan of that, but if not doing that ends up being a problem, I'd consider it

**Comment by imranismail** [comment]
Chicken and egg problem. I'm not too sure what's the way forward for this one. But this could potentially be a huge PITA.

People use Mix functions all the time in their Mix config files.

**Comment by imranismail** [comment]
In my case I could get away with just using `System.get_env("MIX_ENV")`. But not sure what other cases I might be missing.

**Comment by bitwalker** [comment]
Well, I don't usually ever use Mix functions (other than `Mix.env`) in my config files, but that's generally because I design my configuration to be fairly minimal, and do most runtime configuration in the application code itself. Which is a direction I think we should be pushing people in anyway, but I digress.

Ultimately Mix isn't intended to be available outside of Mix projects, so if one wants to use `config.exs`, it will come with some caveats - José has been quite explicit about the fact that it will not be usable from releases, and I support the sentiment - most Mix functions are very much dependent on the entire project context, and none of that is available in the release, as all of the source code is gone.

The primary use case people have for wanting `config.exs` is to be able to use functions like `System.get_env/1` and friends to do some basic runtime configuration and transformation. For apps which have complex configs which are heavily dependent on the Mix project context, the only approach is to refactor those configs to be less dependent, and push more stuff into the application.
