### ISSUE TITLE
Some Missing Docs For Hooks

### ISSUE THREAD

**Issue by asummers** [bitwalker/distillery#467]
Hey Paul,

Spent a bit debugging some release issues so I figured I'd call these out to save someone some effort in future. We were trying to use the `PRE_START_HOOKS` functionality and were seemingly getting silent failures with it not running.  This was of course due to user error but the cause was missing a `.sh` extension on the hook. Might be worth calling out that only `.sh` (or presumably `.exe` on Windows?) files will be executed due to the check:

```
++ '[' -f '_build/dev/rel/project/releases/0.1.0/hooks/pre_start.d/[0-9a-zA-Z]*.sh' ']'
```

I don't think the single hook functionality had the same `.sh` name requirement, so it's at least worth calling out in the `CHANGELOG.md`.  Underscore and dot are legal first character too, at least in Unix, so that may be worth adding to the regex. 

After it failing to find any scripts there,  some sort of messaging that it tried to run hooks but was unable to find any in the provided directory might be helpful. 

`DEBUG_BOOT=true` was extremely helpful in debugging these, so that might deserve some love in the README, as well. 

Please let me know if I can answer questions, and I'll try to find some freetime to adjust the verbiage this weekend, but someone else is more than free to step in and grab em =)

Thanks,
Andrew

**Comment by bitwalker** [comment]
I'm fine with removing the `.sh` requirement, and adding `[._-]` to the pattern. After some consideration I don't think it's necessary to restrict the hooks to shell scripts, though that was the design - it should work with scripts of other types as well, though shell scripts will have far more capabilities due to the API that Distillery provides.
