### ISSUE TITLE
Task 'describe' doesn't seem to work.

### ISSUE THREAD

**Issue by jung-hunsoo** [bitwalker/distillery#468]
### Steps to reproduce

Call for task `describe` to see the release information.
`$ myapp describe`

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
==> Gathering release description..
** (FunctionClauseError) no function clause matching in Mix.Releases.Runtime.Control.start_data/1   

    The following arguments were given to Mix.Releases.Runtime.Control.start_data/1:

        # 1
        %{cookie: :"N%7X!`pknK=)J5@OOUKmmJRLj$O3H(%E,]ca_xI>Mv{%tnXmV*GT:]590eEhk@r]", name: :"nohogu_maint_@127.0.0.1", name_type: :longnames, peer: :"nohogu@127.0.0.1", sysconfig: "/home/centos/var/sys.config", vmargs: "/home/centos/var/vm.args"}

    Attempted function clauses (showing 1 out of 1):

        defp start_data(-%{release_root_dir: root_dir}-)

    (distillery) lib/mix/lib/releases/runtime/control.ex:246: Mix.Releases.Runtime.Control.start_data/1
    (distillery) lib/mix/lib/releases/runtime/control.ex:191: Mix.Releases.Runtime.Control.describe/2
    (distillery) lib/entry.ex:44: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/code.ex:192: Code.eval_string/3
```

  </details>
</summary>

### Description of issue

- What are the expected results?
> A detail information about current release.

- What version of Distillery?
> 2.0.0-rc.8

- What OS, Erlang/Elixir versions are you seeing this issue on?
> CentOS 7.3 / Erlang 21 / ERTS 10.0 / Elixir 1.6.6

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
```elixir
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"A_LONG_COOKIE"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"A_LONG_COOKIE"
end

release :nohogu do
  set version: current_version(:nohogu)
  set applications: [
    :runtime_tools
  ]
  set pre_start_hooks: "rel/hooks/pre_start.d"
end
```

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
> Haven't looked for within a doc.

- If this is a runtime configuration issue, please also provide your config file 
  (with any sensitive information stripped of course). This is almost
  always necessary to understand why some configuration may not be working.

If you do not provide the above information and I need it to help troubleshoot, it may delay things significantly,
as I will have to ask you for all of these things anyway. Help me help you!

**Comment by jung-hunsoo** [comment]
Actually the problem is quite simple.

https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/runtime/control.ex#L191 is calling `start_data/1` at https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/runtime/control.ex#L246, but it seems that `opts` have no key `:release_root_dir` I guess.

**Comment by bitwalker** [comment]
Thanks for reporting! It seems `OptionParser` expects switches with underscores to always be passed with dashes instead.

**Comment by sax** [comment]
There seems to be a different issue, after applying the fix. I'm using `e6c2bc29c440066640e636ec55cdd5495902900c`, and when I try to run `describe` I see the following error:

```
==> Gathering release description..
** (KeyError) key :release not found in: %{cookie: :"__cookie__", erl_opts: "", name: :"my_app_maint_@127.0.0.1", name_type: :longnames, peer: :"my_app@127.0.0.1", release_root_dir: "/Users/sax/workspace/my_app/_build/prod/rel/my_app", run_erl_env: "", sysconfig: "/Users/sax/workspace/my_app/_build/prod/rel/my_app/var/sys.config", version: "1.879.0", vmargs: "/Users/sax/workspace/my_app/_build/prod/rel/my_app/var/vm.args"}. Did you mean one of:

      * :release_root_dir

    (distillery) lib/mix/lib/releases/runtime/control.ex:193: Mix.Releases.Runtime.Control.describe/2
    (distillery) lib/entry.ex:44: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
```

https://github.com/bitwalker/distillery/blob/e6c2bc29c440066640e636ec55cdd5495902900c/lib/mix/lib/releases/runtime/control.ex?utf8=✓#L193

It does not appear as if `release` is an option of `describe`:
https://github.com/bitwalker/distillery/blob/e6c2bc29c440066640e636ec55cdd5495902900c/lib/mix/lib/releases/runtime/control.ex?utf8=✓#L120-L128

**Comment by sax** [comment]
This seems like it's still broken. I just reproduced it with Elixir 1.6.6 on OTP 20 and OTP 21, as well as Elixir 1.7.2 on OTP 21.

If I delete this line and create a new release, then describe works:
https://github.com/bitwalker/distillery/blob/e6c2bc29c440066640e636ec55cdd5495902900c/lib/mix/lib/releases/runtime/control.ex?utf8=%E2%9C%93#L193

**Comment by bitwalker** [comment]
I haven't pushed the fix for this yet, that tag is for my own tracking purposes

**Comment by sax** [comment]
Oh, awesome. Thank you!
