### ISSUE TITLE
Codepoint error when using hooks.

### ISSUE THREAD

**Issue by jung-hunsoo** [bitwalker/distillery#469]
### Steps to reproduce

Add `pre_start.sh` hook. Then run release as `foreground`.

It's strange that under dev env, the `pre_start.sh` is processed as expected. But after move the `.tar.gz` to EC2, unzip, and run `bin/nohogu foreground`, the `pre_start.sh` hook isn't called.

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
/home/ubuntu
" (column 34, codepoint U+000D)ed token: "
```

  </details>
</summary>

Following is a pre_start.sh
```sh
#!/bin/bash
echo "${RELEASE_ROOT_DIR}"
${RELEASE_ROOT_DIR}/bin/nohogu eval 'Nohogu.Tasks.ReleaseTasks.setup()'
```

### Description of issue

- What are the expected results?
> A pre_hook should be processed.

- What version of Distillery?
> 2.0.0-rc.8

- What OS, Erlang/Elixir versions are you seeing this issue on?
> CentOS 7.3, OTP 21, Elixir 1.6.6
> Ubuntu 18.04, OTP 21, Elixir 1.6.6

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

```elixir
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"A_LONG_COOKIE"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"A_LONG_COOKIE"
end

release :myapp do
  set version: current_version(:myapp)
  set applications: [
    :runtime_tools
  ]
  set pre_start_hooks: "rel/hooks/pre_start.d"
end
```

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
> I followed the doc, but have no luck.

- If this is a runtime configuration issue, please also provide your config file 
  (with any sensitive information stripped of course). This is almost
  always necessary to understand why some configuration may not be working.

If you do not provide the above information and I need it to help troubleshoot, it may delay things significantly, as I will have to ask you for all of these things anyway. Help me help you!

**Comment by jung-hunsoo** [comment]
The same error is produced when I used custom command for `migration`.

**Comment by jung-hunsoo** [comment]
Current EC2 is running on Ubuntu 18.04 with locale of
```
LANG=ko_KR.UTF-8
LANGUAGE=ko_KR:ko
LC_CTYPE="ko_KR.UTF-8"
LC_NUMERIC="ko_KR.UTF-8"
LC_TIME="ko_KR.UTF-8"
LC_COLLATE="ko_KR.UTF-8"
LC_MONETARY="ko_KR.UTF-8"
LC_MESSAGES="ko_KR.UTF-8"
LC_PAPER="ko_KR.UTF-8"
LC_NAME="ko_KR.UTF-8"
LC_ADDRESS="ko_KR.UTF-8"
LC_TELEPHONE="ko_KR.UTF-8"
LC_MEASUREMENT="ko_KR.UTF-8"
LC_IDENTIFICATION="ko_KR.UTF-8"
LC_ALL=ko_KR.UTF-8
```

`codepoint U+000D` is `CR`, but I can't figure out what's `column 34` and `ed token:`

After change the locale to `en_US` in the EC2, it still makes error. Now I'm discovering with another editor.

**Comment by jung-hunsoo** [comment]
Thanks bitwalker. The problem was in the atom editor. I removed the previous `pre_start.sh` then remake via `vm pre_start.sh`. Now the script is called.

And now I'm getting another;
`▸  Evaluation failed with: no match of right hand side value: {:error, {:already_loaded, :nohogu}}`.

This is raised when `:ok = Application.load(@app)` is called. There's a posted issue, so I should dig more.

Anyway this issue can be closed, since it's solved now.

**Comment by bitwalker** [comment]
Thanks for following up @jung-hunsoo, the other issue has been closed as of rc.10 :)
