### ISSUE TITLE
Invalid sectio number in the `applications` key description 

### ISSUE THREAD

**Issue by lessless** [bitwalker/distillery#482]
### Current behavior

I was looking through the documentation to figure out how to use `load` start type and found out that Walkthrough Guide https://hexdocs.pm/distillery/configuration.html references section 8.9 in Erlang documentation for more details.
Two things here:
- link references 7 section and probably correct section number should be 7.9
- there is nothing about "load" start type (as far as I can see)

### Expected behavior

It would be great to get more info on the `load` option and how it can be used :) 
Particularly scenario described in Getting Started is of the interest:
> loading, but not starting an application you need to dynamically configure before use at runtime

Thanks!

**Comment by bitwalker** [comment]
I've fixed the section reference and added a warning about using the `:load` start type. I do not plan on showing people how to use that start type, as I have come to find out that it is a bad idea to use it. You should always use `:included_applications` instead for such dependencies.
