### ISSUE TITLE
Spaces in cookie in vm.args makes things bad.

### ISSUE THREAD

**Issue by cdegroot** [bitwalker/distillery#504]
### Steps to reproduce

Use `-setcookie something with spaces` or `-setcookie "something with spaces"` and run
describe on the resulting release - only the first word is taken, due to

https://github.com/bitwalker/distillery/blob/master/priv/libexec/config.sh#L200

Two solutions:

1. Document this behaviour

2. Switch to something that won't just take the first word, like:

```
COOKIE="$(echo "$COOKIE_ARG" | sed 's/\s*-setcookie\s*//')"
```

The latter solution has its own problems because vm.args requires quoting:

```
-setcookie "my awesome spaced out cookie"
```

and the above sed construct does not remove these quotes. That's simple enough to add, of course, but then you get in the hot waters of escaped double quotes inside the cookie... As I don't know enough about what Erlang does with vm.args, I've elected to open an Issue instead of a PR and let smarter people than I decide.

**Comment by evadne** [comment]
Distillery now requires Bash, right

```
#!/usr/bin/env bash

VMARGS_PATH="$1"
VM_ARGS="$(cat "$VMARGS_PATH")"
COOKIE_REGEX="^-setcookie (.+)$"

echo $COOKIE_ARG
if [[ "$VM_ARGS" =~ $COOKIE_REGEX ]]; then
  echo "Cookie - ${BASH_REMATCH[1]} -"
fi
```

```
$ cat vmargs-1
-setcookie foobar

$ cat vmargs-2
-setcookie foo bar baz

./test.sh vmargs-1
Cookie - foobar -

$ ./test.sh vmargs-2
Cookie - foo bar baz -
```
