### ISSUE TITLE
Issue with 2.0.6 package, prevents use in Nerves projects

### ISSUE THREAD

**Issue by fhunleth** [bitwalker/distillery#508]
### Steps to reproduce

It appears that all Nerves projects are failing with Distillery release 2.0.6. Distillery 2.0.5 worked. At least our CI builds all started failing a few hours ago and the only change that I can find is the Distillery 2.0.6 release.

To reproduce (Elixir 1.7.3/OTP 21):

```
$ mix archive.install hex nerves_bootstrap
$ mix nerves.new testing
$ cd testing
$ export MIX_TARGET=rpi3
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  artificery 0.2.6
  distillery 2.0.6
  elixir_make 0.4.2
  nerves 1.3.0
  nerves_runtime 0.6.5
  nerves_system_br 1.4.1
  nerves_system_linter 0.3.0
  nerves_system_rpi3 1.3.0
  nerves_toolchain_arm_unknown_linux_gnueabihf 1.1.0
  nerves_toolchain_ctng 1.5.0
  shoehorn 0.4.0
  system_registry 0.8.0
<trimmed>
$ mix firmware
...
==> Release failed: function nil.path/0 is undefined
    nil.path()
    (distillery) lib/mix/lib/releases/models/release.ex:559: Mix.Releases.Release.do_print_discovered_apps/1
    (distillery) lib/mix/lib/releases/models/release.ex:476: Mix.Releases.Release.apps/1
    (distillery) lib/mix/lib/releases/models/release.ex:324: Mix.Releases.Release.apply_configuration/3
    (distillery) lib/mix/lib/releases/assembler.ex:28: Mix.Releases.Assembler.pre_assemble/1
    (distillery) lib/mix/lib/releases/assembler.ex:46: Mix.Releases.Assembler.assemble/1
    (distillery) lib/distillery/tasks/release.ex:111: Mix.Tasks.Release.do_release/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
```

This is what I have so far. I'm continuing to investigate off and on this evening, but figured that I'd post what I have in case this is easy to fix.

**Comment by fhunleth** [comment]
For anyone running into this issue with Nerves, a workaround is to add `{:distillery, "2.0.5",  override: true}` to your deps.

**Comment by bitwalker** [comment]
Thanks Frank! Sorry for the trouble :(. I'll get a fix out ASAP, looks like that code needs better tests.

**Comment by bitwalker** [comment]
@fhunleth I'm having trouble tracking down how that error is even possible, it shouldn't be given the way the code is written (it would raise a different error before it could hit that line, when mapping the list of `App` structs over `correct_app_path_and_vsn/2`) - could you try using the `2.0.6` tag instead and let me know if you see the issue there as well? I wonder if I had some local changes unstaged when I published to Hex - I'm usually careful about that, but I may have messed up :(

**Comment by bitwalker** [comment]
In the meantime, I'm going to retire 2.0.6

**Comment by fhunleth** [comment]
I get the same result by pulling Distillery using the `2.0.6` tag.

This is the first commit that fails for me: ab8d308abfbfcd07a5df5ede2bebbf05ae2e65a0.

**Comment by fhunleth** [comment]
Regarding 2.0.6 retirement, hex.pm still gives out 2.0.6 when updating deps. I get a warning now, but it doesn't prevent 2.0.6 from being used. The only option that I know of is to make a 2.0.7 release.

**Comment by bitwalker** [comment]
@fhunleth That's surprising, I thought it would prevent new fetches (i.e. if you hadn't already upgraded and had it in `mix.lock`). In any case, I've pushed 2.0.7 with the fix.

**Comment by bitwalker** [comment]
Note: I did test using your repro steps in the OP, looks good.

As an aside, apparently Dialyzer doesn't catch missing `else` branches resulting in a `nil` return violating the typespec :(

**Comment by fhunleth** [comment]
Re: hex.pm/retirement - yes, I thought that too and then found out otherwise.
Re: 2.0.7 - I did a quick test here and it looks good.

Thanks!
