### ISSUE TITLE
Hot upgrade fails on 2nd time.

### ISSUE THREAD

**Issue by ijunaid8989** [bitwalker/distillery#514]
### Steps to reproduce

https://github.com/bitwalker/distillery/issues/495

### Verbose Logs

<summary>
  <details>

```
After updating the version to the latest release.

The whole process is the same. first hot upgrade worked and on the 2nd one. I got this error.

```
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media upgrade 1.0.1-a42e5917
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
Node evercam_media@127.0.0.1 is not running!
```

```
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media ping
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media remote_console
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
Node evercam_media@127.0.0.1 is not running!
root@evercam-release-test:~#
```
Though the server is running

can you please guide what is the issue now?

PS: I tried everything 3 times from scratch but the same error is there.
```

  </details>
</summary>

### Description of issue

Distillery version 2.0.8 and the Hot upgrade fails on 2nd time it only works on first time on scratch deploy.

If I do restart the server by stopping and restarting and then do an upgrade then I have this error.

```
```
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media upgrade 1.0.1-a42e5917
Release evercam_media:1.0.1-a42e5917 not found, attempting to unpack releases/1.0.1-a42e5917/evercam_media.tar.gz
Unpacked '1.0.1-a42e5917' successfully!
Release evercam_media:1.0.1-a42e5917 is already unpacked, installing..
▸  Release handler check for evercam_media:1.0.1-a42e5917 failed with: {:no_matching_relup, '1.0.1-a42e5917', '1.0.1-a25483c8'}
```
This was the new version `1.0.1-a42e5917`
But the old one was `1.0.1-a9429b9` not ` '1.0.1-a25483c8` This was the most first one. on scratch release.
```

Please provide a solution on it.

**Comment by bitwalker** [comment]
Please do not open duplicate issues. I'm aware of the ongoing discussion in the other thread. This issue is missing requested information as well, if you are going to open new issues, you need to provide all of the requested information.
