### ISSUE TITLE
Distillery don't take new application version on upgrade dynamic versions

### ISSUE THREAD

**Issue by ijunaid8989** [bitwalker/distillery#517]
### Steps to reproduce

I am doing application versions as
```
  def project do
    [app: :evercam_media,
     version: "1.0.#{versions()}",
     elixir: "~> 1.7",
     elixirc_paths: elixirc_paths(Mix.env),
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     compilers: [:phoenix] ++ Mix.compilers,
     aliases: aliases(),
     deps: deps()]
  end

  defp versions do
    {description, 0} = System.cmd("git", ~w[describe --tags])
    description
    |> String.split("-", trim: true)
    |> Enum.take(2)
    |> List.last
    |> IO.inspect
  end
```
And I ran first command as mix release, it gave me this 
```
==> Assembling release..
==> Building release evercam_media:1.0.509 using environment prod
==> Including ERTS 10.0 from /home/ijunaidfarooq/.asdf/installs/erlang/21.0/lib/erlang/erts-10.0
==> Packaging release..
```

I made a few changes and commit, after that, I again did an upgrade
```
==> Assembling release..
==> Building release evercam_media:1.0.509 using environment prod
==> Relup successfully created
==> Including ERTS 10.0 from /home/ijunaidfarooq/.asdf/installs/erlang/21.0/lib/erlang/erts-10.0
==> Packaging release..
```
Even on the start of release IO.inspect showed the new version number is `510` but `mix release --upgrade` didnt take the new version in creating a release but created Relup file though.

```
{"1.0.509",
 [{"1.0.509",[],[point_of_no_return]}],
 [{"1.0.509",[],[point_of_no_return]}]}.
```

But when I do this in mix.exs
```elixir
  def project do
    [app: :evercam_media,
     version: "1.0.1" #then change it to 1.0.2 and 1.0.3 and 1.0.4,
     elixir: "~> 1.7",
      ....
```
This works fine and create new releases with `--upgrade`

### Description of issue

- What are the expected results?
  - Distillery mix release --upgrade` should use new version of application
- What version of Distillery?
  - 2.0.9
- What OS, Erlang/Elixir versions are you seeing this issue on?
   - 21.0 OTP , Elixir 1.7.1

my rel/conf.exs
```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/config/distillery.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"E5D0Yce]tvuW5?qW{!X|]1Zlmo$TmLADeze.Yxdt=ny;)%4Gdt<tUeB0ty<*t^7r"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"{deQw.|9L?hGHdeymL2^`&<Q62Nd9RJXh8F~Ks,TU(>j@tQLA?rZftlna&_v]?Fy"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :evercam_media do
  set version: current_version(:evercam_media)
  set applications: [
    :runtime_tools
  ]
end
```

I also tried dynamic versions like 
```elixir
{epoch, _} = System.cmd("git", ~w|log -1 --date=raw --format=%cd|)
[sec, tz] =
  epoch
  |> String.split(~r/\s+/, trim: true)
  |> Enum.map(&String.to_integer/1)
#⇒ [1527769224, 200]
sec + tz * 36 # * 60 * 60 / 100
#⇒ 1527776424
```

But still it takes 2 versions right. but then stopped taking new version and use the last created version and again create the same release.

**Comment by bitwalker** [comment]
This isn't a bug in Distillery - the issue is that Mix is compiling the module, and because the module isn't modified on disk, the result of that compilation is cached (namely the `.app` file which contains the version).

I had thought Mix used to always evaluate `mix.exs`, but after some experimentation, that no longer appears to be the case. You could switch to setting the version in `rel/config.exs` dynamically instead, e.g.:

```elixir
release :myapp do
  vsn = String.trim(elem(System.cmd("git", ["rev-parse", "--short", "HEAD"]), 0), "\n")
  set version: current_version(:myapp) <> "-#{vsn}"
end
```

This will append the current git hash to the version of your app when building the release. That isn't ideal if you want the git hash in the actual version of the app for other reasons, but works for building the release.

The other approach is to `touch` the `mix.exs` file each time you want it to be reevaluated. If you are automating builds already, this would ensure the new version gets picked up.

As far as what the current recommendations are for dynamically setting versions, I'm not sure, I'm interested in figuring that out myself though.

**Comment by ijunaid8989** [comment]
@bitwalker Thanks a lot.

I would like to say one thing, I have been to many repositories for issues, you are one of the best Author who always uses clear the explanation and satisfies the other end user.  Highly Appreciate that.

**Comment by bitwalker** [comment]
Thanks for the kind words, it means a lot :)
