### ISSUE TITLE
GenServer's code_change got invoked again even if vsn is fixed to last version in successive hot code upgrade?

### ISSUE THREAD

**Issue by kenspirit** [bitwalker/distillery#523]
The second upgrade release cannot be installed successfully.  From the error log below, seems the code_change function is invoked again and processed the state incorrectly.

### Steps to reproduce

I am following the examples and steps in book "Programming Elixir >= 1.6" chapter 20 OTP.Applications.

1. On commit [one](https://github.com/kenspirit/programming-elixir-exercises/commit/3df90c00690fe72894a8c82034d0a3a381a536cd), I have prepared the application as 0.2.0 version
2. On commit [two](https://github.com/kenspirit/programming-elixir-exercises/commit/f3801929d9ff2f38615a21438e5177167c82a527), the state in `server.ex` has been updated and need to run code_change.  I can hot upgrade the code to 0.3.0 successfully.
3. After above two steps, if I simply change the return text in `next_number` function in `server.ex` and upgrade the version to 0.3.1 for example, leaving the code_change function in step 2 untouched, the hot upgrade will failed with below error.

After step 2, I did run new function `Sequence.Server.next_number() and Sequence.Server.increment_number(2)` several times to make sure it takes effect and the state is updated to new format.

The question is that why the `code_change("0")` with version marked as last version can still be triggered in the second upgrade?

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
▸  Release handler failed to install: {:code_change_failed, #PID<10063.770.0>, Sequence.Server, "1", {:EXIT, {:function_clause, [{Sequence.Server, :code_change, ["1", %{__struct__: Sequence.Server.State, current_number: 8, delta: 2}, []], [file: 'lib/sequence/server.ex', line: 44]}, {:gen_server, :system_code_change, 4, [file: 'gen_server.erl', line: 794]}, {:sys, :do_change_code, 5, [file: 'sys.erl', line: 573]}, {:sys, :do_cmd, 6, [file: 'sys.erl', line: 465]}, {:sys, :handle_system_msg, 8, [file: 'sys.erl', line: 365]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}
```

  </details>
</summary>

### Description of issue

- What are the expected results?    hot code upgrade should be successful
- What version of Distillery?   2.0.9
- What OS, Erlang/Elixir versions are you seeing this issue on?    Mac 10.13.6, Elixir 1.7.2

**Comment by bitwalker** [comment]
Yes, this is expected, the `code_change` handler is just a regular function, so you are pattern matching on only one possible version - you need a clause that can handle upgrading to and from any version. It is acceptable to have it fail like this if you only support upgrades/downgrades from specific versions, but if you want to handle the case you've outlined, you need a clause that can handle other versions.
