### ISSUE TITLE
Mix.Dep.loaded_by_name/2 is undefined or private

### ISSUE THREAD

**Issue by ddefrenne** [bitwalker/distillery#526]
### Steps to reproduce

- Elixir 1.7.2 umbrella-app
- Distillery 1.5.4
- `$ mix release --env=prod`

### Verbose Logs
<summary>
  <details>

==> Loading configuration..
==> Assembling release..
==> Building release sreint:0.1.0 using environment prod
==> Release failed: function Mix.Dep.loaded_by_name/2 is undefined or private
    (mix) Mix.Dep.loaded_by_name([:elixir], [])
    (distillery) lib/mix/lib/releases/models/app.ex:83: Mix.Releases.App.get_dependencies/1
    (distillery) lib/mix/lib/releases/models/app.ex:55: Mix.Releases.App.do_new/2
    (distillery) lib/mix/lib/releases/utils.ex:282: anonymous fn/2 in Mix.Releases.Utils.get_apps/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/utils.ex:263: Mix.Releases.Utils.get_apps/1
    (distillery) lib/mix/lib/releases/models/release.ex:166: Mix.Releases.Release.apply_configuration/3
    (distillery) lib/mix/lib/releases/assembler.ex:28: Mix.Releases.Assembler.assemble/1

ERROR: Job failed: exit code 1

  </details>
</summary>

### Description of issue

- What are the expected results?
  It used to build correctly, now it doesn't anymore after upgrading to Elixir 1.7.2 (from 1.6.6).
- What version of Distillery?
  1.5.4
- What OS, Erlang/Elixir versions are you seeing this issue on?
  Docker image for Elixir 1.7.2 with Erlang OTP 21 on Debian
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

```
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :""
  set vm_args: "rel/vm.args.prod"
end

release :sreint do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    monitoring: :permanent
  ]
end
```

**Comment by bitwalker** [comment]
Fixed in 1.5.5
