### ISSUE TITLE
erl: not found on app start

### ISSUE THREAD

**Issue by schurig** [bitwalker/distillery#53]
### Steps to reproduce

run `./bin/my_app console`

### Verbose Logs

```
/home/apps/edeliver/my_app/releases/1.0.3602+3602-b84b0be-develop/my_app.sh: 105: /home/apps/edeliver/my_app/releases/1.0.3602+3602-b84b0be-develop/my_app.sh: erl: not found
```

### Description of issue

- the app should start
(it used to work yesterday)

- Building server: `elixir 1.3.2` and `Erlang/OTP 18`
- on the app server is no erl nor elixir installed. Only nginx and the app are on there

```elixir
# rel/config.exs
use Mix.Releases.Config,
    default_release: :default,
    default_environment: :dev

environment :dev do
  set dev_mode: true
  set include_erts: false
end

environment :beta do
  set include_erts: true
  set include_src: false
end

environment :prod do
  set include_erts: true
  set include_src: false
end

release :my_app do
  set version: current_version(:my_app)
end
```

Notice: I used [exrm](https://github.com/bitwalker/exrm) before and switched to distillery. Also I use [edeliver](https://github.com/boldpoker/edeliver) for deployment.

Is there anything I didn't think of? I couldn't identify any difference in our app so I figured out that it might be because we switched to distillery.

**Comment by bitwalker** [comment]
This may be related to a fix I just merged. Could you try with master and let me know?

**Comment by schurig** [comment]
Can't test it due to dep error [Install distillery from github fails](https://github.com/boldpoker/edeliver/issues/149)

**Comment by schurig** [comment]
@bitwalker seems to work 👍

**Comment by bitwalker** [comment]
Awesome, I'll get a release pushed today.

**Comment by bitwalker** [comment]
Just pushed 0.9.7, so I'm closing this for now
