### ISSUE TITLE
Unexpected behaviors after upgrade to version 2.0

### ISSUE THREAD

**Issue by samidarko** [bitwalker/distillery#535]
We upgraded from distillery 1.5.5 to 2.0.9 but now we have the following intermittent problems:

1) when we are deploying we are rotating between 2 directories `current_version` and `previous_version`. 
- `previous_version` is deleted
- `current_version` is renamed `previous_version`
- the new build is copied into a new directory named `current_version`

The issue happens when we are doing stopping `previous_version` and starting `current_version`.
`previous_version` is returning "ok" with exit code 0 but `current_version` is not starting because socket is still not closed by `previous_version`. If we add a *sleep 3* command then it works.

Shouldn't `previous_version` return "ok" only when all resources are freed? 

2) We had another problem at runtime. The application was still running. End-points up and running but doing a `ping` operation was returning:

```bash
> bin/backend ping
▸  Received 'pang' from backend@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
```

### Steps to reproduce

We are still looking for a way to constantly reproduce but it seems to be intermittent.

### Description of issue

- What version of Distillery? 2.0.9
- What OS, Erlang/Elixir versions are you seeing this issue on? 
Erlang/OTP 20 [erts-9.2] + Elixir 1.6.0 running on AWS Linux AMI

- rel/config.exs (we use the default)
```elixir
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"J~q1`n?B@qX,]PUlHe[<sSy[mr|31|ZKx7LqMGX.p{ee,_5{!Nj]sPyA6~cec[_D"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"6SiTyB~m7;bzr*t5.ykX%=40N,qOBuM>a]8<~4A2}=F={.51GA{fVtOTMvRmO}:i"
end

release :backend do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    tsc: :permanent,
    tsc_web: :permanent
  ]
end

```

Thanks by advance for your help

**Comment by bitwalker** [comment]
Should be fixed in master/2.0.10
