### ISSUE TITLE
PIDFILE broken in 2.0.9

### ISSUE THREAD

**Issue by lasseebert** [bitwalker/distillery#536]
### Steps to reproduce

* Use distillery 2.0.9
* Build a release
* Start release with `PIDFILE=/path/to/pidfile _build/dev/rel/myapp/bin/myapp console`

The command then just hangs an nothing is outputted.

### Verbose Logs

Even with `--verbose` nothing is outputted

### Description of issue

- Expected that the app would start a console
- Version 2.0.9 is affected. This works in 2.0.8
- Run on Ubuntu 18.04

I have tried looking in the commit history, but I can't find where this changed.

My config is (I think only difference from default config is that I don't include ERTS):

```elixir
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/config/distillery.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set cookie: :"SECRET"
end

environment :prod do
  set cookie: :"SECRET"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :balrog do
  set version: current_version(:balrog)
  set include_erts: false
  set include_src: false
end
```

**Comment by lasseebert** [comment]
I forgot to mention that if the 2.0.9 release is run without `PIDFILE` it works as expected (but then I don't have a pidfile of course).

**Comment by OvermindDL1** [comment]
As a work-around if needed to use with 2.0.9 my [PidFile](https://hex.pm/packages/pid_file) library should suffice until this is fixed.

**Comment by bitwalker** [comment]
Can you try master? There are some fixes there that have not yet been released

**Comment by lasseebert** [comment]
@bitwalker: Same issue in master

**Comment by bitwalker** [comment]
Thanks @lasseebert, I'll take a look here shortly!

**Comment by bitwalker** [comment]
This should be fixed in master/2.0.10

**Comment by lasseebert** [comment]
@bitwalker: Thanks :)
Can confirm that my issue is gone in master :tada:

**Comment by bitwalker** [comment]
Awesome :) I'll be pushing 2.0.10 shortly
