### ISSUE TITLE
You tried to invoke MyApp.ReleaseTasks.migrate/1 with 0 arguments ([]) but the function has a different arity!

### ISSUE THREAD

**Issue by chenxsan** [bitwalker/distillery#550]
### Steps to reproduce

I'm doing migration according to https://hexdocs.pm/distillery/guides/running_migrations.html.

We just defined `migrate/1` in `MyApp.ReleaseTasks` module:

```elixir
def migrate(_argv) do
    start_services()

    run_migrations()

    stop_services()
end
```
And a custom command in `rel/commands/migrate.sh`:

```sh
#!/bin/sh

release_ctl eval --mfa "MyApp.ReleaseTasks.migrate/1" -- "$@"
```
So `migrate` should be called with one argument.

But the document here https://hexdocs.pm/distillery/guides/running_migrations.html#tying-it-all-together said:

> Now, once you’ve deployed your application, you can run migrations/seeds with bin/myapp migrate and bin/myapp seed

This part is wrong, you should run migration with `bin/myapp migrate a`, `a` here is only to fix this error:

> You tried to invoke MyApp.ReleaseTasks.migrate/1 with 0 arguments ([]),
> but the function has a different arity!

I'm wondering why the documentation define `migrate/1` instead of `migrate/0` in module `MyApp.ReleaseTasks`.

**Comment by bitwalker** [comment]
You are missing the `--argv` flag, which must be used in conjunction with `--mfa` when trying to build a Mix task style custom command. It seems the docs are missing that as well, so I'll get that updated. Thanks for reporting!
