### ISSUE TITLE
Different config parameters for different environments

### ISSUE THREAD

**Issue by gaynetdinov** [bitwalker/distillery#57]
Hello.

I tried distillery (with edeliver) and it worked great! 👍 

And I've got one question, I couldn't find an answer in the docs. 

Say, I have `demo` env and `staging` env. For example in `demo` env an app should send an auth request to `auth-demo.mysite.com` and in `staging` it should send an auth request to `auth-staging.mysite.com`. 

Is there a place where I can put these two URLs(somehow special, under different namespaces or whatever) and distillery would automagically figure out which URL should be used when I deploy the same built release to `demo` or `staging` environment. Ideally, this magic place should be under version control :)
 
Thanks!

**Comment by bitwalker** [comment]
You need to leverage Mix's environments for this. So in your case, you would have multiple config files under `config`, using something like `import_config "#{Mix.env}.config.exs"` in `config/config.exs`. Then build your releases with `MIX_ENV=demo mix do compile, release --env=demo` or `MIX_ENV=staging mix do compile, release --env=staging`. If your release env and mix env will always be the same, you could do something like this in your `rel/config.exs` to save having to pass the `--env` parameter.

```elixir
use Mix.Releases.Config,
  default_environment: Mix.env,

...snip...
```

**Comment by gaynetdinov** [comment]
Thanks for the explanation! 
Do I understand correctly that in that case I'd need to build a release per environment?

**Comment by bitwalker** [comment]
@gaynetdinov yep that's correct, you could also generate your own `sys.config` and/or `vm.args` for each environment and manually apply them over the top of a single release (i.e. MIX_ENV=prod), either one is equally fine.
