### ISSUE TITLE
include_erts: false doesn't solve the cross platform issue

### ISSUE THREAD

**Issue by omin** [bitwalker/distillery#58]
![image](https://cloud.githubusercontent.com/assets/3143154/17885341/ccff1f88-68d1-11e6-8125-8bc85c0f1dfc.png)

I built the release on a mac without including erlang and the release still failed to run on the production environment. I have other (simple) pheonix application running so it's not an erlang problem.

If what micmus said is true, we should mention that in the guide.

**Comment by bAmpT** [comment]
I just ran in the same problem while cross-compiling with the erts lib from the machine I want to deploy to.

reason: {on_load_function_failed,'Elixir.Comeonin.Bcrypt'}

**Comment by bitwalker** [comment]
Yeah, if you are using NIFs you definitely have to have the cross-compilation toolchain for them as well. In the case of NIFs, it's far easier to build your release on the same OS/architecture, with Docker or Vagrant or whatever. I'll make a note of this in the docs.
