### ISSUE TITLE
Do not overwrite existing vm.args file on release.init

### ISSUE THREAD

**Issue by mobileoverlord** [bitwalker/distillery#585]
### Steps to reproduce
```
mix nerves.new test_app
...
Fetch and install dependencies? [Yn] Y
```

rel/vm.args file that nerves needs is overwritten by the one from distillery

### Description of issue

The Nerves new project generator includes a custom release config.exs and a customized vm.args file. When `mix release.init` is called, the vm.args file is overwritten by the version Nerves needs. This is causing all new projects to be generated to fail to boot Nerves devices. Distillery should not overwrite existing files.

**Comment by bitwalker** [comment]
Sorry about that, this came in via PR, usually I'm careful about this kind of thing :( - a new release has been pushed to Hex with the fix.
