### ISSUE TITLE
Slow command on server when using Kernel sync_nodes_optional

### ISSUE THREAD

**Issue by nulian** [bitwalker/distillery#590]
When using sync_nodes_optional with the new distillery 2.0 commands on the server like remote_console take a very long time.

```
config :kernel,
  sync_nodes_optional: [
    :"example@example.com"
  ],
  sync_nodes_timeout: 10000
```
This is caused by all the internal commands in the script like ping and net_kernel get_net_ticktime now including sys.config with the sync_nodes_optional in it. While the old tooling skipped including that so the commands weren't slow down by that.

Is there a work around for this so server commands are no longer extremely slow?

**Comment by bitwalker** [comment]
This is addressed as recently as 2.0.13
