### ISSUE TITLE
Migration Module code example isn't rendering on hexdocs - 2.0

### ISSUE THREAD

**Issue by fozcodes** [bitwalker/distillery#596]
### Steps to reproduce

https://hexdocs.pm/distillery/guides/running_migrations.html#migration-module

The code block for the _Migration Module_ isn't rendering on hexdocs.

<img width="1248" alt="screen shot 2018-11-29 at 9 11 51 pm" src="https://user-images.githubusercontent.com/1767848/49264233-7b04b300-f41b-11e8-9c6f-9a9ee8bd7a14.png">

### Description of issue

- What are the expected results?
  - Should see the code for the module as you do in the Markdown file: https://github.com/bitwalker/distillery/blob/master/docs/guides/running_migrations.md#migration-module
- What version of Distillery?
  - 2.x

**Comment by chenxsan** [comment]
There's already a pull request here https://github.com/bitwalker/distillery/pull/595 :)
