### ISSUE TITLE
`mix release --erl` is undefined

### ISSUE THREAD

**Issue by isaacsanders** [bitwalker/distillery#598]
### Steps to reproduce

- create a project using Distillery version 2.0.12
- run `mix release --erl="-sname foo"`

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
 $ mix release --erl="-sname foo" --verbose
** (FunctionClauseError) no function clause matching in Mix.Tasks.Release.do_parse_args/2

    The following arguments were given to Mix.Tasks.Release.do_parse_args/2:

        # 1
        [erl: "-sname foo", verbose: true]

        # 2
        %{executable: [enabled: false, transient: false], is_upgrade: false, no_tar: false, selected_environment: :default, selected_release: :default, upgrade_from: :latest, verbosity: :normal}

    Attempted function clauses (showing 10 out of 16):

        defp do_parse_args([], acc)
        defp do_parse_args([{:verbose, _} | rest], acc)
        defp do_parse_args([{:quiet, _} | rest], acc)
        defp do_parse_args([{:silent, _} | rest], acc)
        defp do_parse_args([{:profile, profile} | rest], acc)
        defp do_parse_args([{:name, name} | rest], acc)
        defp do_parse_args([{:env, name} | rest], acc)
        defp do_parse_args([{:no_warn_missing, _} | rest], acc)
        defp do_parse_args([{:no_tar, _} | rest], acc)
        defp do_parse_args([{:executable, e} | _rest], %{is_upgrade: true}) when e != false

    lib/distillery/tasks/release.ex:260: Mix.Tasks.Release.do_parse_args/2
    lib/distillery/tasks/release.ex:82: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

  </details>
</summary>

### Description of issue

- What are the expected results? __The documented behavior of the `--erl` flag.__
- What version of Distillery? __`2.0.12`__
- What OS, Erlang/Elixir versions are you seeing this issue on? __Mac OS X High Sierra, Elixir 1.6.5, Erlang 20.3.7__
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :) __Not the problem this time, the code is missing a function definition.__
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented. __https://github.com/bitwalker/distillery/blob/master/lib/distillery/tasks/release.ex#L15__

**Comment by trajakovic** [comment]
What's alternative in distillery 2.x for 0.5 `--erl` switch?
