### ISSUE TITLE
mix release --env flag problem

### ISSUE THREAD

**Issue by typicalpixel** [bitwalker/distillery#6]
To reproduce.. 

`mix phoenix.new sample_app`
`mix.exs << {:distillery, "~> 0.6"}`
`mix deps.get`
`mix release.init`

Add staging environment into `rel/config.exs`
```
environment :staging do
  set dev_mode: false
  set include_erts: true
end
```
```
$ mix release --env=staging
==> Assembling release..
==> Failed to build release:
    :no_environments
```

If you change `default_environment: :default` to `default_environment: :staging`, it will work.

**Comment by bitwalker** [comment]
I'd just go ahead and use master for now rather than the hex package ;). Once we've worked out the kinks I'll push a new release. Anyway, this issue is now fixed.

**Comment by typicalpixel** [comment]
Updated to master.

```
$ mix release --env=staging
** (ArgumentError) argument error
    :erlang.binary_to_atom(:default, :utf8)
    lib/distillery/tasks/release.ex:145: Mix.Tasks.Release.parse_args/1
    lib/distillery/tasks/release.ex:51: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

`mix release` is the same result.
