### ISSUE TITLE
Starting the same service twice on the same machine

### ISSUE THREAD

**Issue by farao** [bitwalker/distillery#60]
Sorry in advance for this issue, there's a high chance I just didn't get how to deal with distillery properly.

I want to start a release twice on a machine - the only difference being the network port that the service listens on (which is given as an environment variable). Naively, I thought just copying the release in two separate directories (one for the "testing" service and one for production) would be enough since each of them has its own tmp directory. But that wasn't really the case, I could start one of them but the other didn't start. Then I tried having one with dev and one with prod environment in rel/config.exs but that didn't work either.

What's the right way to do this? Maybe it would be worth having a section in "Common Problems" of the documentation for this? I guess I'm not the only one having a testing/production setup and thus running the same project twice on a machine.

Thanks in advance!

**Comment by bitwalker** [comment]
You just need to tweak the `vm.args` file in the release and change the node name (the first part of the `-name` parameter). I can add this to the docs as a troubleshooting step :)

**Comment by farao** [comment]
Alright, thanks! At least it wasn't embarassingly obvious :-) I think it would help adding it to the documentation!
