### ISSUE TITLE
can't loop over require_live_node in command script 

### ISSUE THREAD

**Issue by MagiCrazy** [bitwalker/distillery#650]
### Steps to reproduce

here's the `start_app.sh` file:

```shell
bin/my_app start
...
bin/my_app connect_mnesia
```

Here's the `rel/commands/connect_mnesia.sh` file:

```shell
#!/bin/sh
set -o posix
set -e
while true; do
        require_live_node
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 0 ]; then
                break
        fi
done
release_remote_ctl rpc --mfa "Core.ReleaseTasks.connect_mnesia/0"
success
```

### Verbose Logs

```
$ start_app.sh
▸  Received 'pang' from my_app@172.16.12.34!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
Node my_app@172.16.12.34 is not running!
```

### Description of issue

We want to launch a command once after the *first* start of the app. So we don't use boot hooks, just a deploy script that starts our application, then launch a custom command.

As we investigated the issue, we found that the function `require_live_node` fails using a [fail function](https://github.com/bitwalker/distillery/blob/088f4b1d360bcbcbe088da40175d37eba5908803/priv/libexec/helpers.sh#L9) and that `fail function` [throws an `exit 1`](https://github.com/bitwalker/distillery/blob/088f4b1d360bcbcbe088da40175d37eba5908803/priv/libexec/logger.sh#L33). We think that `require_live_node` could throw back a `return 1` instead of an `exit 1`, in order to be more easily manageable in command scripts.
Or maybe, we missed something and done it the wrong way, but we can't figure it out!

If our solution is accepted, we could propose a PR 💪

elixir version: 1.7.2
distillery version: 2.0.12

**Comment by bitwalker** [comment]
You should just use `release_ctl ping --name="$NAME" --cookie="$COOKIE"`, which will return non-zero if the ping fails. `require_live_node` is designed specifically to _require_ a thing, i.e. fail if the condition is not met. You can take a look at the `ping.sh` script under `priv/libexec/commands` for an example.

**Comment by MagiCrazy** [comment]
OK, so we missed something :)
Thanks a lot for your time and your work!
