### ISSUE TITLE
Confusing/incorrect docs around --warnings-as-errors flag

### ISSUE THREAD

**Issue by bglusman** [bitwalker/distillery#655]
Based on comments in docs code at https://github.com/bitwalker/distillery/blob/master/lib/distillery/tasks/release.ex
I would expect `mix release --warnings-as-errors` to fail when the release  contains warnings, but this was not the case in a test with an intentionally introduced warning.

Discussion on  Slack suggested simply using `mix compile --force --warnings-as-errors && mix release` which works fine, but if this flag isn't supported by distillery for release task, ideally docs should be updated, unless I'm misunderstanding them of course.

**Comment by bitwalker** [comment]
Ah, yes `--warnings-as-errors` is a different flag for the `release` task which treats _release_ warnings as errors, not compilation warnings as errors. For that, the command you've used as a workaround is the correct solution: specifically, run `compile` first, _then_ run `release`.

I will update the docs to make note of this.
