### ISSUE TITLE
Elixir 1.3 really required?

### ISSUE THREAD

**Issue by matehat** [bitwalker/distillery#66]
I just wanted to make sure that Elixir 1.3 was really required for distillery (awesome talk yesterday @bitwalker!). We wanted to use this in our company, and moving to Elixir 1.3 is _definitely_ on the roadmap, but at this time upgrading elixir would have much more side effects in our project (some erlang projects not compiling on Erlang 19) than just switching from exrm to distillery, and we can't do that in the short term.

**Comment by bitwalker** [comment]
It's not strictly required for the hex package, but the project itself uses some 1.3 features in the test suite, and could depend on 1.3 features in the library itself at any time. You shouldn't have to upgrade to Erlang 19 to use Elixir 1.3 though, at work we still run Erlang 18.3, and Elixir 1.3.2. That said, if there are other reasons, I can certainly understand.

I could probably drop the requirement down to Elixir 1.2, but I unfortunately don't have time to test on 1.2, which is the major reason why I am hesitant to do so. If you are planning to migrate to 1.3 soonish, the easiest thing to do is to temporarily fork Distillery and change the Elixir requirement, then switch to the hex package when you have upgraded to 1.3

Thanks for the kind words about my talk by the way, I never can tell how it goes, and it's always great to hear from others that it wasn't useless ;)
