### ISSUE TITLE
v2.0.13: Can not run eval right after building a release

### ISSUE THREAD

**Issue by jesseshieh** [bitwalker/distillery#662]
### Steps to reproduce

```
# install distillery 2.0.13
mix release.init
rm -rf _build/
MIX_ENV=prod mix release --env=prod
_build/prod/rel/gigalixir_getting_started/bin/gigalixir_getting_started eval 'IO.inspect 123+123'
```

Produces the error
```
Unable to load vm.args and NAME is not exported, unable to configure node!
```

In 2.0.12, it works fine.

I think this is because the vm.args file below does not exist yet.
```
_build/prod/rel/gigalixir_getting_started/var/vm.args
```

After running 
```
_build/prod/rel/gigalixir_getting_started/bin/gigalixir_getting_started describe
```
the eval command above works fine. I'm guessing this is because the describe command creates the vm.args file.

Here is the repo I used to reproduce, which just uses the default generated rel/config.exs
https://github.com/gigalixir/gigalixir-getting-started/blob/js/cookie/rel/config.exs

**Comment by ggcampinho** [comment]
I have the same issue running the `help`/`console` commands, that are fixed after running `foreground`

**Comment by bitwalker** [comment]
I'll take a look ASAP

**Comment by bitwalker** [comment]
@jesseshieh @ggcampinho Can you all verify the fix I pushed to master? I'm pretty sure the problem is that `partial_config_release` always assumed that the main app had been run at least once, and it just needs to check that assumption before proceeding without generating configs.

**Comment by geofflane** [comment]
Seeing similar behavior on 2.0.13 with a custom migration command that we run on CI in our remote environment. Downgrading to 2.0.12 worked.

**Comment by djantea** [comment]
Hi,
@bitwalker, im my case the problem was solved wit the version from master.
Thank you.

**Comment by jesseshieh** [comment]
@bitwalker Fix verified! Thanks for such a quick turnaround!

**Comment by bitwalker** [comment]
Thanks @djantea and @jesseshieh! New release published (2.0.14)

**Comment by ggcampinho** [comment]
A little bit late, but confirming that it fixed for me as well :)

**Comment by DavidVII** [comment]
Late here too, but thanks for the quick turnaround on this 🙌
