### ISSUE TITLE
Conflicts with Elixir 1.9 release tooling

### ISSUE THREAD

**Issue by jesseshieh** [bitwalker/distillery#665]
Thanks again for making distillery!

Elixir 1.9 is going to include a `mix release` command which might conflict with distillery's. My understanding is that it will actually supercede distillery's making it impossible to use distillery's `mix release`.

Does it make sense to add an alias such as `mix distillery.release`?

This is sorta related to #642, but this issue isn't discussed there.

**Comment by bitwalker** [comment]
I actually have a branch for that already, elixir19. It needs to be rebased on the last few commits, but it's ready to publish pretty much

**Comment by jesseshieh** [comment]
Oh awesome! I should have known you'd already be on top of it =) Wow, looks like a pretty big change. Is this considered a breaking change or does it make sense to continue to support `mix release` for apps not on elixir 1.9.

**Comment by bitwalker** [comment]
@jesseshieh The bulk of the change is just namespace changes, but it should be considered a breaking release, in that the public APIs and the Mix tasks now fall under new namespaces, e.g. `mix distillery.release`, `distillery.release.clean`, `distillery.init`, and `distillery.gen.appup`; as well as the plugin/config APIs, `Distillery.Release.Config`, and `Distillery.Release.Plugin`. Basically whatever was under `Mix.Release.*` is now `Distillery.Release.*`.

Longer term, I plan to rebuild Distillery's extra functionality on top of the Elixir release tooling, but I have not had time to think that through, or whether it is truly necessary, but I will be releasing the 1.9 compatible version _before_ 1.9 drops, so people have a chance to upgrade.

**Comment by bitwalker** [comment]
I just today forked off the older 2.0.x branch, and merged the elixir19 changes into master, as 2.1.0. I won't be releasing it right away, but by the end of the month for sure.

**Comment by jesseshieh** [comment]
Awesome! Thanks again.
