### ISSUE TITLE
Publishing Version 2.1.0

### ISSUE THREAD

**Issue by rupurt** [bitwalker/distillery#686]
Hi,

I see that there is a commit message for `Version 2.1.0`. But it doesn't look like it's been published to hex. Is there anything besides the official release of `Elixir 1.9` holding a new package back? I'd like to use some of the refactored models in a package I'm building.

Cheers 🍻

**Comment by smaximov** [comment]
It's [published](https://hex.pm/packages/distillery/2.1.0) now 🎉 .
