### ISSUE TITLE
Distillery vs Elixir 1.9 releases

### ISSUE THREAD

**Issue by midas** [bitwalker/distillery#720]
Hi Paul.  Sorry to ask this question here but I cannot find any good opinions/documentation on it

I am at a loss for if I should begin to use Elixir 1.9 releases or stick with Distillery at this point.  Is there any documentation comparing what each can and cannot do?  Any info/opinion/guidance you can provide would be greatly appreciated.  Thanks!

**Comment by davearel** [comment]
This is a fair question-- would be good to address

**Comment by tanweerdev** [comment]
> This is a fair question

Indeed. Very much needed for Elixir community

**Comment by bitwalker** [comment]
The bottom line: if you rely on hot upgrades/downgrades, then 1.9 releases do not support those (yet); while Distillery does. If you don't need hot upgrades/downgrades, then you should switch to using 1.9 releases.

Distillery will continue to be maintained until hot upgrade support makes it way into core, at which point I will archive the project; but for now it is still needed in some systems.
