### ISSUE TITLE
release-init --release-per-app fails in complex umbrella project

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/distillery#73]
### Steps to reproduce

A complex umbrella project is failing to init the distillery configuration. Will update ticket as I narrow down on cause... :-) 

```
$ mix release.init --release-per-app
** (UndefinedFunctionError) function nil.project/0 is undefined or private
    nil.project()
    anonymous fn/1 in Mix.Tasks.Release.Init.get_umbrella_bindings/1
    (mix) lib/mix/project.ex:211: Mix.Project.in_project/4
    (elixir) lib/file.ex:1145: File.cd!/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/distillery/tasks/init.ex:79: Mix.Tasks.Release.Init.get_umbrella_bindings/1
    lib/distillery/tasks/init.ex:46: Mix.Tasks.Release.Init.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```
### Description of issue
- What OS, Erlang/Elixir versions are you seeing this issue on?

Elixir 1.3.2, Erlang 18.
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

`rel` dir is empty.

**Comment by bitwalker** [comment]
Do you have anything under `apps` which isn't an Elixir project directory? From the code I could see that causing an issue.

**Comment by martin-langhoff** [comment]
There shouldn't have been, but there was. I had an "empty" `apps/foo` directory (actually it contained a hidden file) from an experimental branch. Removing the stray empty dir from `apps` fixed it. Thanks.

Up to you on whether this is worth fixing (code, faq) or just closed :-)

**Comment by bitwalker** [comment]
Good news! This is an easy one to fix, it's actually been tackled in the assembler previously, but the init task got missed I suppose. I'll get it on the TODO list :)
