### ISSUE TITLE
Upgrade isn't permanent

### ISSUE THREAD

**Issue by manuel-rubio** [bitwalker/distillery#732]
### Steps to reproduce

Create a release and then a new release with upgrade option. Then run the old release, perform an upgrade to the new one, stop the running system and start it again. It starts using the old version.

Linked to this, the upgrade isn't using the new `priv` directory (based on Phoenix applications this means you're still using old static files).

### Description of issue

- What version of Distillery? **2.1.1**
- What OS, Erlang/Elixir versions are you seeing this issue on? **Debian GNU/Linux Buster 10, Erlang/OTP 22, Elixir 1.9.4**
- The release file is the default generated, I didn't change anything.

**Comment by pvmart** [comment]
Related to #729, fixed by 82ebcb2, merged in master. @bitwalker will you care to deploy new release please?

**Comment by noizu** [comment]
Ditto, It's quite problematic as each node on my cluster services a few hundred thousand devices and the hard restarts for minor code updates are problematic, but so are version mismatches. ^_^

**Comment by manuel-rubio** [comment]
Slowly and sadly stopped using Distillery and hot-code upgrade.
