### ISSUE TITLE
Make hooks into conf.d style dirs [ENH]

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/distillery#76]
It'd be much better to have `start_hook` and friends be _directories_, where scripts found following a certain name pattern are sourced/executed in alphabetical order.

A simple name pattern ("must end with `.hook`, must start with alphanum), helps prevent accidental execution of hidden/temp, conflict files (`.rej`, `.rpmsave`), and other floatsam and jetsam.

It'd be a good idea to do it now (pre `1.0`), as it's API vs other modules.

**Comment by bitwalker** [comment]
I agree, this has been in my mental todo list recently. Let's make this a priority.

**Comment by martin-langhoff** [comment]
I've implemented this a couple times, can bring in known-good code.

**Comment by bitwalker** [comment]
That would be excellent :)

**Comment by spscream** [comment]
Good Idea, but what if project has some dependencies? e.g I have project with conform dependency and conform has its own hook. Now conform hook can be added as pre_start_hook at rel/config.exs. I think it would be good to make possible run hooks from dependencies without any additional configuration, e.g. if dependency has rel/hooks/ directory, then content should be treated as hooks  and must run on release .start/stop/etc.?

**Comment by spscream** [comment]
added implementation ;)

**Comment by spscream** [comment]
@martin-langhoff hm, tried to use hooks implementation with busybox shell inside of alpine:edge docker container, and `read` command returns `read: line 723: illegal option -d`, do you know is there any alternatives to replace `read` command?

**Comment by martin-langhoff** [comment]
Gah, I wasn't expecting ~~the Spanish Inquisition~~ busybox! From what I see, it uses `ash` (or a variant thereof).

From an initial look-around, I don't spot any good alternatives (IFS can't handle null, there's no `ash` mailing list or irc channel to ask ideas, limited docs...). Maybe we can rig something up using `find ... printf "%q"` but I doubt we'll get what we want portably.

What follows is IMHO, and I'm not the maintainer, so feel free to ignore :-)

Aiming for complete lowest common denominator in shell interpreter is, IMO, spending sizable effort for little or no gain. `dash` on F23 x86-64 (optimized for speed, not binary size) is 120k, and that's as bloated as it'll get.

Anyone caring for `dash` vs `busybox` size cannot afford the Erlang runtime footprint.

I'd prefer we use `bash` with GNU tools. I can rationalize making sure things run on `dash` (Debian), and on old BSD-style tooling (OSX, actual BSDs). I can't rationalize the sizable effort _in this context_. I've done embedded work using busybox, where the tradeoff made sense.

Surely the docker container can be told we need dash or bash? no?

**Comment by spscream** [comment]
Currently we use msaraiva/elixir as a base image to run our releases, surely I could make a base image based on it with bash installed, but it will be additional layer to receive from docker registry, and this is only case then we need bash inside of it, so better than additional layer is a right script working everythere :)

**Comment by bitwalker** [comment]
Given that we've gotten this far with `sh` compatibility, I'd prefer to maintain that. If it becomes too much of a problem, I'm ok with switching to `bash`, but it looks like for now we're probably fine. I'm going to close this since this feature has been merged (as well as the fix for busybox).
