### ISSUE TITLE
Undefined applications

### ISSUE THREAD

**Issue by aaronjensen** [bitwalker/distillery#8]
Here are two applications we use that aren't working w/ distillery currently

https://github.com/aaronjensen/distillery_repro

```
$ mix release
==> Assembling release..
==> Building release distillery_repro:0.1.0 using environment default
==> Including ERTS 7.3 from /Users/aaronjensen/.asdf/installs/erlang/18.3/lib/erlang/erts-7.3
==> Failed to build release:

    Undefined applications: [exq,syslog]
```

**Comment by bitwalker** [comment]
Thanks for the repo! I'll take a look now and follow up.

**Comment by bitwalker** [comment]
Found the source of the problem, I can build a release of that repo now :)
