### ISSUE TITLE
Move release output to _build

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/distillery#82]
Instead of pushing build output into `rel/<release_name>`, we should leverage `_build` for these.
- [x] Move `rel/<release_name>/*` to `_build/<env>/rel/<release_name>/*`
- [x] Modify `release.clean`
- [x] Document changes, add notice to README

**Comment by michalmuskala** [comment]
If we do this - does it make sense to keep the `rel` directory at all? The only thing in there would now be the config file. Wouldn't a better place for this config be, for example, `config/rel.exs` or even `config/release.exs`?

**Comment by AndrewDryga** [comment]
+1 for `config/release.exs`

**Comment by bitwalker** [comment]
I've had the discussion about the usage of `rel` vs `config` numerous times in issues here already, but the gist is this: `config` is for runtime configuration, release configuration does not belong there, and often has other dependencies specific to release (such as a custom vm.args or sys.config, or others), grouping those things together in one place is the purpose of `rel`. The usage of `rel` for this is a convention from Erlang as well. For the time being I plan to keep using this directory for those things, except for now that entire directory can be source controlled without worrying about generated files being included on accident.

**Comment by michalmuskala** [comment]
Makes sense, thank you.
