### ISSUE TITLE
ERTS Version Not Well Detected 

### ISSUE THREAD

**Issue by bokay** [bitwalker/distillery#87]
First of all, thank you for your great work 👍 
### Steps to reproduce
- Create a dockerfile  with`FROM bitwalker/alpine-erlang:latest`
- Set a phoenix project with `include_erts: false` in `rel/config.exs`
- Build the release with `MIX_ENV=prod mix release --env=prod`
- Build the dockerfile
- Try to run the build running `CMD ["/app/bin/perahealth", "foreground"]`
### Verbose Logs

Output of the release command ran with the `--verbose` flag.

```
==> Generated overlay vars:
    release_name=:project
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=false
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="7.2.1"
    output_dir="rel/project"
```
### Description of issue

After building the dockerfile successfully, I get this when trying to run the image:

```
➜  docker logs project
Wed Sep 28 16:05:00 EDT 2016
/app/releases/0.0.1/project.sh: line 621: /usr/lib/erlang/erts-7.2.1/bin/erlexec: not found
Shutting down node cleanly..
/app/releases/0.0.1/project.sh: line 621: /usr/lib/erlang/erts-7.2.1/bin/escript: not found
Node is not running!
```

In the Dockerfile, I've explicitly printed the content of the folder `/usr/lib/erlang` and it outputs : 

```
Step 16 : RUN ls /usr/lib/erlang/
 ---> Running in 09a2c623450a
Install
bin
erts-7.3.1
lib
releases
usr
 ---> 65a9789a6d2a
```

I was expecting the project.sh script to use that ERTS `7.3.1` version instead of `7.2.1`.
This issue is similar to : https://github.com/bitwalker/distillery/issues/20

**Comment by bitwalker** [comment]
That's bizarre, how is it picking up 7.2.1? I'm using this image in production at work as well and I haven't yet seen this. Could you gist your whole Dockerfile?

**Comment by bokay** [comment]
Here is the Dockerfile that I'm using : 
https://gist.github.com/bokay/34bd52e56fb0d3b43d49450349841f5d
I always use the version 0.0.1 and I build and commit the release generated by distillery locally.

**Comment by sschneider1207** [comment]
I'm having this issue as well. I built a release on windows that has erts 8.0, `include_erts: false` and deployed it to ubuntu with erts 8.1.  The project.sh script tries to use the erts 8.0 path that I assume it got from the windows machine instead of the erts version from the machine it's currently on.

**Comment by bitwalker** [comment]
Have you tried this with 0.10?

**Comment by bokay** [comment]
@bitwalker I've just tried with version `0.10.1` and ran into the same issue.

**Comment by bokay** [comment]
Hi @bitwalker 

Sorry for the delay. I've tried with the last version of distillery and confirm that the bug is still present.

If I understand correctly, I think you are running the same version Erlang version on your machine as on the docker image.
I think the issue is located here : https://github.com/bitwalker/distillery/commit/9ebc0208aeb373d068c4625dbf6addf312d6b755#diff-8e1a1749b553223a5202b250e93f3e57R20

The script will never try to detect the version on the running machine at this point as the value is already written with the local Erlang version: https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L258

Does that makes sense to you too ?

**Comment by jarrodtaylor** [comment]
+1

I'm running into the same issue.

MacOS dev machine:

    elixir --version
    Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
    Elixir 1.3.4

Arch Linux server:

    elixir --version
    Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
    Elixir 1.3.4

Not running Docker or anything. The `erts-8.1` vs `erts-8.1.1` is blocking the app from starting up.

**Comment by bitwalker** [comment]
Could you all give master a try?

**Comment by madshargreave** [comment]
@jarrodtaylor Did you find a solution?
