### ISSUE TITLE
ignore missing application 

### ISSUE THREAD

**Issue by slashmili** [bitwalker/distillery#88]
Just to be clear, It's just a suggestion.

Every now and then I find my self forgetting to add an application to the list(mostly for libraries) so I enabled `--warnings-as-errors` option which works as I expected.

Everything was good until I added `elixir_make` to my dependency list. I need it to build the project but don't want to include it in release.

What do you think of a settings somewhere to ignore an app if it's not in the `:applications` or `:included_applications` list

**Comment by goofansu** [comment]
This has been solved in https://github.com/bitwalker/distillery/issues/84
