### ISSUE TITLE
Make plugins configurable per-release

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/distillery#9]
Currently all plugins are global and there's no way to disable them. An example use case is building a `.deb` package for the production release, but skipping this for the dev one. 

The new configuration features in `rel/config.exs` are a great place to accommodate enabling plugins explicitly. Not only this goes with elixirs philosophy of `explicit > implicit`, but this would also allow to remove all the shenanigans with traversing beams to find modules that implement the plugin behaviour, simplifying the code considerably.

**Comment by bitwalker** [comment]
I actually really really like this idea. Consider it done. The following is how I plan to implement it:

```elixir
environment :prod do
  plugin Conform.Release
end
```

The `plugin` macro will work in both `environment` and `release` blocks.

**Comment by bitwalker** [comment]
Done and released in 0.8!

**Comment by michalmuskala** [comment]
Thank you!
