### ISSUE TITLE
Conform not executed after an upgrade

### ISSUE THREAD

**Issue by vishnevskiy** [bitwalker/distillery#92]
### Steps to reproduce

Just run a hot upgrade and the conform `pre_start` hook will not be executed until you restart the VM resulting in the default `sys.config`.
### Description of issue

I believe I have previously reported and provided a PR for `exrm` for the same issue. This time however there does not seem to be a clear path to do this since the system is hook based and not intertwined and the executing script of the upgrade is for the previous VSN.

**Comment by bitwalker** [comment]
I'll need to add `pre_upgrade` and `post_upgrade` hooks in order to make this work properly, which is effectively how I did it in exrm.

**Comment by vishnevskiy** [comment]
Actually it seems that downgrades do not work either since the upgrade/downgrade system wants the `sys.config` in the specific release folder to have the correct information and everything is setup to only write to the root release directory.

**Comment by spscream** [comment]
@bitwalker I can take this, if you want

**Comment by bitwalker** [comment]
Now that #123 is merged, all that's needed is for conform to tie in to the new hooks to handle the configs correctly

**Comment by bitwalker** [comment]
I'm going to close this, since the issue with Distillery itself has been resolved. I'll track this in the conform repo.
