### ISSUE TITLE
[documentation] coverage information is missing

### ISSUE THREAD

**Issue by sobolevn** [bitwalker/distillery#95]
For some reason the badge is broken. 

<img width="643" alt="2016-10-04 14 03 09" src="https://cloud.githubusercontent.com/assets/4660275/19071966/5dacf142-8a3b-11e6-8799-8ec2d41ed0de.png">

Repo does not exist on coveralls.io: https://coveralls.io/github/bitwalker/distillery?branch=master

**Comment by bitwalker** [comment]
Ha, I'll get that fixed, thanks!

**Comment by bitwalker** [comment]
Repo has been added to coveralls, thanks!
