### ISSUE TITLE
0.10.0 breaks REPLACE_OS_VARS

### ISSUE THREAD

**Issue by teamon** [bitwalker/distillery#96]
Since https://github.com/bitwalker/distillery/compare/0.9.9...0.10.0#diff-8e1a1749b553223a5202b250e93f3e57L180 the `orig_vmargs_path` is no longer set.

### Steps to reproduce

Make a release and set `REPLACE_OS_VARS=true` env variable.

### Verbose Logs

```bash
$ DEBUG_BOOT=true ./myapp.sh
# ...
+ _replace_os_vars  /opt/app/var/vm.args
./myapp.sh: line 1: can't open : no such file
+ awk
        function escape(s) {
            gsub(/&/, "\\\\&", s);
            return s;
        }
        {
            while(match($0,"[$]{[^}]*}")) {
                var=substr($0,RSTART+2,RLENGTH-3);
                gsub("[$]{"var"}", escape(ENVIRON[var]))
            }
        }1
```

**Comment by spscream** [comment]
the same issue with sys.config:
https://github.com/bitwalker/distillery/compare/0.9.9...0.10.0#diff-8e1a1749b553223a5202b250e93f3e57R266

orig_sys_config_path is not set in current version

**Comment by mtaylor91** [comment]
I'm running into this as well; tried using REPLACE_OS_VARS=true as a workaround when my original attempt to dynamically set the cookie using a pre-start hook failed (see https://github.com/bitwalker/distillery/issues/100)

**Comment by jschniper** [comment]
I've run into this as well. Looks like the variable might have been lost in commit 9ceefaf

**Comment by spscream** [comment]
created pr with fix
