### ISSUE TITLE
Documentation: add details about `set cookie: <cookie>`

### ISSUE THREAD

**Issue by brunogirin** [bitwalker/distillery#97]
### Steps to reproduce

When doing `mix release` with distillery 0.10, it displays a warning about `set cookie:`. However, the [documentation](https://hexdocs.pm/distillery/configuration.html#environment-release-settings) doesn't include anything about that setting.

### Verbose Logs

```shell
$ mix release
==> Assembling release..
==> Building release imby_platform:0.1.0 using environment dev
==> Attention! You did not provide a cookie for the erlang distribution protocol in rel/config.exs
    For backwards compatibility, the release name will be used as a cookie, which is potentially a security risk!
    Please generate a secure cookie and use it with `set cookie: <cookie>` in rel/config.exs.
    This will be an error in a future release.
==> You have set dev_mode to true, skipping archival phase
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: rel/imby_platform/bin/imby_platform console
      Foreground: rel/imby_platform/bin/imby_platform foreground
      Daemon: rel/imby_platform/bin/imby_platform start
```

### Description of issue

- What are the expected results? The documentation should include details about the `cookie` setting
- What OS, Erlang/Elixir versions are you seeing this issue on? Ubuntu 16.04, Elixir 1.3, Erlang 19
- Is there documentation that says one thing, but Distillery does
  another? Yes, see here: https://hexdocs.pm/distillery/configuration.html#environment-release-settings

**Comment by bitwalker** [comment]
I'll get this updated, thanks!

**Comment by brunogirin** [comment]
Excellent, thanks!

**Comment by DavidOliver** [comment]
Noob here. Could I ask what exactly this particular cookie setting is and how it relates to security (or where I should go to read about it)? Should it usually be handled by an environment variable rather than the rel/config.exs file? Many thanks.

**Comment by bitwalker** [comment]
@DavidOliver The cookie is used for authenticating Erlang nodes to communicate with one another, you can read more about it [here](http://erlang.org/doc/reference_manual/distributed.html#id88360). You can provide it via environment variable or `rel/config.exs`, or via some other means (i.e. Puppet/Chef/etc.). In the past I've used first two depending on requirements.
