### ISSUE TITLE
Rename command to run

### ISSUE THREAD

**Issue by scrogson** [bitwalker/distillery#98]
@bitwalker what do you think about renaming `command` to `run`. Not only is a shorter, but it seems more semantically correct to me.

**Comment by bitwalker** [comment]
I do like the verb better, I'm open to the change :)

**Comment by bitwalker** [comment]
With the changes to `eval` in the 2.x timeframe, `command` can be removed, and one can just use `eval` instead, with `:init.get_plain_arguments/0` to fetch any additional arguments.
